ext/bg/js/display-window.js, ext/bg/search.html
Adds #32 by using wanakana IME on the search query field
=> Add romaji input to search

ext/bg/js/dictionary.js, ext/bg/js/templates.js, ext/bg/js/translator.js, ext/mixed/js/japanese.js, tmpl/fields.html
Requires a bit more testing, but seems to work reasonably well
=> Change the {furigana} marker for anki export to distribute furigana over kanji

ext/mixed/js/display.js
Analogous to Alt+up/down which does the same thing
=> Go to next and previous result with Alt+wheel

ext/bg/js/dictionary.js, ext/bg/js/translator.js
Fixes errors with main dictionary other than JMdict. Forgot to do this together with `definitionTags`
=> merged mode: expand termTags earlier

ext/bg/js/options.js, ext/bg/js/settings.js, ext/bg/settings.html, ext/fg/js/float.js, ext/fg/js/frontend.js, ext/fg/js/popup.js, ext/mixed/js/display.js
Same as #102 but against the `dev` branch. Sorry for the mistake, this is actually the first time I mess with a browser extension. :)
=> Add option to play audio automatically

ext/fg/js/document.js
Hides the imposter element once we've finished using it and checks the y position for the range against the point given
=> Fixes for imposter element and range y position

ext/bg/js/options.js, ext/bg/js/settings.js, ext/bg/settings.html, ext/fg/js/float.js, ext/fg/js/popup.js
Allows user-defined CSS to be injected into the popup window.
=> Add support for custom popup CSS

ext/fg/js/document.js, ext/mixed/js/display.js
* Use a cached value for checking if the browser is Firefox.
* Only validate and set up document.caretRangeFromPoint once.
* Use switch for multiple comparisons on the same value.
=> Doc range from point improvements

ext/bg/js/settings.js
As mentioned in https://github.com/FooSoft/yomichan/pull/188#discussion_r317863915
=> Replace double quotes with single quotes

ext/fg/js/document.js
See https://github.com/FooSoft/yomichan/issues/191#issuecomment-526400339 for more details.
This fixes the issue by increasing the range to include 1 character in forward direction, and then performing a point-in-rect check. If this fails, the range is changed to include 1 character in the backward direction and the point-in-rect check is retried.
Tested on Firefox Developer Edition 70, Chrome Dev 78, primarily using https://tategaki.github.io/awards2015/
Fixes #173
Fixes #191
=> Update isPointInRange to be more accurate

ext/bg/js/api.js, ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/settings.html, ext/fg/js/api.js, ext/fg/js/frontend.js
Following the commit history may tell a better story than the total diff, but here's a high-level overview:
* First 5 commits are HTML and styling changes.
* Next 2 commits add some validation to the options loading process.
* Next 2 commits refactor the options update process.
* Last 4 commits are intended to clean up and simplify the flow of how options updates are propagated.
I'm trying to keep this description somewhat brief since the commits may speak for themselves, but let me know if I can clarify or expand upon anything.
The goal of this change is to provide a better starting point for some changes to support multiple settings as discussed in #185. It seemed like a better idea to put these changes up for review separately to avoid making everything too convoluted.
=> Settings improvements

ext/fg/js/frontend-api-sender.js
While testing some other features, I ran into an issue where ports sometimes won't communicate with all frames due to non-deterministic load-order of frames. While this should not have affected existing features using this code, deferring the creation of a Port resource until it's required should be of slight benefit.
=> Defer creation of communication port until required

ext/bg/js/api.js, ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/js/settings-profiles.js, ext/bg/js/settings.js, ext/bg/settings.html
This change adds support for multiple profiles; the diff should be a bit more straightforward since all of the prerequisites were taken care of in #204, #205.
=> Settings profiles

ext/bg/js/options.js, ext/bg/js/settings.js, ext/bg/settings.html, ext/mixed/js/display.js
I liked @toasted-nutbread's rendition of the nested popups and so decided to add an option to enable @siikamiika's first popup search in case anyone got annoyed by having both.
Also, I'm reposting this because of git issues I had due to inexperience.
Fixed the change request too.
=> Add option to enable Alt+B lookup

ext/bg/js/conditions-ui.js, ext/bg/js/settings.js, ext/mixed/js/extension.js
Fixes several issues on Microsoft Edge.
=> Use toIterable for cross-window origin objects

ext/bg/js/database.js
Fixes #245. Meta database lookups were trying to row.id, but row.id was undefined.
=> Fix findTermMetaBulk trying to use undefined row.id

ext/fg/float.html
Creating this as a PR in order to ask: does anyone know if this reference is used for something? As far as I can tell it's unused, but I want to make sure I'm not overlooking anything.
=> Remove wanakana reference from float.html

ext/bg/data/options-schema.json, ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/js/settings/main.js, ext/bg/js/settings/popup-preview-frame.js, ext/bg/settings.html, ext/fg/css/client.css, ext/fg/js/float.js, ext/fg/js/frontend.js, ext/fg/js/popup-proxy-host.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js, ext/mixed/css/display.css, ext/mixed/js/api.js, ext/mixed/js/core.js
Adds support for custom scaling of popups, including scaling relative to page zoom level. Also includes a little bit of cleanup near where some related changes were made.
Resolves #315.
=> Popup scaling

ext/bg/data/options-schema.json, ext/bg/js/search-query-parser.js, ext/bg/js/settings/main.js, ext/bg/settings.html, ext/mixed/css/display.css, ext/mixed/js/japanese.js
=> Query parser helper disabling

ext/bg/js/settings/popup-preview-frame.js, ext/fg/js/document.js, ext/fg/js/source.js, ext/mixed/js/text-scanner.js
Fixes https://github.com/FooSoft/yomichan/pull/317#issuecomment-578397929
=> Fix imposter scanning

ext/bg/js/dictionary.js, ext/bg/js/translator.js, ext/mixed/js/display-generator.js
Fixes the bug noted in #337. First commit is some refactoring, the second is the fix.
=> Translator refactoring

ext/bg/js/settings/dictionaries.js, ext/bg/js/settings/main.js
Fixes https://github.com/FooSoft/yomichan/pull/338#issuecomment-579957698
=> Main dictionary settings fix

ext/bg/js/json-schema.js
Improves the capabilities of the JsonSchema classes.
* Adds support for conditionals
* Adds support for `allOf`, `anyOf`, `oneOf`, and `not`
* Better array validation
* Simplified validation errors (now just using `throw` instead of `return`)
* Adds improved information about validation errors (path to the offending field is tracked)
* Fixes some bugs
=> JSON schema improvements

ext/bg/js/search.js, ext/fg/js/float.js, ext/fg/js/frontend.js, ext/fg/js/popup-proxy-host.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js, ext/mixed/js/display-generator.js, ext/mixed/js/display.js
I couldn't remove the `isPrepared` calls from `Display` yet. That would require some additional handling in `Popup`. But this simplifies `DisplayGenerator`.
#356
=> Simplify display prepare

ext/bg/js/api.js, ext/bg/js/backend.js, ext/bg/js/dictionary.js, ext/bg/js/handlebars.js, ext/bg/js/translator.js, ext/fg/float.html, ext/mixed/js/api.js, ext/mixed/js/audio.js, ext/mixed/js/core.js, ext/mixed/js/display.js
Wanted to get a sanity check on these changes, and it felt like overkill to submit each of these as an individual PR, so this PR contains a bunch of miscellaneous refactorings. Easiest to read on a commit-by-commit basis since the scope of each is different.
=> General refactoring

ext/fg/js/float.js, ext/fg/js/frontend-api-sender.js, ext/fg/js/frontend.js, ext/fg/js/popup-proxy-host.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js, ext/mixed/js/core.js
=> Popup init fix

.eslintrc.json, .github/workflows/nodejs.yml, .gitignore, package-lock.json, package.json
This is the initial setup which can be used to run some unit tests, as mentioned in #345. Right now I just have it set up for lint tests.
I set the version on the package file to 0.0.0, since I don't know if we want to maintain a version number in two places, and this package is used for testing, not for building.
~Depends on #344, since it fixes some linting issues. I could also cherry pick the commits that fix the issues into master and remove them from that PR too if that needs more work.~
No longer necessary due to https://github.com/FooSoft/yomichan/pull/344#issuecomment-583795713.
=> Setup GitHub actions

ext/bg/js/backend.js, ext/bg/js/settings/popup-preview-frame.js, ext/fg/js/popup.js, ext/manifest.json, ext/mixed/js/api.js
Creating this as a PR now to allow some testing to see if this works. I have noticed that this causes about:blank pages to not work, so it's not ready to be merged unless that can be fixed.
=> Defer content script css injection

package-lock.json, package.json, test/data/html/test-document1.html, test/data/html/test-stylesheet.css, test/test-document.js, test/test-stylesheet.css
Tests for some of the functions in [document.js](https://github.com/FooSoft/yomichan/blob/master/ext/fg/js/document.js). This demonstrates that it can be possible to test some of the DOM-based functionality without requiring a web browser. This will be useful for #286 and future related changes.
=> Document tests

ext/bg/js/translator.js
=> compatibility transform non-primary definitions

.eslintrc.json, test/data/html/test-document2-frame1.html, test/data/html/test-document2-script.js, test/data/html/test-document2.html, test/data/html/test-stylesheet.css
https://github.com/FooSoft/yomichan/pull/417#discussion_r400582235
=> Create some tests for fullscreen elements, <iframe>s, and shadow DOMs

README.md, ext/bg/data/default-anki-field-templates.handlebars, ext/bg/js/anki-note-builder.js, ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/js/settings/anki-templates.js, ext/bg/js/settings/anki.js, ext/fg/js/float.js, ext/fg/js/frontend.js, ext/mixed/js/api.js, ext/mixed/js/display.js
Resolves #414 with a new tag `{document-title}`. These changes can be used to easily add additional context data in the future.
=> Anki marker document title

ext/bg/css/settings.css, ext/bg/data/dictionary-index-schema.json, ext/bg/js/dictionary-importer.js, ext/bg/js/settings/dictionaries.js, ext/bg/settings.html
Add support for the extra dictionary information added in #385, mentioned in #429.
=> Extra dictionary information

ext/fg/js/frontend.js
=> Fix default value of _orphaned

ext/bg/js/backend.js, ext/bg/js/database.js, test/lint/global-declarations.js
Does a very basic substring test on all global declarations.
=> Check for unused globals as part of CI

ext/bg/js/backend.js, ext/bg/js/japanese.js, ext/bg/js/mecab.js, ext/bg/js/search-query-parser-generator.js, ext/bg/js/search-query-parser.js, ext/mixed/js/api.js, test/test-japanese.js
Fixes https://github.com/FooSoft/yomichan/issues/418
=> Parse text refactor

ext/bg/js/anki-note-builder.js, ext/bg/js/anki.js, ext/bg/js/backend.js
Resolves https://github.com/FooSoft/yomichan/pull/427#issuecomment-609493372
=> Reuse AnkiConnect instance

ext/bg/js/search.js, ext/bg/js/settings/popup-preview.js
As mentioned in https://github.com/FooSoft/yomichan/pull/463#issuecomment-616831927
=> Use wanakana object directly

ext/bg/js/backend.js
Fixes https://github.com/FooSoft/yomichan/issues/473
Broken in https://github.com/FooSoft/yomichan/pull/380
=> fix custom anki templates

ext/bg/js/search-main.js, ext/bg/search.html, ext/fg/float.html, ext/fg/js/float-main.js
Initial setup for removing usage of `frontendInitializationData`. Next changes will need to touch content-script-main.js, which would be in conflict with #464, so they can come after that.
=> Use dynamicLoader for main

ext/bg/data/options-schema.json, ext/bg/js/anki-note-builder.js, ext/bg/js/anki.js, ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/js/settings/main.js, ext/bg/settings.html
See: https://github.com/FooSoft/anki-connect/pull/157
=> Add duplicateScope: 'deck' option

ext/bg/js/backend-api-forwarder.js, ext/bg/js/backend.js, ext/fg/js/frontend-api-receiver.js, ext/fg/js/frontend-api-sender.js, ext/fg/js/popup-proxy-host.js
#258, https://github.com/FooSoft/yomichan/pull/463#issuecomment-617431416
=> Refactor frontend API classes

ext/mixed/js/object-property-accessor.js, test/test-object-property-accessor.js
Added `delete` and `swap`; simplified names; added documentation; updated tests.
=> Object property accessor API update

ext/fg/js/source.js
Fixes https://github.com/FooSoft/yomichan/pull/488#issuecomment-622607016
https://dom.spec.whatwg.org/#dom-range-compareboundarypoints
=> Catch WrongDocumentError thrown by compareBoundaryPoints

ext/fg/js/document.js, ext/fg/js/float.js, ext/fg/js/popup.js, ext/mixed/js/dynamic-loader.js
=> Validate document nodes before use

.eslintrc.json, ext/bg/js/backend.js, ext/fg/js/source.js
Fixed a few styles with the same issue pointed out in https://github.com/FooSoft/yomichan/pull/490#discussion_r418788009. Searched for an eslint rule but didn't find one. Added a few related eslint rules instead.
=> Style fixes

ext/mixed/js/audio-system.js
Fixes https://github.com/FooSoft/yomichan/pull/477#issuecomment-623004922?
(Copied wrong class name from the top of the file.)
=> Fix incorrect static call

ext/bg/js/search-query-parser.js, ext/fg/js/frontend.js, ext/mixed/js/text-scanner.js
Resolves https://github.com/FooSoft/yomichan/pull/487#issuecomment-621438659
=> Extract textSource text inside TextScanner

ext/bg/js/anki-note-builder.js, ext/bg/js/anki.js
Resolves https://github.com/FooSoft/yomichan/pull/477#discussion_r417623091.
This change also makes the use of "filename" vs "fileName" more consistent.
=> Remove invalid file name characters from Anki media files

ext/bg/background.html, ext/bg/js/backend.js, ext/bg/js/search-query-parser.js, ext/bg/js/search.js, ext/mixed/js/api.js
Replace `apiOptionsSet` with new `apiModifySettings`, which uses `ObjectPropertyAccessor` and the options schema. This new function will be used as the basis for #335.
=> Add apiModifySettings

ext/bg/js/settings/popup-preview-frame.js, ext/fg/js/frontend.js
This time updating functions/fields to be private.
In a future commit, it would probably be a good idea to organize the functions so that they are logically grouped together. But that should be handled in a separate commit where that is the only thing being done, otherwise the diff will be very difficult to follow.
=> Frontend refactor

ext/bg/js/search-query-parser.js
=> Remove search query parser inheritance

ext/fg/js/frontend.js
Addresses https://github.com/FooSoft/yomichan/pull/508#issue-412709438:
> In a future commit, it would probably be a good idea to organize the functions so that they are logically grouped together. But that should be handled in a separate commit where that is the only thing being done, otherwise the diff will be very difficult to follow.
There are no changes other than moving functions around. The intent is to make it easier to quickly find functions.
=> Organize frontend functions

ext/bg/js/search-query-parser.js
Sets up private members and organizes. The organization was done in the same PR in this case since there were only two functions to be moved.
=> Query parser refactor

ext/mixed/js/text-scanner.js
Basically just making things private. Similar to #513, I think the reorganization change should be done separately.
=> Text scanner refactor

ext/mixed/js/audio-system.js
=> Fix not awaiting the AudioSystem.arrayBufferDigest promise

ext/bg/data/default-anki-field-templates.handlebars, ext/bg/js/options.js
Resolves https://github.com/FooSoft/yomichan/pull/524#issuecomment-626194778
=> Omit the sound tag if it's empty

ext/fg/js/source.js
Fixes https://github.com/FooSoft/yomichan/pull/507#issuecomment-626200248.
The API of TextSourceElement needs to be updated to match TextSourceRange, but that's a bit of a larger task.
=> Fix setStartOffset not appending

ext/fg/js/source.js
Addresses https://github.com/FooSoft/yomichan/pull/526#issue-415603889:
> The API of TextSourceElement needs to be updated to match TextSourceRange, but that's a bit of a larger task.
After both of these PRs, I will probably split `TextSourceRange/TextSourceElement.setEndOffset` into two functions:
* `setEndOffset`, which follows the behaviour of `fromEnd=true`
* `setLength`, which follows the behaviour of `fromEnd=false`
=> Text source refactor

test/data/html/test-document2-frame1.html, test/data/html/test-document2-script.js, test/data/html/test-document2.html, test/data/html/test-stylesheet.css
There was a missing test for a standard open shadow DOM.
Using this to test https://github.com/FooSoft/yomichan/pull/529#issuecomment-626326989
=> Simplify shadow test and add an open shadow DOM test

ext/bg/js/search-main.js, ext/bg/settings-popup-preview.html, ext/fg/js/popup.js, ext/manifest.json, ext/mixed/js/dynamic-loader.js
Addresses https://github.com/FooSoft/yomichan/pull/518#issue-415011950:
> I am also thinking that it might be good to move `_injectStylesheet` into `dynamicLoader`.
=> Dynamic loader load style

README.md
Resolves #543; resolves #547; resolves part of #546.
=> Update readme URLs

ext/mixed/js/core.js
=> Add missing spreads

ext/bg/search.html, ext/fg/float.html, ext/mixed/css/display.css, ext/mixed/display-templates.html
This change is adjusting some styles and HTML to better support style/theme customization. The appearance should be the same. The main changes are:
* Removed some whitespace from the HTML which can interfere with layout depending on the styles being used.
* Updated a few styles to ensure there is still correct spacing due to the above change.
* Updated the icons to use pseudo-elements with `background-image` instead of an `<img>` element, allowing the images to be dependent on CSS rules.
=> Style adjustments

ext/bg/js/settings/backup.js, ext/bg/js/settings/main.js, ext/bg/js/util.js
Converts backup.js into a class. Moves `utilReadFileArrayBuffer` out of `util.js` and into this new class.
=> Settings backup refactor

ext/bg/legal.html
There were already links to the licenses, but it's probably safest to more explicitly satisfy the following condition:
```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```
=> Update legal.html to include full licenses

ext/bg/js/settings/dom-settings-binder.js, ext/mixed/js/dom-data-binder.js
Some fixes to #542 which weren't realized since it wasn't in use yet.
=> DOM binder fixes

ext/bg/js/settings/main.js, ext/bg/js/settings/settings-controller.js, ext/bg/settings.html
This will be the single common point for all setting controller modules, rather than having various variables and functions directly in the global scope and in somewhat-random files.
=> Create class to abstract access, mutation, and events for settings

ext/bg/js/settings/anki-templates.js, ext/bg/js/settings/anki.js, ext/bg/js/settings/main.js
Converts anki.js and anki-templates.js into classes.
=> Anki settings controllers

ext/bg/css/settings.css, ext/bg/js/settings/dictionaries.js, ext/bg/js/settings/main.js, ext/bg/js/settings/storage.js, ext/bg/settings.html
storage.js was also converted because it is semi-coupled to dictionaries.js.
=> Convert dictionaries.js and storage.js to classes

ext/bg/js/settings/popup-preview-frame-main.js, ext/bg/js/settings/popup-preview-frame.js
=> Popup preview frame refactor

ext/bg/js/settings/clipboard-popups-controller.js, ext/bg/js/settings/generic-setting-controller.js, ext/bg/js/settings/main.js, ext/bg/settings.html
`GenericSettingsController` will be superseded by #542 in the future.
=> Generic settings controller + clipboard popups controller

ext/bg/js/settings/anki-templates.js, ext/bg/js/settings/anki.js, ext/bg/js/settings/audio.js, ext/bg/js/settings/backup.js, ext/bg/js/settings/clipboard-popups-controller.js, ext/bg/js/settings/dictionaries.js, ext/bg/js/settings/dom-settings-binder.js, ext/bg/js/settings/generic-setting-controller.js, ext/bg/js/settings/main.js, ext/bg/js/settings/popup-preview.js, ext/bg/js/settings/profiles.js, ext/bg/js/settings/settings-controller.js
Updates all controller classes to use `SettingsController`.
=> Use SettingsController

ext/bg/js/settings/generic-setting-controller.js, ext/bg/js/settings/settings-controller.js, ext/bg/settings.html
Originally mentioned https://github.com/FooSoft/yomichan/pull/573#issue-422911356.
=> Update GenericSettingController to use DOMSettingsBinder

ext/mixed/css/display.css
Broken in 90af55d4c84f545635f238178b30748a0e8093ee
=> scale background icon when page is zoomed

ext/mixed/css/display.css
Broken in 90af55d4c84f545635f238178b30748a0e8093ee
=> fix css class name

ext/bg/js/backend.js, ext/bg/js/background-main.js
Addresses https://github.com/FooSoft/yomichan/issues/455#issuecomment-633134977
=> Immediate backend event handlers

ext/bg/js/backend.js
=> Update the badge icon if the backend experiences an error

ext/bg/js/audio-uri-builder.js, ext/bg/js/request.js, ext/mixed/js/audio-system.js, test/test-database.js
`XMLHttpRequest` is not available in service workers, so `fetch` must be used instead.
=> Replace XMLHttpRequest

ext/bg/background.html, ext/bg/js/backend.js, ext/bg/js/handlebars.js, ext/bg/js/template-renderer.js
First step of sandboxing the template rendering system.
https://github.com/FooSoft/yomichan/issues/455#issuecomment-633122831
=> Template renderer class

ext/bg/js/search.js
=> Handle stack overflow caused by wanakana.toKana

ext/mixed/js/display.js
=> Safely handle volume values that are out of range

ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/settings.html, ext/fg/js/popup.js
Add this as a fallback option. Testing to see if it affects #608.
=> Add option to use the unsecure frame URL

README.md
Fixes https://github.com/FooSoft/yomichan/issues/608#issuecomment-647156997.
=> Fix JMdict URL in README

README.md, ext/bg/context.html, ext/bg/css/context.css, ext/bg/guide.html, ext/bg/js/context-main.js
* Removed Bootstrap usage
* Moved styles to a separate file
* Updated icons
* Updated some terminology to reflect updated icons
=> Context popup update

ext/bg/js/search.js, ext/bg/js/settings/popup-preview-frame-main.js, ext/fg/js/content-script-main.js, ext/fg/js/float.js, ext/fg/js/popup-factory.js
=> Make PopupFactory.prepare non-async

ext/bg/js/backend.js, ext/fg/js/popup.js, ext/mixed/js/api.js, ext/mixed/js/core.js
Use new `deferPromise` function for pre-existing code which used the same pattern.
=> Use deferPromise

ext/bg/js/backend.js
* Functions and fields are now marked as private.
* Group functions together by type (public, private, event handler, etc.)
* A few minor renames and simplifications.
* Removal of `static` for private functions.
=> Backend refactor

ext/bg/js/backend.js, ext/bg/js/background-main.js
Simplification of #555. This helps to simplify the public API of `Backend`.
=> Merge BackendEventHandler into Backend class

ext/bg/js/template-renderer.js
=> Fix incorrect handlebars execution context in helpers

ext/bg/js/util.js, ext/mixed/js/core.js
Remove some unused functions and fix `clone` not being exposed on the background window object (temporary fix).
=> Util refactor and fix

ext/mixed/img/up-arrow.svg, resources/icons.svg
Generic up arrow icon, will be used for the "Top" link.
=> Add up arrow icon

ext/bg/js/search.js, ext/fg/js/float.js, ext/mixed/js/display.js
This change should be the final in the series of converting classes to use the underscore-prefix private convention. The `Display` class and its subclasses now use privates and have the functions organized.
=> Display class refactoring

.eslintrc.json
Resolves https://github.com/FooSoft/yomichan/pull/424#issuecomment-609039565.
=> Add no-underscore-dangle rule

ext/bg/js/backend.js, ext/bg/js/search.js, ext/bg/settings-popup-preview.html, ext/fg/float.html, ext/fg/js/float.js, ext/fg/js/popup.js, ext/manifest.json, ext/mixed/js/frame-client.js, ext/mixed/js/frame-endpoint.js
This change extracts the frame handshake mechanism set up in #497, as mentioned in https://github.com/FooSoft/yomichan/pull/497#issuecomment-624303727. This should make it easier to understand in general, since it's isolated from other functionality. In addition, this change adds support for detecting what the frameId is of the frame.
=> Generalized frame connections

ext/fg/js/frontend.js
For stylistic consistency with other message handlers.
=> Add support for async vs non-async

ext/bg/js/backend.js, ext/bg/js/search.js, ext/fg/js/frontend.js, ext/mixed/js/comm.js, ext/mixed/js/yomichan.js
This change makes message handling use shared functionality so that there is less repeated code.
=> Message handler refactor

ext/bg/js/anki.js, ext/bg/js/request.js
=> Fix Anki CORS requests

ext/fg/js/float.js, ext/fg/js/frontend.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js, ext/mixed/js/display.js, ext/mixed/js/yomichan.js
=> Extension unload indication fix

ext/bg/js/context-main.js
General simplifications. Should make the initial setup occur slightly faster, so less animation/state artifacts.
=> Refactor context-main.js

ext/bg/js/backend.js, ext/bg/js/search.js, ext/mixed/js/api.js
The search popup is now more reusable and there is now an API function to create it.
=> Reusable backend popup window

ext/bg/js/search.js, ext/fg/js/float.js, ext/mixed/js/display.js
This change moves some common functionality from `DisplayFloat` and `DisplaySearch` into the base `Display` class, including:
* Nested popup setup.
* Auto-play timer and delay (delay is now assigned by `DisplayFloat`).
* Cross-frame message handling, which is now extensible by subclasses.
* Initial assignment of `_optionsContext`.
=> Display refactoring

ext/bg/js/backend.js, ext/bg/js/dictionary-importer.js, package-lock.json, package.json, test/test-database.js
`DictionaryImporter.import` was renamed to `.importDictionary` to avoid naming conflicts with one of no-unsanitized's rules.
=> Dev dependencies updates

ext/bg/js/search.js
`setContent` and `clearContent` should be better places for the clearing action.
=> Update DisplaySearch.setContent/clearContent to close popups

ext/mixed/js/display.js
Various fixes, cleanup, organization, and merging of near-duplicate code.
=> Display fixes and refactoring

ext/bg/js/search.js, ext/fg/js/frontend.js, ext/fg/js/popup.js, ext/mixed/js/display-context.js, ext/mixed/js/display.js
Improves the structure of `setContent` function's arguments, and standardizes its use.
=> Set content refactor

ext/bg/js/template-renderer.js
=> Add eachUpTo function

ext/bg/js/search.js, ext/fg/js/frontend.js, ext/mixed/js/display.js
Improves scroll assignment and restoration upon navigation.
=> Display scroll refactor

ext/fg/js/float.js, ext/mixed/js/display.js
Use `camelCase` instead of `kebab-case`.
=> Standardize hotkey action naming convention

ext/bg/search.html, ext/fg/float.html, ext/mixed/js/dictionary-data-util.js, ext/mixed/js/display-generator.js
For general data formatting functionality which can be reused.
=> Dictionary data utility class

ext/bg/js/template-renderer.js
This change adds several general-purpose functions to the template system.
=> Additional template renderer helpers

ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/js/settings/backup.js
Refactors options.js into a class and organizes the upgrade process. The old profile upgrading process is now considered "legacy" and will be discontinued in favor of the global options upgrade process. This should have a smaller long-term maintenance cost, and improve the determinism of upgrades. In addition, the upgrade process is now able to be async.
=> Options util

docs/templates.md
=> Add documentation about template helper functions

ext/mixed/js/display.js
Simplifies a few of the try-catches in `Display`.
=> Display try catch refactor

ext/fg/js/frontend.js, ext/fg/js/source.js, ext/mixed/css/display.css
Resolves #535. This doesn't add any option to control enabled status, but that is probably not necessary until there is a clear demand for it (the less options, the better).
=> Button and image scanning

ext/fg/js/popup-proxy.js, ext/fg/js/popup.js, ext/mixed/js/display.js
Various fixes to extension unload detection and reaction.
=> Fix extension unload cases

ext/bg/js/anki.js
This can occur on the settings page
=> Fix overlapping version checks

ext/bg/js/anki.js
=> Fix a stray error printed due to not catching

dev/build.js, dev/yomichan-util.js, test/dictionary-validate.js, test/lint/global-declarations.js, test/test-database.js, test/test-dictionary.js, test/test-manifest.js, test/yomichan-test.js
* Two implementations of `getAllFiles` merged into one.
* `JSZip` export moved.
=> Create dev utility class for some shared functionality

ext/bg/js/search.js
Basically just renaming some variables to help disambiguate what they are (so there aren't both `_clipboardMonitorEnable` and `_clipboardMonitorEnabled`).
=> Search refactoring

ext/bg/js/json-schema.js, test/test-schema.js
* Adds support for `const`
* Adds support for `contains` for arrays
* Adds some tests
* Refactors some existing test data
=> More JSON schema improvements

test/test-profile-conditions.js
=> Fix profile conditions unit test using old JsonSchema

ext/fg/js/frontend.js, ext/fg/js/popup-factory.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js
Standardizes the public API shared between `Popup*` classes.
=> Popup API refactor

ext/fg/js/float.js, ext/fg/js/frontend.js
Simplifies requesting the root frame's popup ID and requesting a frame's document information.
=> Refactor some frontend cross-frame communication

ext/fg/js/popup-void.js
Will be used to fix https://github.com/FooSoft/yomichan/issues/713#issuecomment-674032328.
=> Add PopupVoid

ext/bg/js/search.js, ext/bg/js/settings/popup-preview-frame.js, ext/fg/js/content-script-main.js, ext/fg/js/float.js, ext/fg/js/frontend.js, ext/mixed/js/display.js
* Standardizes how `Frontend` class is created.
* Fixes a case where `Frontend._depth` could be reassigned incorrectly.
=> Frontend initialization refactor

test/data/html/test-document2.html
=> Add tests for data: and blob: iframe URLs

ext/bg/js/backend.js, ext/mixed/js/api.js
Not used yet, but will be in the future.
=> Add api.isTabSearchPopup

ext/fg/js/popup-factory.js, ext/fg/js/popup-proxy.js
Fixes some bugs and makes a few improvements/simplifications.
=> Popup proxy improvements

.eslintrc.json, ext/bg/js/template-renderer.js
=> Fix template renderer sandbox compatibility

ext/mixed/js/text-scanner.js
=> Fix touch input always being disabled

dev/data/manifest-variants.json, ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/settings.html, ext/fg/js/frontend.js, ext/fg/js/popup-factory.js, ext/fg/js/popup-window.js, ext/manifest.json, ext/mixed/js/display.js
=> Popup window

ext/bg/js/backend.js, ext/mixed/js/display.js
More correct and consistent error handling.
=> Fix error handling for screenshot captures

ext/bg/js/settings/profile-conditions-ui.js
* Fixes a few issues with some options not being assigned.
* Refactors a function to make it easier to extend.
=> Profile conditions fixes and improvements

README.md, ext/bg/data/anki-field-templates-upgrade-v4.handlebars, ext/bg/data/default-anki-field-templates.handlebars, ext/bg/js/anki-note-builder.js, ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/js/settings/anki-templates.js, ext/bg/js/settings/anki.js
This change adds a new marker `{clipboard-image}`, which adds an image from the clipboard.
Resolves #776.
=> Anki note clipboard marker

ext/bg/js/query-parser.js, ext/fg/js/frontend.js, ext/mixed/js/display.js, ext/mixed/js/text-scanner.js
Fixes a few issues and adds support for more input details in the `searched` event.
=> Text scanner fixes and refactoring

ext/bg/js/anki-note-builder.js, ext/bg/js/anki.js, ext/bg/js/backend.js, ext/bg/js/settings/anki-templates.js
Slight changes to the public API of `AnkiNoteBuilder` and `AnkiConnect`. These changes will facilitate some future updates to make the Anki classes more generic and able to be used directly on a `Display*` page.
=> Anki API refactor

ext/bg/js/anki-note-builder.js
Uses more correct/shared code for data URL conversion.
=> Use common function for data URL mediatype/data extraction

ext/bg/background.html, ext/bg/js/audio-uri-builder.js, ext/bg/js/simple-dom-parser.js
This change extracts the first commit of #561 (60b606efe5ce06e7fd4e040c24f79072b18120e8) into a separate PR so it can be used without adding the full replacement.
=> Create abstraction class for parsing DOM

ext/bg/js/backend.js, ext/mixed/js/api.js, ext/mixed/js/display.js
Adds `api.addAnkiNote` and `api.getAnkiNoteInfo`.
=> Anki note api functions

ext/bg/js/settings/keyboard-mouse-input-field.js, ext/bg/js/settings/scan-inputs-controller.js
Pen events are otherwise not detected properly.
=> Add support for pointer event input detection

ext/mixed/js/text-scanner.js
A bit of refactoring to better support pointer events.
=> Text scanner refactoring

ext/bg/css/settings.css, ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/js/settings/generic-setting-controller.js, ext/bg/js/settings/scan-inputs-controller.js, ext/bg/settings.html
Adds advanced scanning options, including:
* `scanOnPenHover`
* `scanOnPenPress`
* `scanOnPenRelease`
These options are not yet used.
=> More scanning options

ext/mixed/js/text-scanner.js
This was causing some state issues with certain events.
=> Update TextScanner.setEnabled to not reset state if unnecessary

ext/mixed/js/text-scanner.js
Should really have tested #817 first
=> Fix location of _enabled assignment

ext/bg/js/settings/keyboard-mouse-input-field.js
=> Add workaround for Firefox bug not detecting pen input type correctly

ext/bg/data/options-schema.json, ext/bg/js/options.js
Adds some missing defaults and always adds the touch input group during upgrade.
=> Settings upgrade and schema fixes

ext/bg/js/backend.js, ext/bg/js/settings/dictionary-controller.js, ext/bg/js/settings/dictionary-import-controller.js, ext/bg/js/settings/settings-controller.js, ext/mixed/js/api.js, ext/mixed/js/yomichan.js
Moves the `databaseChanged` event to the `yomichan` object.
=> Database change event

ext/fg/js/frontend.js
`_getIframeProxyPopup` can return `null`.
=> Add missing null check

docs/browser-bugs.md
Mentioned in #819, #820, #821, #824. Bug links:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1449660
* https://bugzilla.mozilla.org/show_bug.cgi?id=1487509
* https://bugzilla.mozilla.org/show_bug.cgi?id=1583480
* https://bugzilla.mozilla.org/show_bug.cgi?id=1583519
* https://bugzilla.mozilla.org/show_bug.cgi?id=1631377
=> Add info about the Firefox pen pointer event issues

build.bat, build.sh, dev/build.js
* Some restructuring for better organization.
* Adds more variant modification actions.
* Better value safety by cloning.
* Adds inheritance support.
* Adds some optional command line arguments:
* `--all` - builds all variants
* `--default` - updates the manifest to the default manifest
* `--manifest <target>` - updates the manifest to a specific manifest version
* `<target> <target> ...` - lists specific targets to build
=> Build system updates

ext/bg/js/settings/anki-templates-controller.js, ext/bg/js/settings/backup-controller.js, ext/bg/js/settings/dictionary-controller.js, ext/bg/js/settings/dictionary-import-controller.js, ext/bg/js/settings/modal.js, ext/bg/js/settings/profile-controller.js, ext/bg/settings.html, ext/mixed/js/core.js
This change moves all Bootstrap modal code into a single class, which should be easier to swap out later.
=> Modal refactor

ext/bg/js/settings/backup-controller.js
Deleting values causes the data to be invalid for the schema.
=> Fix settings sanitization resulting in invalid data for the schema

ext/bg/background.html, ext/bg/js/backend.js, ext/bg/js/clipboard-reader.js, ext/bg/js/dictionary-importer.js, ext/bg/js/media-utility.js
* Converts to a class.
* Uses in more places.
* Moves the image reading functionality that the database importer uses.
=> Media utility refactor

ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/settings.html, ext/fg/js/frontend.js, ext/mixed/js/display.js, ext/mixed/js/text-scanner.js, test/test-options-util.js
=> Add middle mouse prevention option

ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/js/settings/scan-inputs-controller.js, ext/bg/settings.html, ext/mixed/js/text-scanner.js, test/test-options-util.js
=> Add scan on touch move and prevent touch scroll options

ext/bg/js/backend.js, ext/bg/js/translator.js
This removes the `chrome` dependency from `Translator` by removing `_fetchJsonAsset`, which is redundant with `Backend._fetchAsset`.
=> Move deinflection reasons setup to backend

ext/bg/js/translator.js
Resolves #560:
> prioritize kana-only or "usually kana" results when the scanned text is kana
=> Add sourceTermExactMatchCount to prioritize exact expression matches

ext/bg/js/translator.js
=> Fix doc comments for translation options

ext/bg/js/translator.js
Fix a few more data structure bugs/changes which caused inconsistencies with previous behaviour.
=> Dictionary definition structure fixes

ext/bg/js/translator.js
This could happen in merged mode.
=> Don't add duplicate definitions

package-lock.json, package.json
This change updates the dev dependencies and adds `parse5` and `browserify`, which are used by #561.
=> Dev dependency update

ext/bg/js/settings/anki-controller.js, ext/bg/js/settings/audio-controller.js, ext/bg/js/settings/dictionary-controller.js, ext/bg/js/settings/profile-conditions-ui.js, ext/bg/js/settings/scan-inputs-controller.js, ext/bg/js/settings/settings-controller.js, ext/bg/settings.html
Use `HtmlTemplateCollection` on settings controllers.
=> Settings templates refactor

ext/bg/js/settings/generic-setting-controller.js, ext/mixed/js/dom-data-binder.js
Extracted 79819f29d63ef28f3d1d9a84f95684cac4033fba from #606.
=> Add additional transforms

ext/bg/js/settings/modal.js
Allows it to be used for settings v2.
=> Update the Modal class to support non-jQuery modals

ext/bg/js/settings/modal.js
* Adds `isVisible`.
* Improves `setVisible` by `.focus`ing the node.
* Fixes incorrect event data.
=> Modal updates 2

ext/bg/js/settings/modal.js
Defaults to true, but allows it to be disabled if necessary.
=> Make animation optional for Modal.setVisible

ext/bg/js/settings/audio-controller.js, ext/bg/settings.html
* Removes some unneeded handling.
* Improves compatibility with settings v2.
=> Update audio controller

ext/bg/css/settings.css, ext/bg/js/settings/storage-controller.js, ext/bg/settings.html
Refactors storage controller in preparation for settings v2.
=> Storage controller refactor

ext/bg/js/settings/anki-templates-controller.js, ext/bg/js/settings/backup-controller.js, ext/bg/js/settings/dictionary-controller.js, ext/bg/js/settings/dictionary-import-controller.js, ext/bg/js/settings/main.js, ext/bg/js/settings/modal-controller.js, ext/bg/js/settings/profile-controller.js, ext/bg/settings.html
Used to provide shared access to modals, for compatibility with settings v2.
=> Add modal controller class

ext/bg/js/settings/generic-setting-controller.js
Primarily adds `setVisibility` transform and a shorthand for setting both pre and post transforms using the `data-transform` attribute.
=> Generic settings improvements

ext/mixed/img/spinner.svg
=> Add spinner.svg

ext/bg/css/settings.css, ext/bg/js/settings/dictionary-controller.js, ext/bg/js/settings/dictionary-import-controller.js, ext/bg/settings.html
Updates ids and data structures for better settings v2 compatibility.
=> Dictionary controller refactor

ext/mixed/js/japanese.js
These functions no longer use `wanakana`, so they should be more efficient. This also removes the `wanakana` dependency from `distributeFurigana`, which uses `convertKatakanaToHiragana`. This fixes #915, since WanaKana is not included on the template renderer page. There should be no other issues, as that was the only `jp` function which used WanaKana functionality.
These conversions should also have less issues; the following is incorrect with WanaKana:
```js
wanakana.toHiragana('[ヷ][ヸ][ヹ][ヺ]');
// "［゗］［゘］［゙］［゚］"
```
=> Improve convertKatakanaToHiragana and convertHiraganaToKatakana

ext/bg/js/options.js
=> Fix template updates for multiple declarations

ext/bg/js/settings/dictionary-controller.js
Fixes an issue mentioned in #919: 
> My dictionaries were disabled and couldn't be reenabled by checking the boxes, so I had to remove and reinstall them.
=> Ensure settings exist for all installed dictionaries

ext/bg/js/settings/modal-jquery.js, ext/bg/js/settings/modal.js, ext/bg/settings.html
`modal-jquery.js` will eventually be removed.
=> Modal split

ext/bg/js/settings/popup-menu.js
=> Add PopupMenu class

ext/bg/js/settings/popup-menu.js
=> Popup menu updates

ext/bg/js/settings/audio-controller.js
=> Update audio controller for menus

ext/bg/js/settings/popup-elements.js
Used in settings v2 to report task status.
=> Status footer

ext/bg/js/settings/dictionary-controller.js, ext/bg/js/settings/main.js
Compatibility with settings v2.
=> Dictionary controller updates

ext/bg/js/settings/dictionary-import-controller.js
Compatibility with settings v2.
=> Change progress reporting to support settings v2

ext/bg/js/settings/dictionary-import-controller.js
=> Make dictionary spinner optional

ext/bg/js/options.js, ext/bg/js/settings/backup-controller.js, ext/bg/settings.html
* Updates selectors.
* Fixes an error during settings import (again, #917).
* Fixes import errors not being shown properly.
=> Backup controller refactor

ext/bg/css/popup-preview.css, ext/bg/js/settings/popup-preview-frame.js
Restores transparent background.
=> Popup preview fixes

ext/fg/js/text-source-element.js, ext/fg/js/text-source-range.js, ext/mixed/js/text-scanner.js
* Improve function names and public API.
* Make fields private.
=> Text source range refactor

ext/bg/js/settings/profile-controller.js, ext/bg/settings.html
* Updates IDs.
* Fixes profile copy not working correctly.
=> Profile controller refactor

ext/bg/js/settings/anki-controller.js
Support for features settings v2 uses.
=> Anki controller refactor

ext/bg/settings.html
=> Remove limits for popup horizontal/vertical offsets

ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/js/settings/backup-controller.js, test/test-options-util.js
* Fixes an issue where settings would be incorrectly reverted due to an incorrect version number.
* Removes legacy version number for profile options.
* Added some tests.
=> Options fixes

ext/bg/js/json-schema.js
=> Option schema default value info

ext/bg/js/settings/dictionary-controller.js, ext/bg/js/settings/dictionary-import-controller.js, ext/bg/settings.html
More improvements for settings v2.
=> Dictionary controllers update

ext/bg/css/settings.css, ext/bg/js/settings/anki-controller.js, ext/bg/js/settings/anki-templates-controller.js, ext/bg/settings.html
=> Anki templates refactor

ext/bg/js/settings/scan-inputs-controller.js
In order to keep the simple and advanced UIs in sync.
=> Trigger event on property change

ext/bg/css/pitch-accents-preview.css, ext/bg/js/settings/pitch-accents-preview-main.js, ext/bg/pitch-accents-preview.html, ext/mixed/js/display-generator.js
Isolated preview frame that can be used with settings v2, to avoid polluting the root frame's CSS rules.
=> Pitch accents preview

README.md, ext/bg/data/anki-field-templates-upgrade-v6.handlebars, ext/bg/data/default-anki-field-templates.handlebars, ext/bg/js/options.js, ext/bg/js/settings/anki-controller.js, test/test-options-util.js
=> Conjugation marker

ext/bg/js/settings/dictionary-controller.js, ext/bg/js/settings/settings-controller.js
=> Settings controller changes

ext/bg/css/popup-preview.css, ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/js/settings/popup-preview-controller.js, ext/bg/js/settings/popup-preview-frame-main.js
* Add an option to persist the popup preview visibility.
* Animation fixes.
* Better support for settings v2.
=> Popup preview update

ext/bg/js/settings/storage-controller.js, ext/bg/settings.html
=> Fix byte count labels

ext/bg/js/search-main.js, ext/bg/js/search.js, ext/bg/search.html, ext/fg/float.html, ext/fg/js/float.js, ext/mixed/css/display.css, ext/mixed/css/search.css, ext/mixed/js/display.js
* Input field is now multi-line. (Search query parser is not yet multi-line; for a future update.)
* Styles no longer dependant on Bootstrap.
* Simplifications.
=> Search and display style updates

ext/bg/js/backend.js, ext/bg/js/query-parser-generator.js, ext/bg/js/query-parser.js, ext/bg/query-parser-templates.html, ext/mixed/js/api.js, ext/mixed/js/display.js
Simplifications and improvements to speed up the query parser.
=> Query parser generator refactor

ext/bg/data/options-schema.json, ext/bg/js/anki-note-builder.js, ext/bg/js/options.js, ext/bg/settings.html, ext/mixed/js/display.js, test/test-options-util.js
=> Add duplicate check option

ext/bg/js/settings/popup-preview-frame.js, ext/fg/js/frontend.js
Add an internal override property rather than requiring the function to be overridden.
=> Frontend options override refactor

ext/bg/js/query-parser.js, ext/fg/js/frontend.js, ext/mixed/js/display.js, ext/mixed/js/text-scanner.js
Improve and simplify internal structure.
=> Options context updates

ext/mixed/css/display.css, ext/mixed/display-templates.html, ext/mixed/js/display-generator.js, ext/mixed/js/display.js
Debug info is now displayed as a clickable link, which logs debug information to the console.
=> Display updates

ext/bg/search.html, ext/mixed/css/display.css, ext/mixed/css/search.css
Mostly just organization/cleanup of styles, no real visual changes.
=> Display styles update

ext/mixed/js/scroll.js
Use private members and reorganize.
=> Scroll refactor

ext/bg/search.html, ext/fg/float.html, ext/mixed/css/display.css, ext/mixed/css/search.css, ext/mixed/js/display.js, ext/mixed/js/scroll.js
Moving towards some new design updates of the popup to support new features. Currently looks the same, but the the scrollbar is attached to a different element.
=> Display layout updates

ext/fg/js/float.js, ext/fg/js/frontend.js, ext/mixed/js/display.js
* Fixes initial selection not always working on the search page.
* Fixes CTRL+C not working on Firefox.
=> Display fixes

ext/bg/search.html, ext/fg/float.html, ext/mixed/css/display.css, ext/mixed/js/display.js
Progress indicator is now displayed as an indeterminant progress bar, which better matches some recent and upcoming style updates.
=> Update progress indicator styles

ext/bg/js/query-parser.js, ext/bg/search.html, ext/mixed/css/display.css, ext/mixed/css/search.css, ext/mixed/js/display.js
Updates padding and query parser layout on display pages.
=> Display and query parser layout

ext/bg/context.html, ext/bg/css/context.css, ext/bg/js/context-main.js
Updates to the context popup which improve consistency and add a dropdown to change the primary profile. Looks like the following:
Resolves #388; may resolve #944.
=> Context popup improvements

ext/mixed/js/display.js
=> Fix cloze not using the raw source

ext/bg/js/search.js, ext/mixed/css/display.css, ext/mixed/js/display-generator.js, ext/mixed/js/display.js
* Layout updates.
* Fixes scrolling issues.
* Simplifies audio playback based on new data format assumptions from the translator.
=> More display updates

ext/bg/js/settings/popup-preview-frame.js, ext/fg/js/frontend.js, ext/fg/js/popup-factory.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup-window.js, ext/fg/js/popup.js, ext/mixed/js/display.js
Simplifies use of Frontend and Popup. The primary change is that Frontend no longer uses monkey patching to customize behaviour for the preview page. Other changes are mostly cosmetic to improve readability and consistency.
=> Popup setup refactoring

ext/bg/js/translator.js
=> Fix incorrect frequency field being used

ext/mixed/css/display.css, ext/mixed/display-templates.html, ext/mixed/js/display-generator.js
Improves display of frequency tags in merged mode.
=> Frequency display improvements

ext/mixed/css/display.css, ext/mixed/display-templates.html, ext/mixed/js/display-generator.js, ext/mixed/js/html-template-collection.js
* Added an option to strip all whitespace from templates. This makes it easier to design readable templates without having whitespace pollute the layout.
* Updates to some existing templates.
=> Improve html templates

ext/mixed/css/display.css
Various color variable updates and a fix to expression colors.
=> Display style updates

ext/mixed/css/display.css, ext/mixed/display-templates.html, ext/mixed/js/display.js
* Use HTML properties instead of classes.
* Fade transitions for buttons.
=> Display button improvements

ext/bg/js/backend.js, ext/mixed/js/api.js, ext/mixed/js/display.js
=> Fix kanji note creation

ext/bg/js/audio-downloader.js, ext/bg/js/backend.js, ext/bg/js/clipboard-monitor.js, ext/bg/js/search-main.js, ext/bg/js/search.js, ext/bg/js/settings/pitch-accents-preview-main.js, ext/bg/js/template-renderer-frame-main.js, ext/bg/js/template-renderer.js, ext/bg/js/translator.js, ext/fg/js/float-main.js, ext/mixed/js/display-generator.js, ext/mixed/js/display.js, ext/mixed/js/japanese.js, test/test-japanese.js
`JapaneseUtil` is now manually created instead of creating during declaration. This should improve consistency with other util classes, and improve testability.
=> JapaneseUtil normalization

ext/mixed/css/display.css
More compact layout when lots of info is present in the database.
=> Update compact layout

ext/bg/data/options-schema.json, ext/bg/js/backend.js, ext/bg/js/context-main.js, ext/bg/js/options.js, ext/bg/settings.html, ext/bg/settings2.html, test/test-options-util.js
This change adds an option for and info about the new settings v2 page, set up in #606.
=> Settings v2 testing setup

ext/bg/lang/deinflect.json, test/test-deinflector.js
As described here: http://jgrammar.life.coocan.jp/grammar/jgr_vcon.htm
=> Add classic suru deinflections

ext/bg/css/settings2.css, ext/bg/legal.html
Removes another bootstrap CSS dependency.
=> Update style of legal.html to match settings v2

docs/permissions.md, ext/bg/js/permissions-main.js, ext/bg/permissions.html
=> Add permissions page and documentation

ext/bg/js/generic-page-main.js, ext/bg/legal.html
Enables animations and keyboard navigation without previous interaction.
=> Add initialization script for generic internal pages

ext/bg/context.html, ext/bg/info.html, ext/bg/js/anki.js, ext/bg/js/backend.js, ext/bg/js/context-main.js, ext/bg/js/info-main.js, ext/bg/js/settings/backup-controller.js, ext/bg/settings2.html, ext/mixed/js/api.js
=> Add info page

ext/mixed/js/display.js
=> Fix incorrect page type condition causing incorrect document title

dev/data/manifest-variants.json, ext/manifest.json
* `default-src 'self'` added.
* `media-src *` added.
* `connect-src *` added.
=> Update content-security-policy to be more explicit

ext/bg/search.html, ext/fg/float.html, ext/mixed/css/display.css, ext/mixed/display-templates.html, ext/mixed/js/display-generator.js, ext/mixed/js/display-notification.js, ext/mixed/js/display.js
=> Improve display tags

ext/bg/data/options-schema.json, ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/js/search.js, ext/bg/settings2.html, test/test-options-util.js
=> Maximum clipboard search length

ext/bg/css/settings2.css, ext/bg/js/settings/anki-controller.js, ext/bg/settings.html, ext/bg/settings2.html
Should make it easier to catch problems like #1094.
=> Display an indication when Anki field order/existence doesn't match

dev/build.js
Improvements to the supported modifications.
=> More build script improvements

dev/build.js, dev/util.js, package.json
Added to CI to ensure that the build files are configured properly.
=> Build dry run test

ext/mixed/css/display.css
Fixes an issue mentioned here: https://github.com/FooSoft/yomichan/issues/1079#issuecomment-748480063
=> Fixed terms being colored when not using merged mode

ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/settings2.html, ext/mixed/css/display.css, ext/mixed/display-templates.html, ext/mixed/js/display.js, test/test-options-util.js
* Added option to change selection indicator style:
* None
* Asterisk
* Triangle
* Vertical bar (left)
* Vertical bar (right)
* Small dot (left)
* Small dot (right)
Addresses feedback mentioned here: #1079.
Selection indicator original changed in: #1044.
=> Entry indicator update

ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/settings2.html, ext/fg/float.html, ext/mixed/css/display.css, ext/mixed/js/display.js, test/test-options-util.js
Adds support for:
* Changing the location of the action bar (left, right, top, bottom)
* Changing the visibility of the action bar (auto, always)
Was already planned to be added, but expedited based on feedback here: https://github.com/FooSoft/yomichan/issues/1079#issuecomment-748480063
=> Popup action bar options

ext/bg/js/anki-note-builder.js, ext/bg/js/settings/anki-controller.js
Makes it more clear that the first field should contain a `{marker}`.
Mentioned here: https://github.com/FooSoft/yomichan/issues/1128#issuecomment-74860386
=> Indicate if first Anki card field is invalid

ext/bg/css/settings2.css, ext/bg/js/settings/dictionary-controller.js, ext/bg/js/settings2/secondary-search-dictionary-controller.js, ext/bg/settings2.html, ext/bg/welcome.html
Style is more consistent across the welcome page and settings page. The popup is now a regular sized popup instead of full height, since the entries have been compressed.
=> Dictionary display updates

ext/bg/css/settings2.css, ext/bg/search.html, ext/bg/settings2.html, ext/bg/welcome.html, ext/mixed/css/search.css
Generalize how icons are used on various pages, making them easier to reuse in other places.
=> Settings v2 icon improvements

ext/bg/css/settings2.css, ext/bg/settings2.html
* Improved spacing around headings to improve scroll target location when clicking outline items.
* Adds icons to headings for faster visual searching when scrolling through the page.
=> Settings v2 headings improvements

ext/bg/css/settings2.css, ext/bg/js/settings/popup-elements.js, ext/bg/settings2.html, ext/mixed/img/collapse.svg, ext/mixed/img/expand.svg, resources/icons.svg
Most modals are now able to have their size change using a button on the top right.
=> Settings v2 modal size toggle

ext/bg/css/settings2.css, ext/bg/settings2.html, ext/bg/welcome.html
Helps to make the buttons more clear that they can be clicked and open a popup.
=> Improve settings item button styles

ext/bg/css/settings2.css, ext/bg/settings2.html, ext/mixed/img/window.svg, resources/icons.svg
Better organization for future window settings which will be added.
=> Add window settings

ext/bg/css/settings2.css, ext/bg/info.html, ext/bg/js/generic-page-main.js, ext/bg/js/info-main.js, ext/bg/js/permissions-main.js, ext/bg/js/search-main.js, ext/bg/js/search.js, ext/bg/js/settings2/settings-main.js, ext/bg/js/welcome-main.js, ext/bg/legal.html, ext/bg/permissions.html, ext/bg/search.html, ext/bg/settings2.html, ext/bg/welcome.html, ext/fg/float.html, ext/fg/js/float-main.js, ext/mixed/css/display.css, ext/mixed/js/display.js, ext/mixed/js/document-focus-controller.js
* Generalizes the document focus controller into a standalone class.
* Improves some styles to prevent the element from being visible on Firefox.
* Better documents what it's used for.
* Fixes #1164.
=> Improve document focus control

ext/bg/css/settings2.css, ext/bg/settings2.html
Based on feedback, this link is likely not necessary.
=> Remove "Top" link from settings v2 page

ext/bg/css/settings2.css, ext/bg/js/settings/popup-elements.js, ext/bg/settings2.html
Now uses `.hidden` property + a single class for animation, rather than three unique classes.
=> Improve element hiding

ext/mixed/css/display.css, ext/mixed/css/material.css, ext/mixed/css/search.css
* Fixes missing icon on dropdown buttons.
* Fixes the action buttons sometimes being under an element, rendering them unusable.
* Fixes the rounded border on the search page.
* Fixes some undesired styles on the display action buttons.
=> Fix various issues with some styles

ext/fg/float.html, ext/fg/js/float-main.js, ext/fg/js/frontend.js, ext/mixed/css/display.css, ext/mixed/css/search.css, ext/mixed/display-templates.html, ext/mixed/js/display-generator.js, ext/mixed/js/display-profile-selection.js, ext/mixed/js/display.js
This change adds a side panel to the display popup which allows profile selection.
Resolves #389, #388.
=> Display profile panel

ext/bg/css/settings2.css, ext/bg/js/settings/anki-controller.js, ext/bg/settings.html, ext/bg/settings2.html
Moved from the Anki card format popup to in the `Enable Anki integration` option.
=> Improve location of Anki status message

ext/bg/js/settings/generic-setting-controller.js, ext/bg/settings.html, ext/bg/settings2.html, ext/bg/welcome.html
Transforms are now stored entirely as JSON, which allows easier argument specification and support for multiple transforms per step. Functionality remains the same.
=> Improve settings transforms

ext/mixed/css/display.css
This caused tags to not be clickable.
=> Fix kanji selection area being on top of tags

ext/bg/js/anki-note-builder.js, ext/bg/js/settings/anki-templates-controller.js, ext/mixed/js/display.js
General refactoring to support some additional changes in the future.
=> Refactor anki note generation

ext/bg/js/settings/anki-controller.js
Fixes an issue mentioned in #1203.
=> Fix AnkiCardController using stale data

ext/mixed/css/display.css, ext/mixed/display-templates.html, ext/mixed/js/dictionary-data-util.js, ext/mixed/js/display-generator.js
=> Improve frequency display

ext/mixed/css/display.css, ext/mixed/display-templates.html
=> Use ruby tag for frequency disambiguation

ext/bg/css/settings2.css, ext/bg/settings2.html
Makes it easier to assign the scroll anchor target for page refreshing.
=> Add links to settings v2 headings

ext/fg/js/frontend.js, ext/mixed/js/display.js, ext/mixed/js/document-util.js, ext/mixed/js/text-scanner.js, test/data/html/test-document1.html, test/test-document-util.js
=> Refactor sentence parsing

ext/bg/css/settings2.css, ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/js/settings2/sentence-termination-characters-controller.js, ext/bg/js/settings2/settings-main.js, ext/bg/settings2.html, ext/fg/js/frontend.js, ext/mixed/js/display.js, ext/mixed/js/document-util.js, ext/mixed/js/text-scanner.js, test/test-document-util.js, test/test-options-util.js
=> Customizable sentence parsing

ext/mixed/css/display.css, ext/mixed/js/display-profile-selection.js
=> Fix profile panel not being able to be closed due to hidden sidebar

ext/fg/float.html, ext/mixed/css/display.css, ext/mixed/js/display.js
More consistent with changes from #1220, and other display controls in general.
=> Update how navigation sidebar visibility is controlled

ext/bg/data/options-schema.json, ext/bg/js/options.js, test/test-options-util.js
Mentioned in https://github.com/FooSoft/yomichan/issues/1219#issuecomment-757547773.
=> Change popupActionBarLocation to top

ext/bg/js/anki.js, ext/bg/js/backend.js, ext/mixed/js/api.js, ext/mixed/js/display.js
Various simplifications and clarifications.
=> Refactor display anki functions

ext/bg/js/query-parser.js, ext/fg/js/frontend.js, ext/mixed/js/display.js, ext/mixed/js/text-scanner.js
Some changes to allow some additional data to be provided to `TextScanner`'s `'searched'` event.
=> Refactor text scanner options context generation

ext/bg/js/search.js, ext/fg/js/frontend.js, ext/mixed/js/display.js
This should also fix some issues related to using the document title in Anki notes when using a native window as a popup.
=> Refactor note document title

ext/bg/js/settings/keyboard-mouse-input-field.js, ext/bg/js/settings/profile-conditions-ui.js, ext/bg/js/settings/scan-inputs-controller.js
KeyboardMouseInputField now supports having a key in addition to modifiers. Modifiers are now exposed as an array instead of a string.
=> Update KeyboardMouseInputField 

ext/bg/js/search.js
Simplify how focus change is done
=> Search key handling refactor

ext/bg/js/settings/keyboard-mouse-input-field.js, ext/mixed/js/display.js, ext/mixed/js/document-util.js
=> Use code instead of key

ext/bg/js/settings/scan-inputs-simple-controller.js, ext/bg/settings2.html, ext/bg/welcome.html
In order to improve understandability, based on some comments in #120.
=> Clarify some settings descriptions

ext/bg/js/settings/profile-conditions-ui.js, ext/bg/js/settings/profile-controller.js, ext/bg/settings2.html
* Fixes the conditions counter not being updated.
* Fixes stale data sometimes being used for profile conditions.
* Adds a _Remove group_ menu option for conditions groups with more then one condition.
=> Fix profile conditions issues

ext/bg/data/options-schema.json, ext/bg/js/anki.js, ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/settings2.html, ext/mixed/js/api.js, ext/mixed/js/display.js, test/test-options-util.js
=> Support suspending new anki cards

ext/bg/settings2.html, ext/mixed/js/display.js
=> Add hotkeys to change dictionary

ext/bg/css/settings2.css, ext/bg/data/options-schema.json, ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/js/settings/generic-setting-controller.js, ext/bg/js/settings2/popup-window-controller.js, ext/bg/js/settings2/settings-main.js, ext/bg/settings2.html, test/test-options-util.js
Adds some options for the popup window. Resolves some of the comments in #680.
=> Popup window options

dev/data/manifest-variants.json, ext/bg/js/backend.js, ext/bg/js/context-main.js, ext/manifest.json
Updates shortcuts and adds a new shortcut to open the popup window.
Resolves #680.
=> Update extension shortcuts

README.md, ext/bg/data/anki-field-templates-upgrade-v8.handlebars, ext/bg/data/default-anki-field-templates.handlebars, ext/bg/js/options.js, ext/bg/js/settings/anki-controller.js, ext/bg/js/template-renderer.js, ext/bg/settings2.html, test/test-options-util.js
Resolves #348, and can be used to serve as an example for users to add custom markers for other stats.
=> Stroke count marker

ext/bg/js/options.js, ext/bg/settings.html, ext/bg/settings2.html, test/test-options-util.js
Starting the migration process of using the v2 settings as the default.
=> Update default settings page

ext/bg/js/query-parser.js, ext/fg/js/frontend.js, ext/mixed/js/display.js, ext/mixed/js/text-scanner.js
Various simplifications and improvements to `TextScanner`.
=> Text scanner improvements

ext/bg/js/search-main.js, ext/bg/js/search.js, ext/fg/js/float-main.js, ext/mixed/js/display.js, ext/mixed/js/hotkey-handler.js
Hotkeys can now be forwarded across frames, e.g. from the display popup to the owner page.
=> Hotkey forwarding support

ext/mixed/js/display.js, ext/mixed/js/hotkey-handler.js
Saves a redundant invocation of `_updateHotkeyRegistrations`.
=> Optimize hotkey registration

dev/data/manifest-variants.json, ext/bg/data/options-schema.json, ext/bg/js/settings/popup-preview-frame-main.js, ext/bg/js/settings/popup-preview-frame.js, ext/bg/popup-preview.html, ext/bg/settings2.html, ext/fg/js/content-script-main.js, ext/fg/js/frontend.js, ext/manifest.json, ext/mixed/js/display.js
=> Add support for frontend hotkeys; add scanSelectedText action

ext/bg/search.html, ext/fg/float.html, ext/mixed/display-templates.html, ext/mixed/js/display-audio.js, ext/mixed/js/display.js
Refactors the audio controls of the `Display` class into a separate component. This should make it easier to maintain in the future.
=> Display audio

ext/bg/js/settings/keyboard-mouse-input-field.js, ext/bg/js/settings/scan-inputs-simple-controller.js, ext/bg/settings2.html, ext/mixed/js/document-util.js, ext/mixed/js/hotkey-util.js, test/test-hotkey-util.js
Moves hotkey utility functions into a separate, reusable class.
=> Hotkey util

dev/data/manifest-variants.json, ext/bg/context.html, ext/bg/js/backend.js, ext/bg/js/context-main.js, ext/manifest.json
`openHelpPage` => `openInfoPage`
=> Command refactor

ext/bg/context.html, ext/bg/js/context-main.js, ext/bg/search.html, ext/fg/float.html, ext/mixed/display-templates.html, ext/mixed/js/display-generator.js, ext/mixed/js/display.js, ext/mixed/js/hotkey-help-controller.js, ext/mixed/js/html-template-collection.js
The hotkey information found in HTML `title` attributes is now dynamic and correctly represents the current set of hotkeys.
=> Hotkey help controller

ext/bg/js/backend.js
Some cleanup to `Backend` related to options.
=> Backend options update

ext/bg/js/audio-downloader.js, ext/bg/js/backend.js, ext/mixed/js/api.js, ext/mixed/js/audio-system.js, ext/mixed/js/display-audio.js
Some initial work to prepare for supporting #1249/#544.
=> Audio system refactoring

ext/bg/js/settings/anki-controller.js, ext/bg/js/settings/anki-templates-controller.js, ext/bg/js/settings/audio-controller.js, ext/bg/js/settings/dictionary-controller.js, ext/bg/js/settings/popup-menu.js, ext/bg/js/settings/profile-conditions-ui.js, ext/bg/js/settings/profile-controller.js, ext/bg/js/settings/scan-inputs-controller.js, ext/bg/js/settings2/keyboard-shortcuts-controller.js, ext/bg/js/settings2/sentence-termination-characters-controller.js, ext/bg/js/settings2/settings-display-controller.js, ext/bg/js/settings2/translation-text-replacements-controller.js
Some general refactoring to prepare for more broad use (outside of the settings page).
=> Menu refactor

ext/bg/js/search.js
=> Fix numpad enter functioning differently than enter on the search page

ext/bg/search.html, ext/fg/float.html, ext/mixed/js/display-audio.js
Improves the cache to support changes to the audio sources.
=> Update display audio cache

ext/mixed/css/display.css, ext/mixed/css/material.css, ext/mixed/display-templates.html, ext/mixed/img/plus-thick.svg, ext/mixed/js/display-audio.js, resources/icons.svg
* Shows a small `+` when more than one audio is available.
* Shows a small `x` when no audio is available.
=> Audio play button status badge

ext/bg/js/settings/anki-controller.js, ext/bg/js/settings/dictionary-controller.js, ext/bg/js/settings/profile-conditions-ui.js, ext/bg/js/settings/profile-controller.js, ext/bg/js/settings/scan-inputs-controller.js, ext/bg/js/settings2/translation-text-replacements-controller.js, ext/bg/settings2.html, ext/bg/welcome.html, ext/mixed/css/material.css, ext/mixed/js/popup-menu.js
Fixes an issue where out-of-order `popup-menu-item`s will result in the menu being positioned incorrectly.
=> Update popup menu structure

ext/bg/search.html, ext/fg/float.html, ext/mixed/css/display.css, ext/mixed/display-templates.html, ext/mixed/js/display-audio.js, ext/mixed/js/display-generator.js, ext/mixed/js/display.js, ext/mixed/js/popup-menu.js
Adds a popup menu to the audio button, which can be activated by shift clicking or right clicking.
Resolves #1249, same framework can be used for #544.
=> Audio button menu

ext/bg/js/search.js
Search box now shrinks when reading text from the clipboard.
=> Fix search box resizing

ext/bg/data/options-schema.json, ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/js/search.js, ext/bg/js/settings/clipboard-popups-controller.js, ext/bg/settings.html, ext/bg/settings2.html, test/test-options-util.js
Clipboard options are now grouped together in a single object instead of being in the `general` object.
=> Update clipboard options organization

README.md, ext/bg/css/settings2.css, ext/bg/settings2.html, ext/bg/welcome.html, ext/mixed/css/material.css
Some wording and minor style improvements.
=> Settings and welcome page improvements

ext/mixed/css/display.css, ext/mixed/display-templates.html
=> Display notification style updates

ext/bg/js/anki-note-builder.js, ext/bg/js/anki.js, ext/bg/js/backend.js, ext/bg/js/clipboard-reader.js, ext/bg/js/settings/anki-templates-controller.js, ext/mixed/css/display.css, ext/mixed/display-templates.html, ext/mixed/js/display-generator.js, ext/mixed/js/display.js
An error notification is now shown if any part of the note creation process fails.
* Missing audio does not count as an error.
* Missing clipboard image does not count as an error.
=> Add note errors

ext/bg/js/clipboard-reader.js
`navigator.clipboard.readText()` throws `undefined` if the permissions are not granted on Firefox.
=> Update error handling for navigator.clipboard

ext/bg/css/settings2.css, ext/bg/js/settings/anki-controller.js, ext/bg/js/settings/backup-controller.js, ext/bg/js/settings/clipboard-popups-controller.js, ext/bg/js/settings/settings-controller.js, ext/bg/settings2.html, ext/mixed/css/material.css
Settings which require certain permissions will now display an invalid indicator when those permissions aren't granted.
=> Settings permissions info display

ext/bg/js/settings/main.js, ext/bg/js/settings/permissions-toggle-controller.js, ext/bg/js/settings2/settings-main.js, ext/bg/settings.html, ext/bg/settings2.html
Generalize `ClipboardPopupsController` to `PermissionsToggleController`.
=> Permissions toggle controller

ext/fg/js/frame-ancestry-handler.js, ext/mixed/js/comm.js
=> Frame ancestry handler refactor

ext/bg/lang/deinflect.json, test/test-deinflector.js
This list is probably not comprehensive, but it covers a lot of common cases.
https://japanese.stackexchange.com/questions/29099/changing-of-diphthongs-at-the-end-of-words-to-%E3%81%88-in-exclamations
=> え deinflection

ext/bg/pitch-accents-preview.html, ext/bg/popup-preview.html, ext/bg/search.html, ext/bg/settings2.html, ext/mixed/css/display.css, ext/mixed/js/display-generator.js
This should apparently prevent font issues on Chrome, such as #688.
https://www.reddit.com/r/LearnJapanese/comments/iup3n/psa_google_chrome_kanji_rendering/
https://en.wikipedia.org/wiki/Han_unification#Examples_of_language_dependent_characters
=> Enforce language

ext/bg/context.html, ext/bg/css/context.css, ext/bg/css/settings2.css, ext/bg/js/context-main.js, ext/bg/settings2.html
Badges/indicators now show up on the settings button link on the browser action popup, and a second badge shows up on the settings page _Configure installed and enabled dictionaries…_ button to clarify what the user is supposed to do.
=> Improve dictionaries not enabled badges

ext/bg/css/popup-preview.css
Not sure why that style was there.
=> Fix overflow scrollbar appearing sometimes

ext/bg/js/settings/anki-controller.js
Will auto-fill the first field, fields with the same name as the previous model, and fields with names that match a marker.
Resolves #495.
=> Auto-fill Anki card fields when possible

ext/bg/js/backend.js, ext/bg/js/mecab.js
Improvements and better error handling for the Mecab component handler.
=> Mecab refactor

ext/bg/js/backend.js, ext/bg/js/mecab.js, ext/bg/js/settings2/mecab-controller.js, ext/bg/js/settings2/settings-main.js, ext/bg/settings2.html, ext/mixed/js/api.js
Resolves #1356.
Resolves siikamiika/yomichan-mecab-installer#2.
=> Mecab test

ext/bg/js/backend.js, ext/bg/js/search.js, ext/fg/js/popup-window.js, ext/mixed/js/display.js
Updates the `{screenshot}` marker to capture the screenshot for the correct content origin.
Also fixes an argument order issue in `DisplaySearch`.
=> Fix window popup screenshot

ext/bg/js/audio-downloader.js, ext/bg/js/backend.js, ext/bg/js/media-utility.js
The `.mp3` file extension is now dynamic, based on content type.
=> Add support for multiple types of audio

ext/bg/lang/deinflect.json, test/test-deinflector.js
Resolves https://github.com/FooSoft/yomichan/issues/910#issuecomment-777631764.
=> Add additional vz deinflection rule

ext/bg/js/search-display-controller.js, ext/mixed/js/display.js
Since this is only used for the search page, move the code to `SearchDisplayController`.
=> Move search mode

.eslintrc.json, dev/build-libs.js, dev/lint/global-declarations.js, dev/lint/html-scripts.js
Part of some general organizational improvements.
=> Update lint and tests

.eslintrc.json, ext/js/app/content-script-main.js, ext/js/app/frontend.js, ext/js/app/popup-proxy.js, ext/js/background/backend.js, ext/js/comm/cross-frame-api.js, ext/js/core.js, ext/js/display/display.js, ext/js/display/popup-main.js, ext/js/display/query-parser.js, ext/js/display/search-main.js, ext/js/general/task-accumulator.js, ext/js/language/dictionary-database.js, ext/js/language/text-scanner.js, ext/js/pages/info-main.js, ext/js/pages/permissions-main.js, ext/js/pages/welcome-main.js, ext/js/settings/anki-controller.js, ext/js/settings/backup-controller.js, ext/js/settings/dictionary-controller.js, ext/js/settings/dictionary-import-controller.js, ext/js/settings/main.js, ext/js/settings/pitch-accents-preview-main.js, ext/js/settings/popup-preview-frame-main.js, ext/js/settings/settings-main.js, ext/js/yomichan.js
Logging is now performed as part of a core class, instead of being part of the `yomichan` object. The `Yomichan` class is now only responsible for forwarding the logs to the background page.
=> Log refactoring

ext/action-popup.html, ext/background.html, ext/pitch-accents-preview.html, ext/popup-preview.html
Improved overall consistency of HTML formatting.
=> Update html files and scripts

ext/css/display.css, ext/css/material.css, ext/display-templates.html, ext/js/display/display-audio.js, ext/js/display/display-generator.js
Menu generation is much more simple, which should make future extensions and modifications easier.
=> Display audio menu refactor

ext/css/display.css, ext/css/material.css, ext/display-templates.html, ext/js/display/display-audio.js, ext/js/display/display.js
The primary audio for Anki cards is now selectable in the audio menu.
=> Audio popup menu primary card audio selection

ext/css/display.css, ext/js/display/display-generator.js
=> Fix search tags in split and grouped display modes

ext/css/display.css, ext/display-templates.html
=> Remove section headings

ext/js/language/translator.js, test/data/dictionaries/valid-dictionary2/tag_bank_1.json, test/data/dictionaries/valid-dictionary2/term_bank_1.json, test/data/test-translator-data.json
Fixes an issue mentioned in https://github.com/FooSoft/yomichan/issues/1340#issuecomment-781203189
=> Fix translation regex replacements

ext/css/display.css, ext/css/material.css
Improve some styles definitions.
=> Refactor styles

ext/css/context.css, ext/css/display.css, ext/css/material.css, ext/css/search.css, ext/css/settings.css
Improved focus styles for keyboard-only focus.
https://css-tricks.com/keyboard-only-focus-styles/
=> Focus visible styles

ext/css/display.css, ext/display-templates.html, ext/js/display/display-generator.js, ext/js/display/display.js
Updates tag structure and style to be more flexible.
=> Improve tag styles

ext/js/background/backend.js, ext/js/data/anki-util.js, ext/js/display/display.js
Disables the ability to add notes if the data is invalid (e.g. empty fields).
Resolves #1415.
=> Improve note addability

ext/css/display.css
Adds string variables for disambiguation styles.
=> Disambiguation style strings

ext/js/app/frontend.js
Missing broadcast request after refactoring.
=> Fix wait for frontend not working properly

ext/css/settings.css, ext/js/pages/settings/anki-controller.js, ext/settings.html
Use tabs instead of a select.
Should fix an issue pointed out in #1415.
=> Improve Anki card type selection

ext/js/language/japanese-util.js, test/test-japanese.js
Related: https://github.com/toasted-nutbread/yomichan-bccwj-frequency-dictionary/issues/1
=> Improve kana segmentation

ext/css/display.css
Initial improvements to expression styles. This change makes variable names a bit more consistent.
=> Refactor expression vars

ext/css/display.css, ext/display-templates.html, ext/js/display/display-audio.js, ext/js/display/display-generator.js, ext/pitch-accents-preview.html
More improvements to styles in display.css. This primarily involves removing `term-` prefix from a number of classes and names.
=> Refactor display styles

ext/css/display.css, ext/display-templates.html, ext/js/display/display-generator.js, ext/js/display/display.js
Should make it a bit easier to find some certain styles. A few minor improvements included as well.
=> Organize display styles

ext/css/display.css
More flexible color variables.
=> Improve expression variables

ext/data/deinflect.json, test/test-deinflector.js
=> Add ge deinflect rule

ext/js/dom/document-util.js, ext/js/dom/text-source-element.js
=> Add support for scanning the selected value of <select> elements

ext/js/display/display-generator.js, ext/js/language/japanese-util.js
Resolves #1459, except for `kifuku`, which requires some additional changes.
=> Add categorization of pitch accents

ext/js/display/display-generator.js
=> Use a Set instead of an array

ext/js/display/display.js, ext/js/input/hotkey-handler.js
=> Remove the now-unused hotkey forwarding functionality

ext/js/background/backend.js, ext/js/display/query-parser.js, ext/popup.html, ext/search.html
Fixes some bugs, improves some performance.
=> Improve text parser

ext/js/display/search-display-controller.js
=> Fix enter key causing duplicate text when typing using an IME

ext/js/background/backend.js
Since this permission doesn't prompt in versions >= 77, automatically request it.
=> Request persistent storage on Firefox

ext/js/display/query-parser.js
Fixes an issue mentioned in https://github.com/FooSoft/yomichan/issues/1472#issuecomment-789511011.
=> Fix text being overwritten when generating the query parser content

ext/js/language/translator.js
Resolves an issue mentioned in https://github.com/FooSoft/yomichan/issues/1472#issuecomment-789511011 and https://github.com/FooSoft/yomichan/issues/1472#issuecomment-791095036.
=> Fix missing meta when reading is empty

ext/display-templates.html
=> Add workaround for a frequency disambiguation layout issue on Firefox

ext/js/language/translator.js
Resolves some issues mentioned in https://github.com/FooSoft/yomichan/issues/1472#issuecomment-789511011 and https://github.com/FooSoft/yomichan/issues/1472#issuecomment-791094772.
=> Use dictionary priority later in the definition sorting algorithm

ext/js/display/display-generator.js
Fixes an issue mentioned here: https://github.com/FooSoft/yomichan/issues/1472#issuecomment-791878660.
Change originally made in #1344.
=> Fix multiline copying

ext/css/display.css
For easier user customization. https://github.com/FooSoft/yomichan/issues/1472#issuecomment-789499901
=> Add CSS variable to control tag height

.eslintrc.json, ext/background.html, ext/js/general/regex-util.js, ext/js/language/translator.js, ext/sw.js, test/test-translator.js
Removes some unused functions and moves some functions into a new `RegexUtil` class.
=> Clean up translator

ext/js/language/text-scanner.js
=> Fix text selection during scanning

ext/js/dom/document-util.js
=> Fix previousStyles being recreated for every transparent element

ext/css/display.css
Fixes an issue mentioned in https://github.com/FooSoft/yomichan/issues/1472#issuecomment-794987642.
Tag height should have been a minimum instead of a fixed value.
=> Fix tag height

ext/js/data/database.js, ext/js/language/dictionary-database.js
Adds helper functions to bulk-find the first matching value for a query.
=> Database API updates

ext/css/display.css, ext/css/search.css, ext/css/settings.css
For easier adjustment of the search page's width. #1518
=> Add css width var

ext/js/data/database.js, ext/js/language/dictionary-database.js, ext/js/language/translator.js, ext/js/media/media-loader.js, test/test-database.js
Various changes to improve the flexibility of the database APIs and improved code reuse.
=> Dictionary database improvements

ext/js/background/backend.js
=> Fix search tab not focusing correctly

ext/js/language/japanese-util.js, test/test-japanese.js
Fixes an issue pointed out in https://github.com/FooSoft/yomichan/issues/1472#issuecomment-797206738.
=> Fix furigana distribution when source/expression kana differs

dev/translator-vm.js, test/test-translator.js
To allow for easier reuse for more tests.
=> TranslatorVM

ext/js/display/display-audio.js, ext/js/dom/popup-menu.js
=> Enable audio menu shift click

ext/css/display.css, ext/js/display/display-generator.js, ext/js/display/display.js
Wasn't working due to the new data format, and there was a separator missing between entries (old issue).
=> Fix tag disambiguation

docs/interfaces/dictionary-entry.ts, ext/js/language/translator.js, test/data/translator-test-results.json
Sorting was using the wrong source text.
=> Fix incorrect sorting

ext/css/material.css, ext/css/settings.css, ext/js/dom/popup-menu.js, ext/js/pages/settings/keyboard-shortcuts-controller.js, ext/settings.html
Improves the layout and adds room for an "argument" field, which will be used in the future.
=> Update hotkey settings design

ext/data/deinflect.json, test/test-deinflector.js
=> -chimau inflection

ext/js/display/display.js, ext/js/pages/settings/keyboard-shortcuts-controller.js, ext/settings.html
=> Add playAudioFromSource hotkey

ext/css/material.css, ext/css/settings.css, ext/js/display/display.js, ext/js/display/option-toggle-hotkey-handler.js, ext/js/pages/settings/keyboard-shortcuts-controller.js, ext/popup.html, ext/search.html, ext/settings.html
Resolves #1416 and https://github.com/FooSoft/yomichan/issues/1504#issuecomment-793242221.
=> Toggle option hotkey

ext/css/display.css, ext/css/material.css, ext/css/settings.css, ext/data/schemas/options-schema.json, ext/display-templates.html, ext/images/double-down-chevron.svg, ext/js/data/options-util.js, ext/js/display/display.js, ext/js/display/element-overflow-controller.js, ext/js/pages/settings/backup-controller.js, ext/js/pages/settings/collapsible-dictionary-controller.js, ext/js/pages/settings/dictionary-controller.js, ext/js/pages/settings/dictionary-import-controller.js, ext/js/pages/settings/settings-main.js, ext/popup.html, ext/search.html, ext/settings.html, resources/icons.svg, test/test-options-util.js
=> Definition collapsing when overflowing

ext/js/data/anki-note-builder.js, ext/js/display/display.js, ext/js/templates/template-renderer-frame-api.js, ext/js/templates/template-renderer-proxy.js, ext/js/templates/template-renderer.js
Since the Anki data format is now significantly different, it should also be logged when logging debug info about an entry.
=> Log Anki data

ext/css/display.css
Fixes an issue mentioned in https://github.com/FooSoft/yomichan/issues/1580#issuecomment-812870553.
=> Fix selectability of kanji text

ext/data/schemas/options-schema.json, ext/js/background/backend.js, ext/js/data/options-util.js, ext/js/display/element-overflow-controller.js, ext/js/pages/action-popup-main.js, ext/js/pages/settings/backup-controller.js, ext/js/pages/settings/collapsible-dictionary-controller.js, ext/js/pages/settings/dictionary-controller.js, ext/js/pages/settings/dictionary-import-controller.js, ext/js/pages/settings/secondary-search-dictionary-controller.js, test/test-options-util.js
Dictionary options are now an array instead of an object. This should allow for improved customization of ordering.
=> Update dictionary settings structure

dev/translator-vm.js, ext/js/app/frontend.js, ext/js/background/backend.js, ext/js/comm/api.js, ext/js/comm/mecab.js, ext/js/data/anki-note-builder.js, ext/js/data/anki-note-data-creator.js, ext/js/data/options-util.js, ext/js/display/display-audio.js, ext/js/display/display-generator.js, ext/js/display/display.js, ext/js/display/search-display-controller.js, ext/js/language/dictionary-data-util.js, ext/js/language/dictionary-database.js, ext/js/language/japanese-util.js, ext/js/language/text-scanner.js, ext/js/language/translator.js, ext/js/media/audio-downloader.js, ext/js/pages/settings/anki-templates-controller.js, ext/settings.html, test/test-anki-note-builder.js, test/test-database.js, test/test-japanese.js, test/test-options-util.js
=> Update dictionary entry terminology

ext/css/permissions.css, ext/js/pages/permissions-main.js, ext/js/pages/settings/permissions-origin-controller.js, ext/permissions.html
This should help address an issue in the future where Chrome won't grant `<all_urls>` permissions by default.
May help address issues such as #1593 in the future.
=> Add PermissionsOriginController

ext/js/app/popup.js
=> Use consistent window size properties to improve popup positioning

ext/js/background/backend.js, ext/js/data/anki-note-data-creator.js, ext/js/display/display-generator.js, ext/js/language/japanese-util.js, ext/js/templates/template-renderer.js, test/test-japanese.js
=> Replace furigana with reading

docs/interfaces/dictionary-entry.ts, ext/js/data/anki-note-data-creator.js, ext/js/language/translator.js, test/data/translator-test-results-note-data1.json, test/data/translator-test-results.json
=> Improve dictionary sequence info

ext/js/language/translator.js
Addresses some feedback mentioned here: https://github.com/FooSoft/yomichan/pull/1616#issuecomment-822069723
=> Translator refactoring for consistency

ext/js/language/translator.js
=> Fix incorrect return type causing an error

ext/js/display/display-generator.js
Helps for #1620, but the dictionary data format would need updates.
=> Improve kifuku detection to not include suru nouns

ext/data/schemas/options-schema.json
Resolves #462.
(Apparently "a while" is "one year")
=> Enable showIframePopupsInRootFrame by default for new installs

ext/js/app/frontend.js, ext/js/language/text-scanner.js
=> Add support for restoring the selection after using scanSelectedText

ext/js/app/frontend.js, ext/js/pages/settings/keyboard-shortcuts-controller.js, ext/settings.html
Same as `scanSelectedText`, but it doesn't require a character to be selected.
=> Add scanTextAtCaret option

ext/js/background/backend.js, ext/js/language/translator.js, test/data/translator-test-inputs.json
=> Translator alphanumeric improvement

ext/js/data/anki-note-data-creator.js, ext/js/display/display-generator.js, ext/js/language/dictionary-data-util.js, ext/js/templates/template-renderer.js
Needed for solving #1459 in a reasonable manner.
=> Add pitch categories template helper

ext/css/settings.css, ext/js/pages/settings/dictionary-controller.js, ext/settings.html, ext/welcome.html
The layout is more compact now, which should help organization of many dictionaries. There is also now an "All" toggle.
Related: #1539, https://github.com/FooSoft/yomichan/issues/1000#issuecomment-818130046
=> Improve dictionary options

ext/js/pages/settings/dictionary-controller.js, ext/settings.html, ext/welcome.html
Resolves https://github.com/FooSoft/yomichan/issues/1000#issuecomment-818130046, helps for #1539.
=> Add support for reordering dictionary options

ext/js/display/display-generator.js
=> Remove the mouseover tags that are shown in merge mode

ext/css/display.css, ext/display-templates.html, ext/js/display/display-generator.js
=> Update search tags to always be displayed in a consistent manner

ext/data/schemas/options-schema.json
https://github.com/FooSoft/yomichan/issues/479#issuecomment-757541536
16 is a nice middle between 10 (current) and 20.
=> Increase the default scanning length to 16

ext/js/pages/settings/dictionary-controller.js
Fixes an issue mentioned in https://github.com/FooSoft/yomichan/issues/1539#issuecomment-830759101.
=> Fix the "Prefix wildcard searches supported" toggle having incorrect state

ext/css/settings.css, ext/js/pages/settings/dictionary-controller.js, ext/settings.html
https://github.com/FooSoft/yomichan/issues/1539#issuecomment-830759101.
=> Add "Move to" menu option for moving dictionary options to a specific location

ext/js/pages/settings/dictionary-import-controller.js
Same idea as #1658, but at least this didn't break anything.
=> Remove more legacy settings page selectors

ext/css/settings.css, ext/info.html, ext/legal.html, ext/permissions.html, ext/welcome.html
This fixes some layout issues on devices with small screens, i.e. mobile devices.
=> Improve internal page overflow

ext/js/pages/settings/dictionary-controller.js
Fixes an issue mentioned in https://github.com/FooSoft/yomichan/issues/1539#issuecomment-835742397 (3).
=> Improve the behaviour of the "Move to..." action

ext/css/search.css, ext/js/display/display.js, ext/js/display/search-action-popup-controller.js, ext/js/display/search-display-controller.js, ext/js/display/search-main.js, ext/js/pages/action-popup-main.js, ext/search.html
Page can be opened by shift-clicking the search button in the popup.
Resolves #1613.
=> Popup action search

ext/action-popup.html
=> Update the search button tooltip to describe Shift+click functionality

ext/css/settings.css, ext/data/schemas/options-schema.json, ext/js/data/options-util.js, ext/js/dom/document-util.js, ext/js/language/text-scanner.js, ext/settings.html, test/data/html/test-document1.html, test/test-document-util.js, test/test-options-util.js
Adds new modes for controlling termination character newlines.
Resolves https://github.com/FooSoft/yomichan/issues/1680#issuecomment-841755468.
=> Sentence termination character mode

ext/js/language/dictionary-importer.js
If an image was referenced twice, the second and subsequent data structures would not be properly formatted.
=> Fix repeated dictionary image importing

README.md, dev/translator-vm.js, ext/data/templates/anki-field-templates-upgrade-v12.handlebars, ext/data/templates/default-anki-field-templates.handlebars, ext/js/data/anki-note-data-creator.js, ext/js/data/options-util.js, ext/js/display/display.js, ext/js/pages/settings/anki-controller.js, ext/js/pages/settings/anki-templates-controller.js, ext/settings.html, test/data/anki-note-builder-test-results.json, test/data/translator-test-results-note-data1.json, test/test-anki-note-builder.js, test/test-options-util.js
Adds a new marker `{search-query}`.
Actually resolves #1680.
=> Expose search query to anki template renderer

ext/css/display.css, ext/data/schemas/dictionary-term-bank-v3-schema.json, ext/display-templates.html, ext/js/display/display-generator.js, ext/js/language/dictionary-importer.js
Improved options for collapsing images, improved code structure for easier reuse.
=> Dictionary image display refactoring

ext/js/app/frontend.js, ext/js/language/text-scanner.js
=> Fix popup preview disappearing after changing a setting

ext/data/schemas/options-schema.json, ext/js/background/backend.js, ext/js/data/options-util.js, ext/js/display/display-audio.js, ext/js/display/display.js, ext/js/media/audio-downloader.js, ext/settings.html, test/test-options-util.js
There is now a separate source type: _Custom URL (JSON)_.
=> Refactor json audio source

ext/js/pages/settings/audio-controller.js
Some refactoring to make it easier to support future changes in a manner more consistent with other settings controllers.
=> Refactor AudioController

ext/js/background/backend.js, ext/js/comm/api.js, ext/js/display/display-audio.js, ext/js/display/display.js, ext/js/media/audio-downloader.js, ext/js/media/audio-system.js
This change refactors how audio sources are internally handled in `DisplayAudio` and the related classes it uses. The intent is to make the implementation more flexible to support more types of audio sources.
=> Refactor display audio options

ext/css/display.css, ext/js/display/display-audio.js
Fixes some issues with changing and indicating the primary audio source.
=> Primary audio fixes

ext/data/schemas/dictionary-index-schema.json, ext/data/schemas/dictionary-term-bank-v1-schema.json, ext/data/schemas/dictionary-term-bank-v3-schema.json, ext/data/schemas/dictionary-term-meta-bank-v3-schema.json
Replace term/expression with just term.
=> Update schema descriptions to be less redundant

dev/build.js, dev/data/manifest-variants.json, dev/manifest-util.js, dev/util.js, ext/manifest.json, test/test-manifest.js
Version is now auto-populated from the most recent reachable annotated git tag.
https://github.com/FooSoft/yomichan/issues/1642#issuecomment-836046369
=> Update build script

dev/manifest-util.js
=> Improve error message when running manifest commands

.github/workflows/ci.yml, dev/data/manifest-variants.json, ext/manifest.json
Version is now auto-populated from the most recent reachable annotated git tag.
Follows #1722.
https://github.com/FooSoft/yomichan/issues/1642#issuecomment-836046369
=> Auto update manifest version

ext/js/background/request-builder.js
=> Fix _getMatchURL missing search and not sanitizing wildcards

docs/interfaces/dictionary-entry.ts, ext/js/data/anki-note-data-creator.js, ext/js/language/translator.js, test/data/translator-test-results.json
Expose multiple IDs for grouped/merged definitions.
=> Translator id updates

ext/js/app/popup.js
Resolves https://github.com/FooSoft/yomichan/issues/305#issuecomment-866195189
=> Fix handling of document.body as <frameset>

ext/js/display/search-display-controller.js
=> Fix search input focus not working properly

ext/css/display.css, ext/css/material.css, ext/data/schemas/dictionary-term-bank-v3-schema.json, ext/js/display/display-generator.js, test/data/dictionaries/valid-dictionary1/term_bank_1.json
* Adds `<br>` tag.
* Adds `<span>`, `<div>` tags, which supports `style` properties:
* `fontStyle: normal | italic`
* `fontWeight: normal | bold`
* `fontSize: xx-small | x-small | small | medium | large | x-large | xx-large | xxx-large`
* `textDecorationLine: none | underline | overline | line-through`
* `verticalAlign: baseline | sub | super | text-top | text-bottom | middle | top | bottom`
* Adds `<table>`, `<thead>`, `<tbody>`, `<tfoot>`, `<tr>`, `<th>`, `<td>` tags.
* `<th>` and `<td>` support `colSpan=<integer>` and `rowSpan=<integer>` properties.
Resolves #1745.
=> Structured content updates

docs/interfaces/dictionary-entry.ts, ext/js/data/anki-note-data-creator.js, ext/js/language/translator.js, test/data/translator-test-results.json
Updates the data stored in a `dictionaryEntry.definitions[]` entry in order to provide more flexibility for sorting.
=> Translator data format updates

ext/js/display/display.js
Generated Anki notes (without injected media) are now logged to the console as well.
=> Improve what info is logged when debugging a definition

ext/js/display/display-generator.js, ext/js/display/structured-content-generator.js, ext/pitch-accents-preview.html, ext/popup.html, ext/search.html
Should make it easier to add functionality and make changes, as well as make it more modular.
=> Move structured-content generation code into a separate file

ext/js/display/display.js
Note generation errors were overlooked.
=> Fix missing error logging when logging debug info

ext/js/display/display-generator.js, ext/js/display/structured-content-generator.js
Generalize and remove dependency on the templates object.
=> Structured content generation updates

ext/js/data/anki-note-builder.js, ext/js/templates/template-renderer.js
Remove unused function and generalization for future updates.
=> Template rendering updates

dev/database-vm.js, dev/translator-vm.js, test/test-anki-note-builder.js
A few fixes and support for generalization.
=> Test updates

ext/js/templates/template-renderer.js
Some more fields for custom functionality.
=> Template renderer internal data update

docs/templates.md
Adds documentation for helper functions which were missing.
=> Update template documentation

ext/js/templates/template-patcher.js, test/test-options-util.js
Some simplifications for future updates.
=> Template patcher updates

ext/css/structured-content.css, ext/js/display/structured-content-generator.js
Removes some external dependencies from structured-content.css.
=> Update structured content CSS styles

dev/data/structured-content-overrides.css, dev/generate-structured-content-style.js, ext/css/structured-content.css, ext/data/structured-content-style.json, package-lock.json, package.json, test/test-structured-content-style.js
This change adds a JSON file representing the style rules used for structured content. This will be used to output formatted Anki content. Required for #1741.
=> Structured content style json

ext/js/dom/css-style-applier.js
This class is used to apply CSS styles to elements using a consistent method that is the same across different browsers.
=> Add CssStyleApplier class

ext/js/display/structured-content-generator.js
=> Fix incorrect aspect ratio of structured-content images

dev/data/structured-content-overrides.css, ext/css/structured-content.css, ext/data/structured-content-style.json
=> Update dictionary image link color

ext/js/templates/template-renderer.js
The requirements will need to be unique-ified on a per-note basis anyways, so having it in two places is redundant.
=> Remove uniqueness check for requirements

ext/js/display/display-anki.js, ext/js/display/display.js, ext/popup.html, ext/search.html
This change separates Anki-related functionality out of the `Display` class into a new `DisplayAnki` class. The implementation and functionality should be mostly the same.
=> DisplayAnki

ext/js/display/display-anki.js, ext/js/display/display.js
Implementation is now more generalized, supports showing kanji and term definitions simultaneously.
=> Refactor DisplayAnki.setupEntriesComplete params and implementation

ext/js/data/anki-note-builder.js, ext/js/display/display-anki.js
This change exposes the template renderer requirement information to the internal dictionary entry details array.
=> DisplayAnki note requirements

ext/js/display/display-anki.js
Note generation will use these requirements to determine which media should be injected.
=> Pass requirements to note generation

ext/js/data/options-util.js, test/test-options-util.js
Some changes to the updates system to make it easier to test the upgrade process from and to specific versions.
=> OptionsUtil and tests updates

ext/js/background/backend.js, ext/js/comm/api.js, ext/js/data/anki-note-builder.js
Dictionary media files are now injected into Anki cards using the system set up in #1802.
Resolves #1741.
=> Add support for injecting dictionary media into Anki cards

README.md, ext/data/templates/anki-field-templates-upgrade-v13.handlebars, ext/data/templates/default-anki-field-templates.handlebars, ext/js/data/anki-note-builder.js, ext/js/data/options-util.js, ext/js/pages/settings/anki-controller.js, ext/js/templates/template-renderer-media-provider.js, ext/settings.html, test/data/anki-note-builder-test-results.json, test/test-anki-note-builder.js, test/test-options-util.js
Adds `{selection-text}`. Resolves #1787.
=> Anki card selected text

ext/data/schemas/options-schema.json, ext/js/background/backend.js, ext/js/comm/api.js, ext/js/display/display.js, ext/js/display/query-parser.js, ext/js/language/japanese-util.js, ext/settings.html
Some refactoring, and the value `dictionary-reading` has been added to `readingMode`.
=> Text parse updates

ext/js/pages/settings/collapsible-dictionary-controller.js, ext/js/pages/settings/dictionary-controller.js, ext/js/pages/settings/secondary-search-dictionary-controller.js
Mentioned in https://github.com/FooSoft/yomichan/issues/1782#issuecomment-873539789.
=> Fix an issue with reordering dictionary settings

ext/css/material.css, ext/js/pages/settings/anki-controller.js, ext/settings.html
Menu items are now thinner since there are so many of them.
=> Update Anki field marker menu

ext/js/templates/template-renderer-proxy.js
Affects Firefox only.
Introduced by #1772.
Resolves #1821.
=> Fix case where "ready" message is received before frame "load" event

ext/js/background/backend.js
Should display a more meaningful error when logged.
Related: #1825.
=> Throw an error when _getProfile doesn't have a matching profile

ext/data/schemas/options-schema.json, ext/js/data/anki-note-builder.js, ext/js/data/options-util.js, ext/js/display/display-anki.js, ext/settings.html, test/test-anki-note-builder.js, test/test-options-util.js
Adds a new option _Check for duplicates across all models_.
Depends on https://github.com/FooSoft/anki-connect/pull/269.
Resolves #1519.
=> Duplicate scope check all models

ext/data/schemas/options-schema.json
=> Fix invalid default value in options schema

test/data/anki-note-builder-test-results.json, test/data/dictionaries/valid-dictionary1/term_bank_1.json, test/data/translator-test-inputs.json, test/data/translator-test-results-note-data1.json, test/data/translator-test-results.json, test/test-database.js
Includes more test cases for pronunciations.
=> Update valid-dictionary1 data

ext/data/schemas/dictionary-term-bank-v1-schema.json
Also could you describe the purpose of the `iru` rule identifier further?
=> List `vz` rule identifier in term bank schema

ext/css/display-pronunciation.css, ext/css/display.css, ext/display-templates.html, ext/js/display/display-generator.js, ext/js/display/display.js
"pronunciation" is the new, more generalized terminology used internally.
=> Rename CSS class names "pitch-accent" to "pronunciation"

ext/js/data/sandbox/anki-note-data-creator.js, ext/js/display/display-generator.js, ext/js/language/sandbox/dictionary-data-util.js, ext/js/language/sandbox/japanese-util.js, test/test-japanese-util.js
Renamed to `pronunciation` for more consistent terminology.
=> Rename pitchAccent in source code

ext/js/language/dictionary-importer.js
And other cleanup after loading an image.
=> Call URL.revokeObjectURL for created URLs

dev/database-vm.js, dev/translator-vm.js, ext/js/language/dictionary-importer.js, ext/js/pages/settings/dictionary-import-controller.js, test/test-database.js
Some minor improvements to the dictionary importer, to make it slightly more efficient.
=> Improve dictionary importer

dev/database-vm.js, dev/translator-vm.js, dev/vm.js, ext/js/language/dictionary-importer-media-loader.js, ext/js/language/dictionary-importer.js, ext/js/pages/settings/dictionary-import-controller.js, ext/settings.html, ext/welcome.html, test/test-database.js
Abstracts the media loading functionality of the `DictionaryImporter` class. This improves how testing is performed and will be used to support threading the `DictionaryImporter`.
=> DictionaryImporterMediaLoader

.eslintrc.json, ext/background.html, ext/info.html, ext/js/data/sandbox/string-util.js, ext/js/media/audio-downloader.js, ext/js/pages/settings/backup-controller.js, ext/settings.html, ext/sw.js
Move some functions to a utility class
=> StringUtil

ext/js/language/dictionary-importer.js
* Improved error message generation.
* Simplified URL for fetching JSON assets. No longer required to generate an extension URL, since it should already be relative to the extension root.
=> DictionaryImporter improvements

ext/js/language/dictionary-importer.js
=> Dictionary importer refactor

ext/js/language/dictionary-importer.js, ext/js/pages/settings/dictionary-import-controller.js
Shows progress for all steps of the import process, including data validation.
#1853
=> Dictionary import progress improvements

ext/js/app/popup.js, ext/js/display/display-audio.js, ext/js/display/display.js
Should fix the issues in #1872, but I was not able to reproduce the exact issue.
=> Improve audio auto play cancellation

ext/js/data/database.js, ext/js/language/dictionary-database.js, ext/js/language/dictionary-importer.js
Fixes an issue mentioned in https://github.com/FooSoft/yomichan/issues/1869#issuecomment-892243316
Related: #1876
=> Fix data not being persisted after terminating Worker thread

ext/js/background/backend.js
Adds support for script injection when using Manifest V3. Note that the behaviour is slightly different, maybe because MV3 is not ready yet:
* [`chrome.tabs.executeScript`](https://developer.chrome.com/docs/extensions/reference/tabs/#method-executeScript) supports `runAt = 'document_start'`, [`chrome.scripting.executeScript`](https://developer.chrome.com/docs/extensions/reference/scripting/#method-executeScript) does not.
* MV2's injection of a `<script>` element uses the extension's CSP; MV3's uses the webpage's CSP. Therefore, `google-docs.js` currently does not work in MV3.
Follow-up of #1875.
=> Add support for manifest V3 script injection

ext/js/display/display-audio.js, ext/js/display/display.js
=> Fix auto-play not working on the search page

ext/css/display.css, ext/css/material.css, ext/css/settings.css, ext/settings.html
Various style updates to the settings page, mostly to support improved generalization, as well as a few minor fixes and improvements.
=> Input styles updates

ext/info.html, ext/settings.html
=> Replace ... with &hellip;

ext/data/schemas/dictionary-term-bank-v3-schema.json, ext/js/display/sandbox/structured-content-generator.js, test/data/dictionaries/valid-dictionary1/term_bank_1.json
=> Add support for structured content margins

ext/js/language/dictionary-importer.js, test/test-database.js
Fixes an issue mentioned in https://github.com/FooSoft/yomichan/issues/1918#issuecomment-908880554:
> It also incidentally continued to 102% in Step 6 before finishing...
=> Fix dictionary import total progress

ext/js/language/translator.js
=> Fix incorrect index being used for headword removal

ext/js/language/dictionary-importer.js, test/test-database.js
Also includes an import timestamp.
=> Dictionary import count details

dev/dictionary-validate.js
Export the `testDictionaryFiles` function so it can be used from other scripts.
=> Update dictionary validation script

ext/css/material.css, ext/js/pages/settings/anki-controller.js
The menu will now show the suggested default value in bold.
=> Anki field templates suggestions

ext/js/language/translator.js
Repeated terms would be looked up multiple times in the database rather than only once.
=> Fix redundant secondary term lookups

ext/css/display.css, ext/css/material.css, ext/display-templates.html
Display action icons are now more consistent with other icons.
=> Display button updates

ext/data/schemas/dictionary-index-schema.json, ext/js/language/dictionary-importer.js
Dictionary authors can specify whether the frequency values correspond to an occurrence count or an indexed rank.
=> Enable frequency dictionaries to specify the frequency mode

ext/js/templates/sandbox/anki-template-renderer.js
=> Fix regexMatch and regexReplace handlebars helper functions

ext/js/display/display.js, ext/js/display/search-display-controller.js
Not only was this feature largely unused for normal use cases, it was also bugged for a long time. So it should be removed.
=> Remove display query post process

ext/js/app/frontend.js, ext/js/display/display-anki.js, ext/js/display/display.js, ext/js/display/query-parser.js, ext/js/dom/text-source-element.js, ext/js/dom/text-source-range.js, ext/js/language/text-scanner.js
Selecting text in the query parser changes the URL, and the URL will now include an offset of the sub-query into the full query. This offset is used to improve sentence context in rare cases (see #1919) and could be used for text selection in the future.
=> Search query offset value

ext/js/app/frontend.js, ext/js/app/popup-factory.js, ext/js/app/popup-proxy.js, ext/js/app/popup-window.js, ext/js/app/popup.js, ext/js/comm/frame-offset-forwarder.js, ext/js/dom/document-util.js
Avoids using `DOMRect.x` or `DOMRect.y` since their minimum Chrome version is higher than Yomichan's.
https://developer.mozilla.org/en-US/docs/Web/API/DOMRectReadOnly/x
=> DOMRect update

ext/js/background/backend.js
=> Disable background clipboard monitor, mecab, and anki if disabled

ext/js/app/frontend.js, ext/js/app/popup-factory.js, ext/js/app/popup-proxy.js, ext/js/app/popup-window.js, ext/js/app/popup.js, ext/js/background/backend.js, ext/js/display/display-audio.js, ext/js/display/display-resizer.js, ext/js/display/display.js, ext/js/display/search-display-controller.js, ext/js/input/hotkey-handler.js, ext/js/pages/settings/popup-preview-controller.js, ext/js/pages/settings/popup-preview-frame.js, ext/js/yomichan.js
Action handler names are now prefixed to avoid ambiguous names or collisions.
=> Action handler name disambiguation

ext/settings.html
Updates descriptions to be more clear.
Resolves #2011.
=> Update sentence parsing settings

.eslintrc.json, ext/background.html, ext/js/background/backend.js, ext/js/background/script-manager.js, ext/sw.js
This change moves some of the script injection of the `Backend` class into its own `ScriptManager` class. This class may be used to contain more functionality in the future.
=> ScriptManager

ext/js/dom/dom-text-scanner.js
Otherwise I will forget to get back to this.
=> Fix typo in comments

ext/js/display/display-audio.js
=> Fix source name not being used

docs/interfaces/dictionary-entry.ts
Fixes some issues with comments and updates some fields to use enums.
=> TS docs updates

ext/data/schemas/options-schema.json, ext/js/data/options-util.js, test/test-options-util.js
This change adds vertical punctuation to the default list of `terminationCharacters`.
Fixes #2045.
=> Update sentence termination characters

ext/js/comm/anki.js, ext/js/pages/settings/anki-controller.js, ext/settings.html
May be helpful for issues such as #2072.
=> Add support for logging Anki errors on the settings page

ext/js/accessibility/google-docs.js
Temporarily fixes #2093, #2094. See links in https://github.com/FooSoft/yomichan/issues/2093#issuecomment-1079726428 for details.
=> Workaround for Google Docs canvas rendering updates

.github/workflows/ci.yml, package-lock.json, package.json
Update node to the latest LTS (16.14.2) and update dependencies.
=> Update node version and dependencies

ext/css/settings.css
Minor updates to make the CSS less hacky.
=> Settings page mobile layout updates

ext/js/app/popup.js
This should result in a bit less memory usage in the long run.
=> Update Popup to not store the full options object

ext/js/dom/sandbox/css-style-applier.js, ext/js/dom/simple-dom-parser.js
=> Regex optimizations

test/data/anki-note-builder-test-results.json, test/data/dictionaries/valid-dictionary1/term_bank_1.json, test/data/translator-test-inputs.json, test/data/translator-test-results-note-data1.json, test/data/translator-test-results.json, test/test-anki-note-builder.js, test/test-database.js
Adds a new test for some simple structured content.
=> Update structured content tests

ext/data/schemas/dictionary-kanji-bank-v1-schema.json, ext/data/schemas/dictionary-kanji-bank-v3-schema.json, ext/data/schemas/dictionary-kanji-meta-bank-v3-schema.json, ext/data/schemas/dictionary-tag-bank-v3-schema.json, ext/data/schemas/dictionary-term-bank-v1-schema.json, ext/data/schemas/dictionary-term-bank-v3-schema.json, ext/data/schemas/dictionary-term-meta-bank-v3-schema.json
Use `"items"` rather than `"additionalItems"`, and also add `"additionalItems": false` where appropriate.
=> Update some JSON schemas to be more compliant to the spec

ext/js/display/display-anki.js
This is consistent with the noteIds originally returned from AnkiConnect.
=> Update _getNodeNoteIds to return integer IDs

ext/js/app/popup.js
=> Fix this._horizontalTextPositionBelow being assigned incorrectly

ext/js/dom/sandbox/css-style-applier.js
This change primarily updates some of the internal data structures to be more explicit. Also adds some JSDoc comments.
=> CssStyleApplier updates

docs/interfaces/translator-types.ts, ext/js/background/backend.js, ext/js/language/translator.js
This change adds some Typescript interface docs and JSDocs about the Translator class's options.
=> Add mode documentation about the types used by Translator

ext/js/display/display-anki.js, ext/js/display/display-notification.js, ext/js/display/display.js, ext/js/display/option-toggle-hotkey-handler.js
Refactoring to make showing notifications more consistent.
=> Display notification updates

ext/js/comm/anki.js
For use with https://github.com/FooSoft/anki-connect/pull/324
=> Add apiReflect and apiExists to AnkiConnect

dev/data/manifest-variants.json, ext/js/background/backend.js, ext/js/background/request-builder.js, ext/js/media/audio-downloader.js
This change will show a notification if a permissions error occurs when trying to download audio while creating Anki cards.
Resolves #2157.
=> Audio request errors

ext/js/background/backend.js
=> Update referenceUrl to include fragment

ext/js/language/translator.js
=> Sort using frequency dictionary before using dictionary priority

ext/css/material.css, ext/data/schemas/options-schema.json, ext/js/background/backend.js, ext/js/comm/anki-connect.js, ext/js/data/options-util.js, ext/js/dom/dom-data-binder.js, ext/js/pages/settings/anki-controller.js, ext/settings.html, test/test-options-util.js
=> Add support for Anki API key

.eslintrc.json, ext/data/schemas/options-schema.json, ext/issues.html, ext/js/background/backend.js, ext/js/background/request-builder.js, ext/js/data/anki-note-builder.js, ext/js/data/options-util.js, ext/js/display/display-anki.js, ext/js/media/audio-downloader.js, ext/settings.html, test/test-options-util.js
This change adds a setting which limits the amount of time that an audio download can be idle for.
Resolves https://github.com/FooSoft/yomichan/issues/2182#issuecomment-1162960085.
=> Audio download timeout

ext/js/display/display.js, ext/js/display/search-display-controller.js, ext/js/pages/info-main.js, ext/js/pages/permissions-main.js, ext/js/pages/settings/profile-controller.js, ext/js/pages/settings/settings-controller.js, ext/js/pages/settings/settings-main.js, ext/js/pages/welcome-main.js
This change fixes some issues where the selected profile index would be incorrect, either due to importing invalid settings, or due to deleting the current profile.
Resolves #2199.
=> Profile index fixes

ext/js/dom/dom-text-scanner.js
This change adds support for scanning UTF-16 surrogate pairs.
Resolves part of [#2211](https://github.com/FooSoft/yomichan/issues/2211#issuecomment-1221138098).
=> Update DOMTextScanner to support UTF-16 surrogate pairs

ext/js/dom/text-source-element.js, ext/js/dom/text-source-range.js, ext/js/language/text-scanner.js
Use a consistent signature between `TextSourceElement` and `TextSourceRange`.
=> Fix setEndOffset

ext/js/data/sandbox/string-util.js, ext/js/dom/text-source-element.js
Follow-up of #2213.
Resolves another part of [#2211](https://github.com/FooSoft/yomichan/issues/2211#issuecomment-1221138098).
=> TextSourceElement surrogate pair support

ext/js/dom/document-focus-controller.js, ext/js/dom/document-util.js, ext/js/dom/text-source-element.js, ext/js/dom/text-source-range.js
This change adds documentation for `TextSourceRange`, `TextSourceElement`, `DocumentUtil`, and `DocumentFocusController`.
=> More API documentation

ext/js/dom/document-util.js, ext/js/dom/dom-data-binder.js, ext/js/dom/text-source-range.js, ext/js/pages/settings/generic-setting-controller.js, ext/js/pages/settings/keyboard-shortcuts-controller.js, ext/js/pages/settings/nested-popups-controller.js
* Removes some unused functions
* Reorganizes some utility functions
* Fixes and documentation fixes
=> Cleanup and refactoring

.eslintrc.json, ext/display-templates.html, package-lock.json, package.json
Updates the lint rules and extension versions, also includes the `eslint-plugin-jsonc` plugin to enforce JSON styling.
=> Lint updates

ext/background.html, ext/css/background.css, ext/js/background/backend.js, ext/js/comm/clipboard-monitor.js, ext/js/comm/clipboard-reader.js
Some refactoring to the clipboard reader. This works towards #2240.
=> Clipboard updates

ext/js/background/backend.js, ext/js/background/request-builder.js, ext/js/comm/anki-connect.js
=> Documentation updates

dev/schema-validate.js
Fix an issue where ajv validation errors wouldn't be used properly.
=> Ajv error fix

ext/data/schemas/dictionary-kanji-meta-bank-v3-schema.json, ext/data/schemas/dictionary-term-bank-v3-schema.json, ext/data/schemas/dictionary-term-meta-bank-v3-schema.json
=> Use "const" instead of "enum" with one value
