README.md, ext/bg/js/options.js, ext/bg/js/templates.js, ext/bg/js/util.js, tmpl/fields.html
Closes #64 
Pretty much what you said, just needed to change `ext/bg/js/util.js` too.
I'm not entirely convinced about having `{glossary}` with tags as the main one for terms, when `{glossary}` for kanji doesn't have tags. It's a thing about internal consistency vs backwards compatibility. I think I value backwards compatibility more than internal consistency, so this is fine. But it's not like much would be lost with that behavior change, either. Up to you.
=> Add glossary-brief anki field, like glossary but without tags

ext/bg/js/database.js
I think I was running into some race or performance issue when attempting to import jmnedict.zip into Yomichan on Firefox 56 - having reliably run into the following failure more than 20 times (including on clean profiles):
(where it fails is sometimes the same but usually different)
From what I could see in the Browser Console, `UnknownErr`s were being thrown from the IndexedDB library in Firefox.
With this change, this no longer occurs for me.
I tried doing this on the dev branch with all the async changes but while the database imports worked, I'm not seeing any dropdown when I actually go to hover above words (they get highlighted but no dictionary entries show up).
=> Import terms with transactional adds instead of bulkAdd

ext/bg/js/database.js
Re-implementation of #66 for async, since I guess behaviour was reverted. Also applied it to kanji import.
(the underlying, I suppose I/O with IndexedDB, issue reappeared for me when I was importing terms after my database disappeared during 1.3.5 upgrade)
I tried to use `await this.db.terms.add()` here but that was leading to an `InvalidStateError`. I'm not sure whether the 'await` is necessary there or not.
For reference: http://dexie.org/docs/Dexie/Dexie.transaction()#async-and-await
=> Import terms/kanji with transactional adds instead of bulkAdd on async

ext/fg/js/document.js
Checked that it does not un-fix #80
Squelches alerts (but does not fix underlying issue) for #89
=> Place `nodeType` checks inside `caretRangeFromPoint` function

ext/bg/js/api.js, ext/bg/js/audio.js, ext/bg/js/database.js, ext/bg/js/dictionary.js, ext/bg/js/handlebars.js, ext/bg/js/options.js, ext/bg/js/settings.js, ext/bg/js/templates.js, ext/bg/js/translator.js, ext/bg/js/util.js, ext/bg/settings.html, ext/mixed/css/display.css, ext/mixed/js/display.js, tmpl/dictionary.html, tmpl/terms.html
I can't find anything major to change or implement, so I'm opening this pull request. Some minor things below:
- I'm not sure if `compactTags` and `compactGlossaries` should be on by default for [new users](https://github.com/siikamiika/yomichan/blob/feature-merge-similar-results/ext/bg/js/options.js#L196). They will be off for [existing users](https://github.com/siikamiika/yomichan/blob/feature-merge-similar-results/ext/bg/js/options.js#L270).
- I tested on a Windows Firefox that `utilStringHashCode` gives the same hash for the first revision of the field templates (it could have messed up with `\r\n` after `formRead`). Can we trust this or should the string be normalized before hashing?
=> Feature: result grouping by main dictionary sequence (along with some other changes)

ext/bg/js/templates.js, tmpl/terms.html
The CSS way would have required editing markup for other modes, too (`.expression` `font-size` to `0px` and `.expression *` `font-size` to `24px` or something similar but that would make https://github.com/FooSoft/yomichan/blob/dcef7ce3774a3dcc8e7bee0bc17398251523451e/tmpl/terms.html#L72 invisible)
Another stupid hack:
```html
<e1>...</e1
><e2>...</e2>
```
=> merged mode: remove whitespace between expressions

ext/bg/js/audio.js
* HTML format for ```'jpod101-alternate'``` seems to have changed at some point, so the HTML node with the URL had to be updated.
* jisho.org now uses https by default.
* Audio URLs are now normalized. This fixes an issue where audio from jisho.org could not be played back on file:/// URLs since the audio URLs look like: ```"//d1vjc5dkcd3yh2.cloudfront.net/audio/21df5faaebe19fd4355d40fbe2fd97aa.mp3"```
=> Fix alternate audio URLs

ext/bg/js/options.js, ext/bg/js/settings.js, ext/bg/settings.html, ext/fg/css/client.css, ext/fg/js/document.js, ext/fg/js/frontend.js, ext/fg/js/popup.js, ext/manifest.json
* Text can now be touched to bring up the dictionary popup.
* Feature can be enabled or disabled through settings (enabled by default).
* When touch input is disabled, touch events will not be hooked.
* An option to allow the dictionary popup be fixed to the bottom or top of the page has also been added. This mode may be less intrusive when physically touching a screen and moving along the text.
* Touch inputs can be tested without a touchscreen in Chrome by using the touchscreen device simulation mode.
=> Add support for touch input

ext/bg/background.html, ext/bg/context.html, ext/bg/guide.html, ext/bg/js/backend.js, ext/bg/js/database.js, ext/bg/js/settings.js, ext/bg/js/util.js, ext/bg/legal.html, ext/bg/search.html, ext/bg/settings.html, ext/fg/float.html, ext/fg/js/frontend.js, ext/fg/js/util.js
Mobile Firefox supports addons, and I had added touch support in a previous pull request, so it seemed logical to add this.
Changes:
* HTML pages now look correct for devices with different display scaling values.
* Added a search link to the settings page since it cannot be accessed otherwise on mobile Firefox.
* Fixed some extension commands which are not supported on mobile Firefox.
* Extension badges and custom commands.
* Added storage usage information to the settings page.
* Interestingly, Firefox for Android's databases seem to take up about 3x the storage space as desktop Firefox, so adding a dictionary takes 3x as much space.
* Slightly changed how database dictionary insertion is handled in order to not leave the database in a completely unusable state.
* If adding a dictionary …
=> Add support for mobile Firefox

ext/fg/js/popup.js
The popup element's parent must be changed to the fullscreen element in order to be visible.
Fixes #163
=> Allow popup window to be visible in fullscreen mode

ext/fg/js/document.js
If range.getClientRects() has more than 1 result, it is possible that nothing will be returned when hovering over a valid target.
Example page exhibiting the bug:
```html
<!DOCTYPE html>
<html>
<body>
<div style="font-size: 20px; width: 300px; font-family: Arial; margin: 0 auto;">
私も台所から便所紙を投げつけて応戦した。
</div>
</body>
</html>
```
The word wrap should appear as such:
```
私も台所から便所紙を投げつけて
応戦した。 
```
Hovering over 応戦 can result in no results being detected because ```range.getClientRects()``` is returning 2 results rather than the usual 1.
The change which causes this issue seems to have been introduced sometime after v1.5.1, since that version does not have this issue (guessing [this](https://github.com/FooSoft/yomichan/commit/0cc5566886f34f781072c1b0ae9ce85a12295a7e#diff-8dcb9a0ea4375b3bf7ed56 …
=> Fix docRangeFromPoint sometimes not returning results

ext/fg/js/popup.js
When "Automatically hide results" is checked and empty part of the website is scanned, the popup hides. However, iframe#yomichan-float still has focus and prevents the site from being used normally with keyboard.
This PR fixes the issue by blurring the popup iframe each time its `hide` method is called.
=> return focus to site after hiding popup

ext/fg/js/document.js
On many sites, for example Twitter (posts), Yomichan doesn't match any
text from the beginning of the line unless you move the mouse cursor to
the top left corner of the word that starts from the beginning of the
line.
Apparently there were some problems related to the imposter and there
was commit 0cc5566 adding a fix for it, but this seemed to cause
problems and 542cdb2 was added to fix that. It didn't handle all of the
cases, though, so this commit is letting everything through on Firefox.
=> fix scanning start of line on Firefox

ext/fg/js/frontend.js
If the event cannot be canceled, the browser will continue to scroll while looking up results, which makes it very difficult to control where the lookup cursor is.
Chrome also logs error messages that this is invalid:
```
[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.
```
=> Don't process touchmove events if they can't be canceled

ext/bg/js/anki.js, ext/bg/js/api.js, ext/bg/js/backend.js, ext/bg/js/dictionary.js, ext/bg/js/options.js, ext/bg/js/settings.js, ext/bg/settings.html, ext/fg/js/api.js, ext/fg/js/frontend.js, ext/fg/js/popup.js, ext/mixed/js/display.js
Add support for exporting a screenshot of the browser tab to Anki. Resolves #169
* Screenshots can now be exported to Anki using the {screenshot} tag.
* Popup is hidden while the screenshot is taken.
* Advanced settings included for screenshot format (png, jpeg) and quality (0-100).
Tested on Chrome Dev 78, Firefox Developer Edition 69, Firefox for Android Beta 68.
=> Anki screenshot

ext/fg/js/frontend.js, ext/mixed/js/display.js
It is sometimes desirable to try to act on the current text selection without performing another scan. For example: a long-press on the selected word to open the context menu.
=> Don't scan when touching the current selection

ext/bg/background.html, ext/bg/context.html, ext/bg/js/search.js, ext/bg/js/settings.js, ext/bg/js/util.js, ext/bg/search.html, ext/bg/settings.html, ext/fg/float.html, ext/fg/js/float.js, ext/manifest.json, ext/mixed/js/extension.js
Resolves #124, but there's a catch.
Here is the [source code](https://github.com/FooSoft/yomichan/blob/168285097004bcc99ecc1dae43e1429c05443d40/ext/bg/js/translator.js#L42) of a basic performance test:
Tested on [a dictionary site](https://jisho.org/search/kyou) with only the common jmdict_english.zip dictionary installed:
Behold, the performance of scanning the word *exactly once* in various different browsers. The result is the number of milliseconds it took to run ```findTerms```.
**Chrome:**
**Firefox:**
**Edge:**
---
These numbers can vary a bit, but the gist is that Edge is *very* slow. More often than not, a basic scan will take in excess of 1 second (the test case was actually one of the better timings). The test was not performed on an exceptionally powerful device, but the …
=> Add support for Edge browser

ext/fg/js/document.js, ext/fg/js/frontend.js, ext/fg/js/source.js, ext/mixed/js/display.js
This change fixes and improves the use of the imposter element:
* CSS ```margin``` property not being zeroed out. This was causing the imposter element to appear in the wrong location in #148, since the ```<textarea>``` had margins and [```getBoundingClientRect```](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) does not include margins in the returned ```DOMRect```.
* Fixed element size sometimes not being correct. Due to rendering differences between ```<textarea>``` and ```<div>```, the size of the imposter element would sometimes not match the original textarea. This is usually due to how the size of the scrollbar(s) affect the size of the textarea. The size of the imposter element is now adjusted to match the textarea if there is a difference.
* …
=> Imposter element improvements

ext/bg/js/options.js, ext/bg/js/settings.js, ext/bg/settings.html, ext/fg/js/document.js, ext/fg/js/frontend.js, ext/mixed/js/display.js
This change allows Yomichan to be able to scan through transparent elements, which includes overlays. There are a few comments to be made about this:
1. There is performance overhead when this change is applied. I did not profile any timings, and my testing didn't necessarily _feel_ slower, but more code will be executed depending on the DOM structure of website.
2. Basically how this works is that when scanning using [```caretRangeFromPoint```](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/caretPositionFromPoint), if no valid text range is found, the "transparent" elements underneath the scan cursor are disabled one-by-one, and the ```caretRangeFromPoint``` sequence is repeated. However, this adds the overhead of adding additional ```caretRangeFromPoint``` and …
=> Deep DOM scanning through transparent elements

ext/bg/background.html, ext/bg/js/api.js, ext/bg/js/backend-api-forwarder.js, ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/js/search-frontend.js, ext/bg/js/settings.js, ext/bg/search.html, ext/bg/settings.html, ext/fg/float.html, ext/fg/js/api.js, ext/fg/js/float.js, ext/fg/js/frontend-api-receiver.js, ext/fg/js/frontend-api-sender.js, ext/fg/js/frontend.js, ext/fg/js/popup-nested.js, ext/fg/js/popup-proxy-host.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js, ext/fg/js/source.js, ext/fg/js/util.js, ext/manifest.json
Allows content of popups to be scanned in the same way that standard webpages are, creating multiple popups to be created in the parent frame.
The concept here is not all that complicated, although it did require some infrastructure to overcome some of the restrictions of browser extensions.
* A PopupProxy class is used inside of ```/fg/float.html```. The public API of this class is the same as the standard Popup class.
* Messages must be passed from the PopupProxy class to the parent frame, and this frame is ultimately where the real Popup is created. Since the popup is created here and not recursively inside of ```/fg/float.html```, there is no need to worry the popup not fitting or getting too small.
* PopupProxyHost is in charge of forwarding API calls to the real Popup.
* New …
=> Recursive popups

ext/bg/js/dictionary.js, ext/bg/js/translator.js, ext/fg/js/document.js
First of several optimizations; this change should slightly reduce memory footprint and slightly increase speed. This change largely optimizes several calls to ```Array.concat``` and ```String.split```, which can be replaced with calls which don't generate intermediate arrays. Also makes a change to ```dictTermsGroup``` to only convert the key array to a string once.
Timing information won't be as relevant for this change, especially since the precision of [```performance.now()```](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now) was reduced in most browsers in light of Spectre and similar exploits. However, I did create several tests for the changes in isolation, which can be run in node or browser.
https://gist.github.com/toasted-nutbread/1b8bab884e95e56483af7d494909baef …
=> Temporary object optimization

ext/fg/js/frontend.js, ext/fg/js/source.js
The range returned by [```docRangeFromPoint```](https://github.com/toasted-nutbread/yomichan/blob/5c793180d04e6b5eafaf01c823f5f5e07639cfa9/ext/fg/js/document.js#L92) is now guaranteed to contain the point due to the addition of [```isPointInRange```](https://github.com/toasted-nutbread/yomichan/blob/5c793180d04e6b5eafaf01c823f5f5e07639cfa9/ext/fg/js/document.js#L290) checks.
=> Omit containsPoint check on searchAt

ext/fg/js/popup-proxy-host.js
If popups are closed and a scan is still occurring, this would result in an orphaned popup which has hidden parents. This would make the orphan popup hard to close without first showing its ancestor popups.
=> Fix nested popups being shown if parent is hidden

ext/fg/js/popup.js
Simplify the check to see if the popup has a parent, since the ```.container``` field should never be null. Also adds a null check to ```contentWindow```, since I encountered a case where this was null. This null case will not occur with the existing features, but I encountered this issue while testing some ideas for moving the popup out of iframes into the root frame.
=> Validate contentWindow before focus

README.md, ext/bg/guide.html, ext/bg/settings.html
* Add rel="noopener" to all anchors with target="_blank".
Rationale: https://mathiasbynens.github.io/rel-noopener/
* Upgrade website URLs to https where applicable. http://ankisrs.net/ also changed to https://apps.ankiweb.net/.
=> URL improvements

ext/fg/js/document.js, ext/fg/js/frontend.js, ext/fg/js/popup-proxy-host.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js, ext/mixed/js/display.js
* Remove manual tracking of mouse left/middle button states from frontend.js. These states are already publicized via [```MouseEvent.buttons```](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons). This should also prevent against inconsistent state issues caused by ```mouseup```/```mousedown``` events not propagating due to external sources calling ```stopPropagation```.
* Simplified early exit condition logic for ```onMouseMove```.
* Removed ```Frontend.mousePosLast```, which does not seem to be referenced anywhere.
* Remove construction of ```{x, y}``` point object and subsequent destructurings in ```Frontend.searchAt```, ```Popup*.containsPoint```, and ```docRangeFromPoint```.
* Rename ```type``` variable to ```cause```, since it better reflects the purpose. (Values …
=> Frontend cleanup

ext/bg/js/settings.js, ext/bg/js/util.js
Prevents dead objects created by different windows. This is primarily an issue in Firefox. The warning produced looked like the following:
<pre><code>TypeError: can't access dead object <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Dead_object">[Learn More]</a></code></pre>
Edge may have a similar issue which I will have to check at some point (just guessing based on that I had to add [```utilReadFile```](https://github.com/FooSoft/yomichan/pull/188/files#diff-da3eea94ffe40f4c8793b0546dc0e6f4R93-R95) for Edge due to a similar cross-window-source object).
Once this is merged, I will have to make changes to #209 to include calls to ```utilBackgroundIsolate``` also.
---
Another note on what I noticed while debugging: settings.html will still display a dead …
=> Isolate options objects created via settings.js

ext/fg/js/document.js, ext/fg/js/source.js
Fixes #215; element names were being reported as lower case.
=> Normalize XHTML document node.nodeNode to upper case

ext/fg/js/frontend.js
Maybe not necessarily a performance improvement in terms of optimization, this improves the delay time when the **Scan delay** option is set to 0 (or lower).
```Promise.resolve().then(callback)``` will run defer ```callback```, but should still run as part of the same event loop. Timers shouldn't be involved when it comes to scheduling when the callback will run. [Info](https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop#Run-to-completion).
The result is that the average time it takes to run the callback is much faster and more consistent. My testing in both Chrome and Firefox indicated that the ```setTimeout(callback, 0)``` approach generally took from 0-10ms, with the results being highly variable. Using the Promise method, the average time was generally less than 0.1ms. …
=> Use a Promise to trigger callback when delay is 0 or less

ext/fg/js/document.js
This would happen when you use press the middle click button and then move the cursor outside of the window while the button is still held. MDN doesn't document that [caretPositionFromPoint](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/caretPositionFromPoint) can return null which is why this case was overlooked.
=> Handle null return value of document.caretPositionFromPoint

ext/bg/background.html, ext/bg/js/api.js, ext/bg/js/backend.js, ext/bg/js/conditions-ui.js, ext/bg/js/conditions.js, ext/bg/js/context.js, ext/bg/js/options.js, ext/bg/js/profile-conditions.js, ext/bg/js/search-frontend.js, ext/bg/js/search.js, ext/bg/js/settings-profiles.js, ext/bg/settings.html, ext/fg/js/float.js, ext/fg/js/frontend.js, ext/fg/js/popup-nested.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js
This change adds the ability to assign customizable conditions to profiles, allowing them to be automatically used in different contexts.
There are currently two types of condition:
* **Popup Level**, which tests the level of the popup. This satisfies @siikamiika's request from #185 for "Settings per nesting level".
* **URL**, which tests against the URL of the current page. This type of condition was added for two reasons:
1) To demonstrate that the conditions can be used for more than just popup level.
2) As something that is potentially useful for the Anki screenshot functionality added in #182 for #169, since maybe screenshots should only be taken on certain video websites like Netflix, etc.
Each condition has different types of operators, which vary depending on which condition is …
=> Settings profile conditions

ext/bg/js/search.js, ext/bg/search.html, ext/fg/float.html, ext/fg/js/float.js, ext/mixed/css/display.css, ext/mixed/js/display.js, ext/mixed/js/scroll.js
There are many places in the ```Display``` class and its subclasses where jQuery is used, but it doesn't (IMO) provide much benefit over native Javascript APIs. The goal of this change is to remove the need to have jQuery loaded in each popup, which would reduce load times and memory footprint. The only thing that didn't really have a counterpart with native Javascript APIs was the smooth scrolling animation, but that is simple enough to recreate (IMO).
Note that I do not think there would be any benefit to try and remove the jQuery dependency from the settings page, as that page actually takes greater advantage of jQuery's features.
This change falls under the purview of #189. Let me know if any of the changes are disagreeable.
---
High level changes:
* Event listeners like …
=> Remove jQuery usage from Display.js

ext/fg/js/frontend.js, ext/fg/js/popup-proxy-host.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js
Fixes #227. This seems like a bug in Chrome, since I don't think scripts should be able to force browser tab focus to change, unless web extensions are privileged enough to do that.
=> Fix tab focus being changed due to settings changes

ext/fg/js/source.js
Simplified the algorithm used for ```TextSourceRange.seekForward``` and ```TextSourceRange.seekBackward```.
Changes:
* Recursion is no longer used, and a single while loop controls iteration across nodes. This functionality is using the ```TextSourceRange.getNextNode``` function I implemented for getting the nodes in a ```Range```.
* Fixed a bug in ```TextSourceRange.getNextNode``` which was null checking the wrong variable.
* The ```shouldEnter``` function had a few optimizations/simplifications as well, the most notable one being that the ```Array.includes``` check was changed to a switch statement since it's faster and doesn't require a temporary array.
Differences:
* Speed of ```seekForward```/```seekBackward``` can be around 10x faster, but this will depend on the length that it's …
=> TextSourceRange improvements

ext/bg/js/database.js, ext/bg/js/deinflector.js, ext/bg/js/translator.js
This change adds support for bulk database lookups and a few other smaller optimizations. A majority of the work came from restructuring some of the code to support bulk lookups, so the changes are listed below.
**Database changes:**
* In database.js, two new bulk functions were added: ```findTermsBulk``` and ```findTermMetaBulk```. These correspond to the old ```findTerms``` and ```findTermMeta```, the difference being that they take an array of terms instead of a single term.
* In order to get the maximum performance, the database lookups are implemented using native IndexedDB API calls. I found that this gave increased performance over Dexie in all browsers, particularly Edge. Edge has some sort of issue with Dexie where ```db.table.getAll()``` will hang before resolving the promise; …
=> Database optimizations

ext/bg/lang/deinflect.json
Adds support for ている inflections. Supports ている, てる, ておる, and ないでいる. The first three are all classified as "progressive or perfect", even though one is humble and one is a contraction. The last is classified as "negative « -te « progressive or perfect".
I chose not to add the とる contraction (at least not in this commit) because と would function slightly differently than て, in that it doesn't stand alone as it's own type of inflection like て does. This functionality can be added, but it would take a few changes to the deinflector.
This change does add some "virtual" deinflection rules to prevent the inflections from being used where they don't make sense. The new values include ```"iru"``` and ```"neg-de"```, both of which are not intended to match any rules found in dictionary files.
Works …
=> Add support for progressive/perfect inflections

ext/bg/js/api.js, ext/bg/js/backend.js, ext/fg/js/float.js, ext/fg/js/frontend.js, ext/fg/js/popup.js, ext/mixed/js/display.js
Changes various handler definitions to be static objects rather than constructed for every event invocation.
* ```keydown``` events now use [KeyboardEvent.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) rather than [KeyboardEvent.keyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode), since keyCode is supposedly deprecated.
* Normalized return types of ```keydown``` handlers to only return ```true``` or ```false```.
* ```wheel``` event handler for ```Display``` simplified.
* Initialization of popups simplified. Combined the ```setOptions``` and ```popupNestedInitialize``` messages into a single ```initialize``` message which contains all of the necessary data. This reduces the number of messages sent.
#189
=> Static handlers

ext/fg/js/frontend.js
Remove event callbacks when the ```options.general.enable``` is ```false```. This is a _very_ minor performance improvement when scanning is enabled (removes the need to check the value every time an event is fired), but should be more impactful when scanning is disabled (no callbacks hooked to frequently invoked events like ```mousemove```, ```touchmove```, etc.) #189
This also fixes a line which used to be checking ```this.options.enable``` rather than ```this.options.general.enable```.
This will cause a merge conflict with #233 due to https://github.com/FooSoft/yomichan/pull/233/commits/7d15213916355a806ba687803ca94209e29f142c#diff-6559642516f798ca10f6693f70f1481eL58-R58, but I will fix those up when necessary.
=> Remove event listeners when scanning is disabled

ext/bg/js/deinflector.js, ext/bg/js/translator.js, ext/bg/lang/deinflect.json
This change addresses two things:
1. The deinflection rules added in #235 weren't specific enough and were generating false positives. Invalid terms like 着かないで and 着かないでない were being deinflected incorrectly. This change improves the specificity of the deinflection rules, as well as adds support for the とる contraction which I previously thought would be more difficult. This change fixes all the false positives that I was seeing.
2. Improves the performance of ```Deinflector.deinflect``` by somewhere in the range of 2x to 5x. Previously, the deinflect algorithm would do an intersection test on the rule arrays to see if there was any overlap. This has been simplified to use a bitwise ```&``` check instead, after first converting the rules arrays into a single flags integer value.
This is …
=> Deinflector optimization

ext/bg/js/search.js, ext/fg/js/float.js, ext/fg/js/frontend.js, ext/fg/js/popup-proxy-host.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js, ext/mixed/js/display.js
The goal of this change is to remove the frequency at which options updates are propagated to popups and Display implementations. Since the options structure is non-trivially sized, there is likely some overhead involved in sharing it across the cross-frame messaging systems. Reducing the size should improve speed slightly.
* ```Display``` is now required to be ```.initialize()```'d before it can properly be used. The initialization process sets up the options value.
* ```Popup``` also now stores options.
* Removed ```.show``` function on ```PopupProxy``` since it's not publicly used.
* Remove ```options``` argument for ```termsShow```, ```kanjiShow```, ```showOrphaned```. These functions now use the reference stored from initialization and options updates.
* Removed …
=> Display options improvements

ext/bg/css/settings.css, ext/bg/js/options.js, ext/bg/js/search.js, ext/bg/js/settings-popup-preview.js, ext/bg/js/settings.js, ext/bg/search.html, ext/bg/settings-popup-preview.html, ext/bg/settings.html, ext/fg/css/client.css, ext/fg/float.html, ext/fg/js/float.js, ext/fg/js/frontend.js, ext/fg/js/popup-proxy-host.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js, ext/mixed/css/display-dark.css, ext/mixed/css/display-default.css, ext/mixed/css/display.css, ext/mixed/js/display.js
This change adds support for previewing some of the styles of the popup from the settings page. This allows custom CSS changes to be visualized in real time.
* Popup preview added to settings page. The background on this page can be switched from dark to light to visualize the popup on different backgrounds.
* Bootstrap styles removed from float.html. Very few were actually used, so this may allow the page to load (very slightly) faster.
* Added support for popup themes. Currently includes the default light theme and a new dark theme.
* Added support for popup shadow themes. Since the box shadow for the popup is outside of the iframe, custom CSS can't be applied in the same way. Three themes are supported: ```default```, ```dark```, and ```auto```. ```auto``` will select the best shadow …
=> Popup style preview + themes

ext/bg/settings.html, ext/manifest.json
Turns out that the ```unlimitedStorage``` permission cannot be an optional permission in the manifest and enabled on demand, so it would have to be added to the manifest as a default permission.
However, I don't know if adding this permission will cause the extension to be disabled when it is updated. Some research seems to indicate that [adding the ```unlimitedStorage``` permission won't disable the extension](https://stackoverflow.com/questions/42868472/unlimitedstorage-not-supported-by-chrome-optional-permission-api-how-to-update), but this info may be out of date.
I'm not sure what the behaviour is on Chrome, but the behaviour on Firefox is to show a popup warning about additional required permissions when it updates versions. For reference, I have seen …
=> Add unlimited storage permission

ext/bg/js/database.js, ext/bg/js/translator.js, ext/bg/js/util.js
Optimization of the remainder of the database calls. Completes the database read optimizations started in #229.
* Bulk operations are now used for all database reads, all of which use native IndexedDB APIs for maximum speed.
* Reduced complexity of ```Translator.findTermsMerged```'s function body by creating some helper functions which do portions of the work. This should also make it easier for Javascript compilers to optimize (typically they're bad at dealing with very large functions).
* Moved the tag cache out of ```Database``` and into ```Translator```. This makes it so that ```Database``` doesn't have to worry about caching, only requesting and updating data.
* A few other simplifications to ```sort``` calls and other inline functions.
This change mostly affects the speed when the …
=> Database optimizations part 2

ext/bg/js/handlebars.js
This should fix #264 
Note it does not address broken segmentation, just representation within Anki itself to work properly.
I've tested these changes locally and it works fine for all cases:
```js
> plainFurigana('お祝い', 'おいわい')
"お 祝[いわ]い"
> plainFurigana('食べ物', 'たべもの')
"食[た]べ 物[もの]"
> plainFurigana('林業試験場', 'りんぎょうしけんじょう')
"林業試験場[りんぎょうしけんじょう]"
> plainFurigana('美味しい', 'おいしい')
"美味[おい]しい"
> plainFurigana('試し斬り', 'ためしぎり')
"試[ため]し 斬[ぎ]り"
> plainFurigana('飼い犬', 'かいいぬ')
"飼[かい]い 犬[ぬ]"
```
The last one has improper segmentation but it's beyond the scope of this PR.
=> Proper spacing for Anki in {furigana-plain}

ext/bg/js/settings-popup-preview.js, ext/fg/js/frontend.js, ext/mixed/js/extension.js
This is the first set of changes necessary to support [pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events). This PR largely simplifies the logic and makes it easier to understand. There was previously a lot of extra code to handle edge cases which realistically won't happen (using two fingers to try to scan text), so this code has been simplified. Event prevention has also been simplified, and a few issues which would cause the context menu to not open have been fixed.
The only intentional behaviour difference is that right clicking will not close the popup; only a left click will do this. This is useful if a user wants to right click on the selected text to copy it or something.
Creating as a PR for tracking purposes. #267
=> Refactoring of touch events

ext/mixed/js/audio.js
There is a bug (seemingly unreported) in Yomichan where an Anki card
will not contain any audio if the JapanesePod101 audio source trumps
a secondary audio source (e.g. JapanesePod101-alternate) where
the jpod101 source can't find the word requested.
For example, そして has an audio entry in the alternate source but not
the standard source, so Anki cards created from そして won't have an
audio field set.
(Alternatively, there may be a bug in the jpod101 audioUrlBuilder,
because I've only noticed this problem with hiragana-only expressions.
JPod101 may not host those on the same url scheme any more.  I'm not
sure how to fix that, though, and the bug I'm addressing here does
still persist).
The reason this happens is that audioGetFromUrl uses downloaded audio
to effectively check for a 404 (by …
=> Remove Download check when resolving Audio data

ext/bg/background.html, ext/bg/js/api.js, ext/bg/js/backend.js, ext/bg/js/mecab.js, ext/bg/js/options.js, ext/bg/js/search-query-parser.js, ext/bg/js/search.js, ext/bg/js/settings.js, ext/bg/js/templates.js, ext/bg/search.html, ext/bg/settings.html, ext/fg/js/api.js, ext/manifest.json, ext/mixed/css/display.css, ext/mixed/js/display.js, ext/mixed/js/japanese.js, tmpl/query-parser.html
I'm opening a pull request because I need a few comments from other developers before I am ready to merge this.
This pull request adds a text parser to the search page that uses two different methods.
The first method that is enabled by default uses the built-in scanning so that it takes the longest result and matches readings from the best match using the score-based sorting and a new furigana function.
The other method is more problematic, as it uses native messaging to parse the text in an external application, MeCab. Here's a list of concerns:
- Should the protocol between the MeCab native host and Yomichan be versioned, and if it should, how? I'm planning to add part of speech highlighting in the future when I have investigated MeCab IPADIC part of speech tag names. I already have a …
=> Search page query parser

ext/bg/js/settings-profiles.js, ext/bg/js/settings.js, ext/bg/js/util.js, ext/fg/js/util.js
Creating this as a PR since there's some background info here, in case this ever has to be referenced again.
```utilAsync``` in the foreground is no longer used so it can be removed.
```utilAsync``` is used very infrequently and can easily be replaced by ```(e) => someFunction(e)```.
History:
```utilAsync``` was initially added in bdf231082f4b4ca7c4c90d8b0cd40b6c4201723d. Presumably this was to work around some issues with the version of jQuery being used (v3.2.1) where async functions are not detected correctly. This was most apparent with something like ```$(document).ready(async () => {})``` not working. This seems to be caused by the ```jQuery.type``` function returning invalid results for async functions.
https://github.com/jquery/jquery/blob/3.2.1/src/core.js#L269-L278 …
=> Remove utilAsync

ext/mixed/js/display.js
Does this fix #58, specifically in afddec66eb749aa0a39c7e7142f929e68697995d? I'm not sure if there's something I'm overlooking, but my understanding is that ```text.substring(offset, offset + source.length)``` should equal ```source``` most of the time, with the only difference being the use of katakana vs hiragana.
=> Cloze fixes

ext/bg/js/search-frontend.js, ext/bg/js/search-query-parser.js, ext/bg/search.html, ext/fg/js/frontend.js, ext/fg/js/popup-nested.js, ext/manifest.json, ext/mixed/js/text-scanner.js
This refactoring was done because other parts of Yomichan are also using text scanning. In popups you can click kanji and glossary, and on search page you can scan text using query parser. Query parser needs to do almost everything that normal scanning does but it doesn't have a popup. Instead of copying and modifying all touch event code from Frontend I created a new class that takes in the scanned element and rules about what elements and places to ignore, and offers a pub/sub interface that emits text sources and other events related to scanning.
After this is reviewed, Im going to replace the duplicated scanning code in query parser and possibly also Display.
https://github.com/FooSoft/yomichan/issues/267
https://github.com/FooSoft/yomichan/pull/279
=> Extract text scanner from Frontend 

ext/bg/js/database.js, ext/bg/js/options.js, ext/bg/js/search.js, ext/bg/js/settings/dictionaries.js, ext/bg/js/translator.js, ext/bg/js/util.js, ext/bg/settings.html, ext/mixed/js/core.js
This change adds support for prefix wildcards. The new option must be enabled and dictionaries must be reimported before it works, since the database is required to store the reversed-string expression/readings for each entry.
This option is disabled by default due to the additional space used by storing reversed strings. Some numbers when using jmdict_english:
```
No dictionaries installed:
Firefox: 49.2KB
Chrome: 7.0KB
Old version:
Firefox: 147.0MB
Chrome: 72.1MB
With new database indices only:
Firefox: 147.0MB
Chrome: 72.1MB
With new databases and data:
Firefox: 182.9MB
Chrome: 78.5MB
```
Simultaneous prefix and suffix wildcards are not supported due to the limitations of IndexedDB.
This resolves #128 as much as is possible with IndexedDB.
Tracking issue: #270
---
=> Prefix wildcards

ext/bg/js/settings/main.js, ext/bg/js/util.js
In combination with #306, this fixes #303. With the exception of how the settings page mutates the backend `options` object, all data should now belong to the window it is being used in.
=> Context isolation

ext/bg/js/settings/popup-preview-frame.js, ext/fg/js/frontend.js, ext/fg/js/popup-proxy-host.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js
Flag internally used functions/fields with underscore prefix to indicate that they should be treated as private. The intent is to make it more clear what is referenced in other files, since it's not easy to search for references since Javascript isn't a strongly typed language. The `_` prefix helps indicate that you would only need to search within the current file.
This should help me address a few issues with the popup class.
Previous discussion: #258
=> Popup class private members

ext/bg/background.html, ext/bg/js/backend.js, ext/bg/js/search.js
This addresses a few things:
* Improves performance while the page is focused. Increased delay from 100ms to 250ms. When the page is in the background, delays are typically throttled to minimum 1000ms anyways.
* Ensures there are no overlapping interval callbacks. The `async` delay isn't taken into account when starting the next delay, so technically it's possible for two callbacks to be running 'simultaneously'.
* Added some info about clipboard copying, removing a TODO.
* Improved Firefox browser detection.
* Improved clipboard paste process in the backend to only paste plaintext instead of rich text.
=> Clipboard monitor refactor

ext/bg/js/backend.js, ext/bg/js/dictionary.js, ext/bg/js/options.js, ext/bg/js/settings/anki-templates.js, ext/bg/js/settings/main.js, ext/bg/js/util.js, ext/bg/settings.html
This change makes the custom Anki field templates `null` if it's the default value. This should make future upgrading easier, as well as make there be less data passed around when it's not needed.
=> Templates null default

ext/bg/background.html, ext/bg/data/options-schema.json, ext/bg/js/backend.js, ext/bg/js/json-schema.js, ext/mixed/js/api.js
This change adds support for a JSON validation schema for the options. Currently based on https://json-schema.org/.
The scheme is not fully used yet; validation is currently only performed on extension startup. In the future, the proxy system will be applied to the entire settings object such that all modifications are validated. This will be done in a later commit, otherwise the settings page would be throwing exceptions it's not currently equipped to handle.
This is tracked in #296.
=> Options schema

ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/js/settings/backup.js, ext/bg/js/util.js, ext/bg/settings.html
Adds support for exporting settings, importing settings, and resetting all settings to default values.
**This commit is dependent on the features added in #309 and #310.** I am putting this up now because there are no code conflicts, but the features added in those PRs are required for this change to work.
* The export button exports to a .json file. The file includes the options and some additional metadata for debugging/informational purposes.
* The import button imports this file and overwrites the settings. Since certain options could be considered insecure if they are coming from an untrusted source, a warning will appear if these settings are considered suspicious. Currently this includes:
* Non-default `anki.fieldTemplates`, since this value can effectively `eval` code.
* …
=> Settings import export

ext/bg/js/search-query-parser.js, ext/bg/js/search.js, ext/fg/js/frontend.js, ext/mixed/js/text-scanner.js
Continuation of https://github.com/FooSoft/yomichan/pull/299.
Fixes blinking results in https://github.com/FooSoft/yomichan/pull/317 so that it can be merged and used to fix https://github.com/FooSoft/yomichan/issues/325.
Also enables scanning query parser text on touchscreen devices.
`TextScanner` could potentially be used in `Display` as well, but it's more work and has less benefits because it only uses click events.
=> use TextScanner in QueryParser

ext/bg/data/options-schema.json, ext/bg/js/handlebars.js, ext/bg/js/options.js, ext/bg/js/search.js, ext/bg/js/settings/main.js, ext/bg/js/translator.js, ext/bg/settings.html, ext/mixed/js/japanese.js
This PR adds support for #313 and a few other things.
* Changed how deinflection variants are handled. This was previously only used for finding deinflections using both the raw text and the text source converted to hiragana, but has been extended with some additional options:
* **Convert katakana to hiragana** (ヨミチャン → よみちゃん) _[default: true]_
* **Convert half width characters to full width** (ﾖﾐﾁｬﾝ → ヨミチャン) _[default: false]_
* **Convert numeric characters to full width** (1234 → １２３４) _[default: false]_
* **Convert alphabetic characters to hiragana** (yomichan → よみちゃん) _[default: false]_
* Each of the above options has three possible values: `'false'`, `'true'`, `'variant'`.
* `'false'` indicates that the conversion will not be performed.
* `'true'` indicates that the conversion will …
=> Deinflection variants

ext/mixed/css/display.css, ext/mixed/display-templates.html, ext/mixed/js/display-generator.js
Fixes #339 by changing display to `inline-block` and adding an inner `display: block` element. This also makes triple click work in case there are spaces. This change also improves the tag layout slightly. The vertical spacing is a bit better. [Old](https://user-images.githubusercontent.com/11037431/73411135-4962d280-42d2-11ea-82dd-1e9717fe3b08.png) vs [New](https://user-images.githubusercontent.com/11037431/73411137-4cf65980-42d2-11ea-834e-fc77d297fa48.png); Open in two new tabs and cycle between them.
=> Fix tag double click

ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/js/settings/main.js, ext/bg/settings.html, ext/mixed/css/display-dark.css, ext/mixed/css/display-default.css, ext/mixed/css/display.css, ext/mixed/display-templates.html, ext/mixed/js/display-generator.js, ext/mixed/js/display.js
Fixes  #53 
Clicking the tags performs the same scan as clicking glossary and it can be hard to hit the first character on the tags due to their small font size. It would require some refactoring in `onTermLookup` to make clicks always search the contents of the entire tag. Maybe it could be facilitated with `TextScanner`.
=> add scannable tags for expression and reading

ext/bg/background.html, ext/bg/css/settings.css, ext/bg/data/options-schema.json, ext/bg/js/api.js, ext/bg/js/backend.js, ext/bg/js/clipboard-monitor.js, ext/bg/js/context.js, ext/bg/js/options.js, ext/bg/js/search.js, ext/bg/js/settings/main.js, ext/bg/search.html, ext/bg/settings.html, ext/mixed/css/display.css, ext/mixed/js/core.js
Uses clipboard as a text source for now, but adding this to the API discussed in #262 is going to be done in a separate PR later.
Refactoring a new class `ClipboardMonitor` out of `search.js` and `backend.js` is planned, but I'm opening a PR in case there are bigger problems to fix first.
Right now it works by opening the search page in a native popup window. It could make sense to hide text input and disable the regular clipboard monitor when the search page is opened in a popup, but query parser is useful even there.
=> Native popup windows

ext/bg/data/dictionary-index-schema.json, ext/bg/data/dictionary-kanji-bank-v1-schema.json, ext/bg/data/dictionary-kanji-bank-v3-schema.json, ext/bg/data/dictionary-kanji-meta-bank-v3-schema.json, ext/bg/data/dictionary-tag-bank-v3-schema.json, ext/bg/data/dictionary-term-bank-v1-schema.json, ext/bg/data/dictionary-term-bank-v3-schema.json, ext/bg/data/dictionary-term-meta-bank-v3-schema.json, test/dictionary-validate.js
Defines schemas for the dictionary JSON files that can be imported.
I am adding this for a few reasons:
* In a future commit, these should be used to validate data before importing, which should help to prevent unwanted data from getting into the database.
* This can be used as a sort of documentation of the file format, in case anyone wants to generate their own dictionaries from a custom data set (#322). Will also serve to document future changes and additions to the types of data supported (e.g. pitch accents #61).
Note that the descriptions of everything are based on how I am seeing the values be used in the code. If anyone has any better descriptions for anything, feel free to suggest.
Also adds a validation script which can be run using node. I have validated the following …
=> Dictionary schemas

ext/bg/js/audio.js, ext/bg/js/backend.js, ext/bg/js/database.js, ext/bg/js/dictionary.js, ext/bg/js/settings/dictionaries.js, ext/bg/js/translator.js, ext/bg/js/util.js, ext/mixed/js/audio.js, ext/mixed/js/text-scanner.js, test/test-database.js
Kind of a follow-up on #358, but this change is mostly updating more objects to use `Set` or `Map`. There should be some slight improvements to some of the functions in translator.js also.
=> More type refactoring

ext/bg/data/default-anki-field-templates.handlebars, ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/js/settings/anki-templates.js, ext/bg/js/settings/backup.js, ext/mixed/js/api.js
While looking into #378, I realized that it's somewhat annoying to look at the default field templates with syntax highlighting. To do this, the defaults must be copied either from options.js or from the settings page, both of which is an extra step. Moving the handlebars templates into a separate file allows them to be viewed in isolation more easily, and also follows the pattern used to have JSON data in separate files.
This currently does affect the settings upgrade process for _very_ old settings, from around version 1.5.2 (2017-11-08). However, IMO the conditions to cause this should be sufficiently rare that it's better to just omit the additional code/complexity it would take to maintain the same upgrade: user is upgrading from 1.5.2 to 20.2.24.0+ (rare) and has modified their Anki …
=> Load default Anki field templates from a file

test/dictionary-validate.js, test/schema-validate.js, test/test-database.js, test/test-document.js, test/test-schema.js, test/yomichan-test.js, test/yomichan-vm.js
Use node [`vm`](https://nodejs.org/api/vm.html) module instead of `Function` constructors. This makes it possible to have the declarative environment record variables (i.e. variables defined using `let`, `const`, and `class`) implicitly passed around using the `context` variable. This also makes any error messages have a more meaningful stack trace, contrasted to [the stack trace seen with the `Function` constructor](https://github.com/FooSoft/yomichan/runs/478639605#step:7:15).
The only downside to this is that `assert.deepStrictEqual` doesn't work for certain values since `assert.deepStrictEqual` compares object prototypes using `===`, and the object prototypes of cross-context objects will be different. Therefore, `vm.assert` was added with a relaxed version of `deepStrictEqual`.
=> Abstract Yomichan extension script execution

ext/fg/js/popup-proxy-host.js
The point can originate from within a popup where the coordinates start from the top left corner of the popup iframe. containsPoint check is done on the root page, and thus the offset has to be adjusted to match the point inside the iframe rect.
Fixes https://github.com/FooSoft/yomichan/issues/394
=> adjust containsPoint offset with nested popups

ext/fg/js/frontend-api-sender.js
Helps with https://github.com/FooSoft/yomichan/issues/392. I was able to reproduce the issue again, but with this patch Yomichan is able to continue operation after failing one API request and printing an error to the console. It would also be possible to retry the same request after a timeout, but I don't think this issue is so big that the complexity is warranted.
=> reconnect FrontendApiSender after disconnecting

ext/fg/js/frontend-initialize.js, ext/fg/js/popup-proxy-host.js
This was originally implemented in https://github.com/FooSoft/yomichan/commit/16521fec935845828b7e08baf1668657bb5a7cef, but broken somewhere in between.
=> start popup depth from 1 on search page

ext/bg/js/handlebars.js, ext/bg/js/japanese.js, ext/bg/js/translator.js, ext/mixed/js/display-generator.js
Resolves #331.
There are still some places in the codebase where UTF-16 character code iteration is still used. Some of these should be fine, while others may potentially have issues with the rare kanji.
For example:
https://github.com/FooSoft/yomichan/blob/7541517d8084b50e054393f3b4fa6d4630ad012e/ext/bg/js/search-query-parser.js#L158-L166
document.js could also have some issues, but I won't touch those for now due to #286.
=> Replace charCodeAt and fromCharCode with codePointAt and fromCodePoint

ext/mixed/js/object-property-accessor.js, package.json, test/test-object-property-accessor.js
This class is intended to be used while implementing #335. This basically redoing part of the commit "[Update implementation of apiOptionsSet](https://github.com/toasted-nutbread/yomichan/commit/d871e020d30201f7aa1f08326f1ae8028c2d84e2#diff-dbd09b161e2e61a02b016ee5e11a5cb3)" that I mentioned in a comment on that issue. The end goal is to assign settings [like this](https://github.com/toasted-nutbread/yomichan/commit/d871e020d30201f7aa1f08326f1ae8028c2d84e2#diff-ae1c71fb13eb3a96c1cce3899144a9dcL78-R82) and enforce schema validation.
=> Object property accessor

ext/bg/js/search-frontend.js, ext/bg/js/search-query-parser.js, ext/bg/js/search.js, ext/fg/js/float.js, ext/fg/js/frontend-initialize.js, ext/fg/js/frontend.js, ext/fg/js/popup-nested.js, ext/fg/js/popup-proxy-host.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js, ext/mixed/js/display.js, ext/mixed/js/text-scanner.js
Extracted from https://github.com/FooSoft/yomichan/pull/389. I think these can be useful while deciding what's the best way to quickly change profiles and how to display it.
Was there a reason why `Frontend` was initialized with options from `Popup`? I removed it to make the code simpler, but it can make the popup appear a bit slower on the first scan.
=> apply all options on profile change

ext/bg/background.html, ext/bg/js/audio-uri-builder.js, ext/bg/js/backend.js, ext/bg/js/clipboard-monitor.js, ext/bg/js/handlebars.js, ext/bg/js/japanese.js, ext/bg/js/translator.js, ext/bg/search.html, ext/bg/settings.html, ext/fg/float.html, ext/mixed/js/display-generator.js, ext/mixed/js/japanese.js, package.json, test/test-japanese.js
Creating this PR now in order to determine a preferred style for module-like style that can also be used for https://github.com/FooSoft/yomichan/pull/385#discussion_r386722493. I'll probably create some unit tests for this also, but they are not added yet.
The diff for japanese.js makes it look like everything changed, but the main differences are some variable renames (remove jp* prefix), added indentation, and rearranging the declarations.
Related: #372
=> Convert Japanese utilities to a module-like style

.eslintrc.json, ext/bg/data/dictionary-term-meta-bank-v3-schema.json, ext/bg/data/options-schema.json, ext/bg/js/dictionary.js, ext/bg/js/options.js, ext/bg/js/settings/main.js, ext/bg/js/translator.js, ext/bg/settings.html, ext/mixed/css/display-dark.css, ext/mixed/css/display-default.css, ext/mixed/css/display.css, ext/mixed/display-templates.html, ext/mixed/js/core.js, ext/mixed/js/display-generator.js, ext/mixed/js/display.js, ext/mixed/js/japanese.js, test/data/dictionaries/valid-dictionary1/tag_bank_3.json, test/data/dictionaries/valid-dictionary1/term_meta_bank_1.json, test/test-database.js, test/test-japanese.js
Adds support for #61.
The dictionary generation script can be found here:
https://github.com/toasted-nutbread/yomichan-pitch-accent-dictionary
A build of the dictionary can be found here:
https://github.com/toasted-nutbread/yomichan-pitch-accent-dictionary/releases/tag/1.0.0
There are three different modes for displaying pitch accent data, each of which can be enabled/disabled individually.
* **Show downstep notation for pitch accents**
Shows a bar over characters with a higher pitch and, if present, a small down bar where the pitch drop is.
* **Show position notation for pitch accents**
Shows the numeric indication for the accent position. E.g. [1]
* **Show graph for pitch accents**
Shows a graph of points indicating the accent positions of the mora. Currently disabled by default.
Here …
=> Pitch accents

ext/bg/background.html, ext/bg/js/japanese.js, ext/bg/js/text-source-map.js, ext/bg/js/translator.js, package.json, test/test-japanese.js, test/test-text-source-map.js
Since the text source map functionality is likely to be used more in the future, it's probably best to abstract it so it's easier to reuse. Related to #421.
Note that the source map operates on UTF16 characters and not unicode code points. This makes it easier to do things like `string.substring` since the lengths are character-based.
=> Text source map

ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/js/search-frontend.js, ext/bg/js/settings/main.js, ext/bg/settings.html, ext/fg/js/frame-offset-forwarder.js, ext/fg/js/frontend-initialize.js, ext/fg/js/frontend.js, ext/fg/js/popup-proxy-host.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js, ext/manifest.json, ext/mixed/js/core.js, test/test-database.js
Replaces https://github.com/FooSoft/yomichan/pull/364.
Fixes https://github.com/FooSoft/yomichan/issues/29.
https://github.com/FooSoft/yomichan/commit/765c1feec9b954c0d0cf79fa2146b0954466c987 does basically the same thing as https://github.com/toasted-nutbread/yomichan/tree/iframe-popups. The difference is that it's compatible with the ID generation in https://github.com/FooSoft/yomichan/pull/411 and doesn't expect the ID to be `'root'`. It should also handle the timing issue.
https://github.com/FooSoft/yomichan/commit/5c216a9416475116ecba191fa6f0e648de94bc83 replaces `frameIdPromise` with `frameId` (https://github.com/FooSoft/yomichan/issues/356).
https://github.com/FooSoft/yomichan/pull/417/commits/ea1da87041fad7eb04f2b70d0bacb26eeb4428bf is the magic, it basically passes an offset …
=> Show iframe popups on root page

ext/bg/js/anki-note-builder.js, ext/bg/js/backend.js
Moving the media injection functions into AnkiNoteBuilder for some preliminary cleanup. Subsequent tasks will include:
* Removing `optionsContext` from `injectAudio` in favor of adding the relevant parameters directly to the object. The `optionsContext` is used to pass a copy of `options` to `AudioUriBuilder`'s `_getUriTextToSpeech` and `_getUriTextToSpeechReading` where only `options.audio.textToSpeechVoice` is used. This can be simplified to just passing `textToSpeechVoice` as a part of the `details` object that is used.
* Potentially refactoring how audio is injected into cards. This was originally brought up in https://github.com/FooSoft/yomichan/pull/277#issuecomment-552145454.
=> Anki card media injection refactor

ext/bg/js/database.js, ext/bg/js/dictionary-importer.js, ext/bg/js/settings/dictionaries.js
There were some issues with dictionary import errors showing up as `[object Object]` due to being cross-window references.
=> Error fixes

ext/bg/js/backend.js, ext/fg/js/float.js, ext/fg/js/frame-offset-forwarder.js, ext/fg/js/frontend-initialize.js, ext/fg/js/frontend.js, ext/mixed/js/api.js, ext/mixed/js/display.js
This PR fixes a few issues causing the following error message to be shown:
```
Unchecked runtime.lastError: The message port closed before a response was received.
```
This was primarily caused by `apiForward`, which was was awaiting the response of its `sendMessage` call, rather than ignoring it. This behaviour was initially described in #185. There was a similar issue in the `yomichanCoreReady` handler.
This PR makes the following changes:
* API message handlers are now defined as an object of the form `{handler: function, async: boolean}`. The `handler` is the same function as before, and the `async` value indicates whether the function returns a promise or not. When `async` is `false`, the handler can be optimized to return early.
* A few handlers which didn't require `async` have …
=> Backend api handler changes

ext/mixed/css/display.css, ext/mixed/display-templates.html, ext/mixed/js/display-generator.js
As I was working on #322, I ran into something that would require some changes to `DisplayGenerator`. Rather than trying to incorporate it into that change, I decided to to isolate it into a separate PR.
The following changes are made:
* `static` functions converted to normal functions. (https://github.com/FooSoft/yomichan/pull/424#issuecomment-609039565)
* Marked functions as private.
* Renamed identifiers which include "only" to use "disambiguation" instead. This is in order to improve clarity and better match `_createPitchAccentDisambiguations`.
* Removed `data-multi` attribute assignment and usage, since it is redundant.
* Refactored `_appendMultiple` to be more streamlined and support passing additional arguments. (This was the change I needed for #322.)
* Some cleanup related to the …
=> Display generator refactoring

ext/bg/data/options-schema.json, ext/bg/js/japanese.js, ext/bg/js/options.js, ext/bg/js/settings/main.js, ext/bg/js/translator.js, ext/bg/settings.html, test/test-japanese.js
Resolves #421.
This change adds a new translation option: **Collapse emphatic character sequences**. It has three possible values:
* "Disabled"
かっっっこい => かっっっこい
* "Collapse into single characters"
かっっっこい => かっこい
* "Remove all characters"
かっっっこい => かこい
One special case that I decided to not handle initially is what to do with っ sequences at the start of the string. Currently, they still collapse, so っっっこい converts to っこい. This case can be changed if necessary.
Related question: should `ー` characters also be able to be collapsed in some way?
=> Add support for collapsing emphatic character sequences

ext/bg/js/search.js, ext/mixed/js/text-scanner.js
`getSelection` only works on window, not on DOM nodes.
=> Fix getSelection not working in QueryParser

ext/bg/js/search-frontend.js, ext/bg/js/search-query-parser.js, ext/fg/js/frontend-initialize.js, ext/fg/js/frontend.js, ext/fg/js/popup-nested.js, ext/mixed/js/text-scanner.js
Fixes https://github.com/FooSoft/yomichan/issues/431
=> Popup live toggle

ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/js/settings/anki.js, ext/bg/js/settings/dictionaries.js, ext/bg/js/util.js, ext/fg/js/popup.js, ext/mixed/js/api.js, ext/mixed/js/core.js
This change is primarily some organizational changes. The motivation behind some of these changes was initially documented in https://github.com/FooSoft/yomichan/issues/353#issuecomment-608961786.
* Change `Popup._isOnExtensionPage` to `yomichan.isExtensionUrl`.
* Converts several `util*` functions which implicitly used [`chrome.extension.getBackgroundPage()`](https://developer.chrome.com/extensions/extension#method-getBackgroundPage) into `api*` functions. There are still a few places left where this is used, but they are non-trivial to convert (they have progress callbacks).
* Move `utilStringHashCode` into options.js since that's the only place it's used.
=> Util conversions

ext/bg/data/dictionary-term-meta-bank-v3-schema.json, ext/bg/js/translator.js, test/data/dictionaries/valid-dictionary1/term_meta_bank_1.json, test/test-database.js
Resolves #382. Data format is as described in https://github.com/FooSoft/yomichan/issues/382#issuecomment-593178227.
=> Add support for filtering frequency metadata based on readings

ext/fg/js/frame-offset-forwarder.js, ext/fg/js/frontend-initialize.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js, ext/manifest.json, ext/mixed/js/dom.js, test/data/html/test-document2.html, test/data/html/test-document3-frame1.html, test/data/html/test-document3-frame2.html, test/data/html/test-document3.html
Support the following edge cases:
- Iframe is fullscreen: create a popup inside the iframe regardless of `options.general.showIframePopupsInRootFrame` value, but return it back when fullscreen is closed
- Iframe in open shadow dom: find the content window recursively and support positioning normally
- Iframe in closed shadow dom: fall back to popups inside iframe
Fixes https://github.com/FooSoft/yomichan/issues/432
=> Iframe popup edge cases

ext/bg/js/anki-note-builder.js, ext/bg/js/audio-uri-builder.js, ext/bg/js/backend.js, ext/bg/js/settings/audio.js, ext/mixed/js/api.js, ext/mixed/js/audio-system.js, ext/mixed/js/display.js
Various refactorings/fixes to the audio-related classes.
* Refactored the arguments that are passed to `AudiUriBuilder.getUri`, `AnkiNoteBuilder.injectAudio`, and `AudioSystem.constructor`. The intent is to make it so that only the relevant details are passed, rather than the entire `options` object or an `optionsContext`. This was mentioned in the first bullet point of https://github.com/FooSoft/yomichan/pull/427#issue-397307625.
* Disabled audio caching on the backend when creating cards. Caching should not be necessary and could potentially cause unnecessary memory to remain allocated.
* Updated the audio cache to only return a value if the source is in the `sources` parameter.
* Fixed a bug where the cache didn't work correctly (was using the wrong key).
* Fixed a bug on the audio …
=> Audio system refactoring

ext/bg/js/backend.js, ext/bg/js/util.js
Some improvements to the status reporting functionality on the browser badge. This satisfies the following task from #270:
> Indicate when the backend / database is upgrading. When the database version is upgrading, the extension won't run. This operation can take multiple seconds, so it can be noticeable. This was the case in the version upgrade in #287, despite the difference being very small.
When the backend is `prepare()`ing, the status will show as "..." if it takes longer than 1 second. Additionally, if any error occurs during `prepare()`, this will be logged and the status will change to a red "!!". Additionally, the hover tooltip text is changed to reflect this status.
Prepare errors don't/shouldn't currently happen in typical use cases, but it can in development workflows. For …
=> Badge improvements

ext/mixed/js/dynamic-loader-sentinel.js, ext/mixed/js/dynamic-loader.js
First part of addressing https://github.com/FooSoft/yomichan/pull/463#issuecomment-617450215. The original issue was that, despite being `async=false`, the scripts are not loaded immediately after injection into the DOM. So there wasn't a way to know when all the scripts were completed loading. Injecting an additional script which triggers an event solves this problem.
This should open the path to not using `frontendInitializationData`, but instead just calling a function that is now available in the global scope.
=> Create dynamic script/CSS loader utility

ext/mixed/js/japanese.js, test/test-japanese.js
Fixes #469.
I created [this](https://toasted-nutbread.github.io/japanese-pitch-accent-table/) for testing, which contains data which comes up in Google searches for "[Japanese pitch accent table](https://www.google.com/search?q=Japanese+pitch+accent+table&tbm=isch)". https://imgur.com/oEjxhWU
=> Fix high pitch calculation

ext/bg/js/search.js, ext/bg/js/settings/popup-preview-frame-main.js, ext/bg/js/settings/popup-preview-frame.js, ext/bg/js/settings/popup-preview.js, ext/bg/js/settings/profiles.js, ext/fg/js/content-script-main.js, ext/fg/js/float.js, ext/fg/js/frontend.js, ext/fg/js/popup-proxy-host.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js, ext/mixed/js/display.js
Resolves https://github.com/FooSoft/yomichan/issues/452.
Now setting `optionsContext` to `Popup` and `DisplayFloat` means also updating options. Because both use `optionsContext` separately from the `options` object, I simplified the code so that new options are fetched by the classes themselves. A bit different from the discussion in #452, but I thought it makes more sense this way.
Each time `optionsContext` is set to a `Popup`, it comes along with the unique ID of the `Frontend` that set it. This is needed when the `Frontend` using the `Popup` changes. For performance reasons, it's sent along with `Popup.showContent` arguments when scanning, but otherwise using `Popup.setOptionsContext`. Scanning checks if the `Frontend` ID has changed, but explicit calls don't because they're meant to …
=> Update Popup and DisplayFloat optionsContext from Frontend

.eslintrc.json, ext/bg/js/backend.js, ext/bg/js/context-main.js, ext/bg/js/database.js, ext/bg/js/mecab.js, ext/bg/js/search-main.js, ext/bg/js/search-query-parser.js, ext/bg/js/search.js, ext/bg/js/settings/backup.js, ext/bg/js/settings/dictionaries.js, ext/bg/js/settings/main.js, ext/bg/js/settings/popup-preview-frame-main.js, ext/fg/js/content-script-main.js, ext/fg/js/float-main.js, ext/fg/js/float.js, ext/fg/js/frontend-api-sender.js, ext/fg/js/popup-proxy.js, ext/mixed/js/api.js, ext/mixed/js/core.js, ext/mixed/js/text-scanner.js, test/test-database.js
* Moves `logError` onto `yomichan` object, similar to how `console.error` and related functions are on the `console` object.
* Adds `logWarning`.
* Improves the log function to handle all types of error values, in case something unexpected is received. This can happen when throwing or rejecting promises with non-errors.
* Removes the alert functionality since it is intrusive and rarely used.
* Handles the [`unhandledrejection`](https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event) event.
=> Error logging refactoring

ext/bg/js/search-query-parser.js, ext/bg/js/search.js, ext/bg/js/settings/popup-preview-frame.js, ext/fg/js/float.js, ext/fg/js/frontend.js, ext/mixed/js/display.js, ext/mixed/js/text-scanner.js
This is kind of a follow up of #467, #481, and https://github.com/FooSoft/yomichan/pull/464#issuecomment-618715392. This will likely be a multi-part process, as mentioned in #480. It should make the overall changes easier to digest since there are fewer at once.
This change is intended to begin some refactoring of the `Frontend`, `TextScanner`, and `QueryParser` classes. These are a few of the remaining classes which haven't been covered by #258 yet, so the effort is moving towards that end as well.
* `_getVisualViewportScale` removed and inlined.
This code was only used once, so it wasn't a big deal. Part of the effort of reducing the use of private statics.
* `QueryParser.getMouseEventListeners` implementation updated to match `Frontend`'s.
* `QueryParser.getTouchEventListeners` …
=> Frontend refactor (part 1)

ext/bg/settings.html
Add a link to the flashcard marker definitions on the yomichan homepage in settings.html to help users who are setting up Anki integration.
=> Add helpful link for markers in settings.html

ext/bg/js/search-query-parser.js, ext/bg/js/settings/popup-preview-frame.js, ext/fg/js/frontend.js, ext/mixed/js/text-scanner.js
Follow-up of #484. `QueryParser` still inherits, which can be addressed in the future.
* Simplified `setEnabled` and `setOptions` APIs. `setOptions` now only takes one argument (`options`), and `setEnabled` now only takes one argument (`enabled`).
* Fixed a bug where `QueryParser` would not work when `options.general.enable` was false.
* `onWindowMessage` handler is now added, removed, and tracked by `Frontend`. The change takes place whenever `setEnabled` is changed.
* A few refactorings, including using `Array.push` instead of `concat`, making `Frontend.options` private, and using `.bind` instead of an arrow function.
=> Remove Frontend inheritance

ext/bg/data/default-anki-field-templates.handlebars, ext/bg/js/anki-note-builder.js, ext/bg/js/backend.js, ext/bg/js/options.js, ext/mixed/js/audio-system.js
Download audio binary instead of downloading an `Audio` object and testing its `duration` parameter for validity. This eliminates a redundant download in Anki for a file that has already been downloaded by the web browser.
Resolves #419, and would be necessary for #455. Originally brought up in https://github.com/FooSoft/yomichan/pull/277#issuecomment-552145454.
=> Anki audio download

ext/bg/js/backend.js, ext/mixed/js/api.js
In order to convert [some of the remaining `util*` functions](https://github.com/FooSoft/yomichan/blob/a49e4ccc4e5c7defb30bd88535c18137acf9812c/ext/bg/js/util.js#L69-L83) that use `utilBackend` into `api*` functions, it is necessary to have a mechanism for `api` calls with progress callbacks. This change implements such a mechanism.
The mechanism works using two steps:
1. The frontend sends a request to the backend to open a persistent communication [Port](https://developer.chrome.com/extensions/runtime#type-Port). The backend opens a port and initializes it with a handler map.
2. After the frontend receives this port, it sends an `{action, params}` message to that port. The port `ack`'s the message and then runs the handler. Progress messages are delivered to the port, as well as a …
=> Api invoke with progress

ext/fg/js/popup.js
Fixes some bugs which cause the popup frame to unload when the fullscreen element is changed. The fullscreen element may be reported as an `<iframe>` or an element with a shadow DOM. If the popup frame is parented to one of these elements, it is unloaded. There are potentially others that this could happen on, but his handles a few edge cases in test-document2.html.
This does not handle elements with closed shadow DOMs, as those aren't (supposed to be) detectable. So it is still possible for the frame to unload. However, this issue needs to be addressed eventually for #441 and some other tasks I'm working on.
=> Don't parent the popup frame to elements which cause unload

ext/fg/js/popup.js
If the popup emits an unexpected `load` event, the popup is removed from the page and unloaded. Such events can occur if the popup is unloaded (see: #441, #488), or new content is loaded, such as assigning `src` or `srcdoc`. This should, for the most part, prevent hijacking. Technically it would be even more secure to create a new iframe and forget about the old one, but that's not necessary at this point (and also out of scope for this change).
=> Remove and unload the popup frame if an unexpected load occurs

ext/fg/js/dom-text-scanner.js, test/data/html/test-dom-text-scanner.html, test/data/html/test-stylesheet.css, test/test-dom-text-scanner.js
I am planning on redoing #286 in a more modular manner, and this is the first part. The ability to scan text in a document can be decoupled from the concept of `TextSourceRange` itself. `TextSourceRange` would eventually use this class, but due to the algorithm complexity of scanning the text, I feel it is best to isolate it as much as possible.
This PR does not solve the issue I originally mentioned in https://github.com/FooSoft/yomichan/pull/286#issuecomment-562902190, but it opens the door to supporting both functionalities with an option to toggle between them.
The new `DOMTextScanner` class has the following public API (excluding static helpers):
```js
DOMTextScanner {
constructor(node, offset, forcePreserveWhitespace=false, generateLayoutContent=true);
seek(length);
get node;
get …
```
=> DOMTextScanner

.eslintrc.json, ext/bg/js/profile-conditions.js, ext/bg/js/search.js, ext/bg/js/settings/conditions-ui.js, ext/bg/settings.html, ext/fg/js/frontend.js, ext/mixed/js/core.js, ext/mixed/js/display.js, ext/mixed/js/dom.js, ext/mixed/js/text-scanner.js
Fixes https://github.com/FooSoft/yomichan/issues/412
Adds a new profile condition that lets you specify a modifier key or an exact set of modifier keys that must or must not be pressed in order to activate a profile when scanning.
The set of active modifiers is changed when you move the mouse cursor and press or release Shift, Alt, Ctrl or Meta. If a popup is open when you do this, a boolean is stored that will cause the profile to be updated on the next popup close or scan.
I'm not completely sure about adding support for `Meta` because its support is so inconsistent across browsers. I only tested on Linux, and Chrome was the only browser where it worked. I still have a condition for Firefox/Linux but I'll remove it if I don't find a way to detect if it's pressed when scanning.
The …
=> Modifier key profile condition

ext/bg/data/options-schema.json, ext/bg/settings.html, ext/mixed/js/text-scanner.js
It was added to profile conditions in https://github.com/FooSoft/yomichan/pull/487, so also support it as the scanning modifier key. Same thing applies here, it doesn't work on Firefox, so the option is conditionally hidden.
=> Support meta as scanning modifier

ext/bg/js/conditions.js, ext/bg/js/profile-conditions.js, ext/bg/js/settings/conditions-ui.js
Fixes https://github.com/FooSoft/yomichan/issues/503.
Saves the transformed value of the input as a profile condition instead of the transformed and reversed value. Since the default value changes from `''` to `[]`, all default values have to be isolated.
Can be used in the future by supplying `transformInput` into the descriptor in place of `transform`.
=> Fix modifier key condition data

ext/bg/js/search.js, ext/fg/js/frontend.js
- https://github.com/FooSoft/yomichan/commit/96c137ac166e92b4d69758ebf3f6c5758d074512 fixes a bug introduced in https://github.com/FooSoft/yomichan/pull/500
- https://github.com/FooSoft/yomichan/commit/68cc57c47a64aa0a58052d72e6d37bcaf5e45a0f fixes an issue on Firefox where the search input can stay focused and/or selected while scanning text with QueryParser and the QueryParser text stays unselected. It started happening some time after I updated to version 76, but it could also be some recent change in Yomichan.
=> Text selection fixes

ext/bg/js/backend.js, ext/fg/js/float-main.js, ext/fg/js/float.js, ext/fg/js/popup.js, ext/mixed/js/api.js
This PR changes the way that the popup and frame are initialized. The goal is to remove the use of [`Backend.messageToken`](https://github.com/FooSoft/yomichan/blob/d4ae9aa501ece99ea6c5e6b8fb01c3005f5b7f03/ext/bg/js/backend.js#L76) as the mechanism for ensuring message authenticity. There are two reasons for this:
* Manifest v3 discourages storing state in the service worker, as it will be started/stopped without notice. `messageToken` is effectively a state, and if it's unexpectedly changed, that could have negative consequences. (#455)
* Since the popup can be unloaded, the initialization sequence will need to be re-executed. This could also cause issues with a stale state. (#441)
Follow-up of #488, #490
(Apologies in advance for yet another lengthy description.)
* Adds an …
=> Popup init update

ext/bg/js/backend.js, ext/bg/js/database.js, ext/bg/js/dictionary-importer.js, ext/bg/js/settings/dictionaries.js, ext/bg/js/translator.js, ext/bg/js/util.js, ext/mixed/js/api.js, test/test-database.js
`apiImportDictionaryArchive` and `apiDeleteDictionary` replace `utilDatabaseImport` and `utilDatabaseDeleteDictionary`.
Related: #455
=> Move util database modification functions

ext/fg/js/dom-text-scanner.js, package.json, test/data/html/test-dom-text-scanner.html, test/test-dom-text-scanner.js
* Fixes a test.
* Actually enables the tests.
* Updates `DOMTextScanner._node` to never become `null`, since this can cause issues with how it will be used elsewhere in the code.
* Adds public `remainder` getter.
=> Dom text scanner fixes

ext/fg/js/document.js, ext/fg/js/source.js, test/data/html/test-document1.html
* Fixes a test with a missing parameter.
* Updates `docSentenceExtract` to not rescan text after moving the starting cursor. Instead, it scans bidirectionally away from the initial cursor. (This is related to what I commented on here: https://github.com/FooSoft/yomichan/pull/458#issuecomment-619281704)
* `TextSourceRange.setEndOffset` now has a `fromEnd` parameter to support the above. Since there are many other places using `setEndOffset`, I chose not to change those for now.
=> Text scanning update

ext/bg/js/search-main.js, ext/bg/js/settings/popup-preview-frame.js, ext/bg/settings-popup-preview.html, ext/fg/js/content-script-main.js, ext/fg/js/frontend-api-receiver.js, ext/fg/js/popup-factory.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js, ext/manifest.json
Various refactorings to `PopupProxyHost` and friends.
* Renamed `PopupProxyHost` to `PopupFactory` since that seems to better represent its use.
* Added support for non-async handlers to `FrontendApiReceiver`.
* Made use of `async` more consistent for some `Popup`/`PopupProxy` functions.
* Removed `static` from some private functions.
* Pass `frameId` into `PopupFactory`'s constructor rather than fetching it in `prepare`. All of the current use cases should have a valid `frameId`, so an error is now emitted if something goes wrong.
=> Popup proxy host refactor

ext/bg/js/search-query-parser.js, ext/fg/js/frontend.js, ext/mixed/js/text-scanner.js
* Fixes a bug with missing return value.
* Changes `TextScanner.onSearchSource` to a constructor argument.
* Simplifies `ignorePoints` function; is now optional.
* Groups public functions together.
=> Text scanner refactor

ext/fg/js/frontend.js, ext/fg/js/popup-factory.js, ext/fg/js/popup.js
* Converts private static functions to non-static.
* Adds `prepare`.
* Replaces variables with "container" with "frame" in order to have a more consistent and accurate terminology.
Note: if `prepare` is ever made `async`, this will incur some changes to `PopupProxyHost/PopupFactory.getOrCreatePopup`, since it will have to await in multiple places.
I am also thinking that it might be good to move `_injectStylesheet` into `dynamicLoader`.
=> Popup refactor

ext/bg/background.html, ext/bg/js/backend.js, ext/bg/js/profile-conditions.js, ext/bg/js/settings/conditions-ui.js, ext/bg/js/settings/main.js, ext/bg/js/settings/profiles.js, ext/bg/settings.html, ext/mixed/js/environment.js
Resolves https://github.com/FooSoft/yomichan/issues/504.
Things related to environment are extracted from backend into the `Environment` class because otherwise there would be a circular dependency between `Backend` and `profile-conditions.js`. The dependency issue could be fixed, but the modifier key definitions would probably still be too much bloat for `Backend` so they can be kept in a dedicated class.
I went with key symbols for macOS and names elsewhere, because the usage of the symbols seems so widespread on mac. Some examples (sourced from https://www.nngroup.com/articles/ui-copy/):
There also seems to be an `X` button in the Evernote screenshot, but I didn't add that for any OS yet.
I think it's fine to use `''` as a separator on macOS for now, but this could change in the future …
=> Modifier key platform names

ext/fg/js/popup.js
Resolves #441 and part of #353.
The changes made to the handshake were made with this eventuality in mind, so the final change is just swapping a single line. Effectively an un-revert of 36605f74c3d48a98500d198636112454b36063f6.
=> Load frame content using contentDocument.location.href instead of src attribute

ext/fg/js/frame-offset-forwarder.js, ext/fg/js/popup.js
[`Element.openOrClosedShadowRoot`](https://developer.mozilla.org/en-US/docs/Web/API/Element/openOrClosedShadowRoot) is available to Firefox 63+ in the WebExtension context.
I think this should resolve https://github.com/FooSoft/yomichan/pull/529#issuecomment-626326989.
Note: it is possible to embed the Yomichan `<iframe>` inside of a fullscreen shadow DOM after we have a reference to it, since [`fullscreenElement`](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/fullscreenElement) is available for the shadow root. However, the problem then becomes that the shadow DOM doesn't have client.css (or custom outer CSS), so the popup won't appear. This would have to be solved by putting the `<iframe>` into its own shadow DOM, and give that one the styles. This probably …
=> Use both shadowRoot and openOrClosedShadowRoot

.eslintrc.json, ext/bg/data/default-anki-field-templates.handlebars, ext/bg/js/backend.js, ext/bg/js/handlebars.js, ext/bg/js/options.js, ext/mixed/js/core.js
Fixes https://github.com/FooSoft/yomichan/issues/538. Yet another issue caused by the data format issue of https://github.com/FooSoft/yomichan/issues/337.
=> Fix "tags" template

ext/mixed/js/core.js
There are some times where it would be convenient for `EventListenerCollection` to support different event listener styles, so this adds that. Not used yet, but may be soon.
=> Add support for additional types of event listeners

ext/bg/js/backend.js, ext/mixed/js/comm.js
These new classes are intended to eventually replace `FrontendApiSender`, `FrontendApiReceiver`, and `BackendApiForwarder`. They serve the same need, but they are more robust and general-purpose.
The implementation is very similar as the classes listed above. The main differences are:
* `FrontendApiReceiver` and `FrontendApiSender` are now the same class (`CrossFrameAPI`), and should be a singleton. The reason is that they should share the same port for bidirectional communication.
* Improved error handling for some potential odd edge cases.
* `BackendApiForwarder` is just part of `Backend`.
This will be used to address the following:
* Moving `PopupProxy.getUrl`: https://github.com/FooSoft/yomichan/pull/516#discussion_r421844037
* Providing a more meaningful error if `setTimeout` fails: …
=> Cross frame communication

ext/bg/js/context-main.js, ext/bg/js/search-main.js, ext/bg/js/search-query-parser-generator.js, ext/bg/js/search-query-parser.js, ext/bg/js/search.js, ext/bg/js/settings/anki-templates.js, ext/bg/js/settings/anki.js, ext/bg/js/settings/backup.js, ext/bg/js/settings/dictionaries.js, ext/bg/js/settings/main.js, ext/bg/js/settings/popup-preview-frame-main.js, ext/bg/js/settings/popup-preview-frame.js, ext/bg/js/settings/profiles.js, ext/bg/js/settings/storage.js, ext/fg/js/content-script-main.js, ext/fg/js/float-main.js, ext/fg/js/float.js, ext/fg/js/frame-offset-forwarder.js, ext/fg/js/frontend.js, ext/fg/js/popup.js, ext/mixed/js/api.js, ext/mixed/js/display-generator.js, ext/mixed/js/display.js, ext/mixed/js/dynamic-loader.js, ext/mixed/js/media-loader.js
Converts `api*` functions into a singleton class. This has a few benefits:
* Only need to do one `global api` instead of every single function.
* Will make some unit tests easier, since only `api` will need to be specified. (I've been putting off making some tests for this reason.)
* Removes global private functions.
* Function names now match the `action` string passed to `_invoke`. (Easier to search maybe?)
* State is now stored in a class instance, which should be more logical/consistent than global state variables (`_forwardLogsToBackendEnabled`).
* May be used to store #531's `CrossFrameAPI` instance when that's ready, which would be a stateful variable.
The [first commit](https://github.com/FooSoft/yomichan/commit/9d877b52e7c555ca96cc2616bf242c5af19cc3ba) may be easier to read in …
=> API refactor

ext/bg/js/settings/anki.js, ext/bg/js/settings/main.js, ext/bg/js/settings/profiles.js, ext/bg/settings.html
Cleans up a few things in preparation for some larger refactoring and changes.
* Debug info block is removed since the same data and more can be found by using the backup system.
* Updated some of the controls for options with special handling. This includes some of the Anki settings and `general.enableClipboardPopups` handling.
* This also fixes a bug where the Anki card fields would not be updated when changing the modifying profile.
=> Settings refactor

ext/mixed/js/core.js
Missing `.resolve` and `.reject` when `delay <= 0`.
=> Consistent fields for return value of promiseTimeout

ext/bg/js/backend.js, ext/bg/js/settings/dom-settings-binder.js, ext/mixed/js/api.js, ext/mixed/js/dom-data-binder.js, ext/mixed/js/task-accumulator.js
This change adds some classes to allow automatic binding of DOM input elements to a settings value. This is the framework for #335, and will be used for #465.
This change does not include any updates to the current settings page, as there are some changes required before that can happen (#541).
=> Settings binder

ext/fg/js/content-script-main.js
Since the call is async, technically it's possible to have more than one `PopupFactory` instance created. This can cause an issue with #553, since `CrossFrameAPI` doesn't permit re-registering a handler with the same name.
There are potentially other issues with this system. Since the file needs to be refactored in general, I leave that as a task for another time.
This issue can be reproduced by doing the following:
* Merge #553 
* Add `await promiseTimeout(5000);` to `Backend.prepare()` below https://github.com/FooSoft/yomichan/blob/83a577fa569e5a6d468e3b304313106bba3e1e49/ext/bg/js/backend.js#L144
(This simulates an abnormally long prepare time, which may occur during database upgrades)
* Reload the extension
* Open/reload a webpage during the 5000ms delay
* When the delay is complete, …
=> Ensure single popup factory

ext/bg/background.html, ext/bg/js/anki-note-builder.js, ext/bg/js/backend.js, ext/bg/js/background-main.js, ext/bg/js/database.js, ext/mixed/js/core.js
Since the global object isn't named `window` for service workers, remove the `window.` prefix for some calls on the background page. `document` is also validated for existence before use. `dom.js` is removed from background.html since it isn't used there.
=> Update background global object usage

ext/bg/js/settings/main.js, ext/bg/js/settings/profiles.js
* Converts profile.js content into a class. (whitespace nightmare diff)
* Moves `getOptionsContext` and the current profile index into the main settings file.
Will eventually use #565.
=> Change profile.js into a class

ext/bg/js/backend.js, ext/bg/js/settings/backup.js, ext/bg/js/settings/settings-controller.js, ext/mixed/js/api.js
* Changes how options are overwritten in order to not use `utilBackend`/`utilBackground*` functions.
* Page reload is no longer necessary after settings import.
=> Backup update

ext/bg/js/settings/clipboard-popups-controller.js
No longer uses mutable options references
=> Update how assignment of general.enableClipboardPopups works

ext/bg/js/backend.js, ext/mixed/js/api.js
This change splits up messages sent over the action ports into fragments in order to prevent exceeding the maximum message length.
Fixes #586.
=> Limit action port message size

ext/mixed/js/environment.js
Fixes #595. `chrome.runtime.getPlatformInfo` was generating an error and returning `undefined`.
=> Handle cases where platform info is not available

ext/bg/js/settings/audio.js
Noticed this while testing the Kiwi browser mentioned in #595. The full tag is "ja_JP".
=> Detect language tags starting with "ja_"

ext/fg/js/content-script-main.js, ext/fg/js/frame-offset-forwarder.js, ext/fg/js/popup-proxy.js
* `PopupProxy.setDisabled` is replaced with an event listener.
* The `FrameOffsetForwarder` instance is passed directly to `PopupProxy`'s constructor, rather than a binding to `getOffset`.
* `FrameOffsetForwarder.start` is now `FrameOffsetForwarder.prepare`.
* `FrameOffsetForwarder.onMessage` is now private.
* `FrameOffsetForwarder`'s `window.onmessage` handler no longer throws errors on unexpected values. This happens if the root page uses `window.postMessage` at all, which is the case on Google Docs. (See: https://github.com/FooSoft/yomichan/issues/608#issuecomment-643789813)
=> PopupProxy refactor

ext/fg/js/frontend.js
Unclear how this happened, but I saw the following error occur on Firefox:
```
Yomichan v20.5.22.1 has encountered a problem.
Originating URL: about:blank
Error: Invalid tab
_onApiGetZoom@moz-extension://.../bg/js/backend.js:687:35
onMessage@moz-extension://.../bg/js/backend.js:222:44
```
This change should fix it.
=> Ignore getZoom errors

ext/bg/js/anki-note-builder.js, ext/bg/js/backend.js
This change optimizes the promises used for Anki field formatting to be parallel instead of serial.
=> Optimize Anki note field generation

ext/bg/js/search-main.js, ext/bg/js/search-query-parser.js, ext/bg/js/search.js, ext/bg/js/settings/popup-preview-frame-main.js, ext/bg/js/settings/popup-preview-frame.js, ext/bg/settings-popup-preview.html, ext/fg/js/content-script-main.js, ext/fg/js/float-main.js, ext/fg/js/float.js, ext/fg/js/frontend.js, ext/fg/js/popup-factory.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js, ext/mixed/js/dom.js, ext/mixed/js/text-scanner.js
This PR changes how the frontend and its popups are initialized. All management of popup creation and changing is now controlled by the frontend instance.
* Error wrapping of `prepare` functions is moved into the entry point functions instead.
* `frontendInitializationData` is no longer used for nested popup initialization. `new Frontend(...)` is directly used instead. (Originally set up in #467, #481)
* `getUrl` is no longer part of `PopupProxy`. Instead, it is part of `Frontend`. (https://github.com/FooSoft/yomichan/pull/516#discussion_r421844037)
* Created utility for listening to fullscreen changes, since it is now used in two places.
* `TextScanner` now has a `prepare` function to prevent inadvertent event hooking before the using class is ready. This basically means that …
=> Frontend initialization refactor

ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/settings.html, ext/fg/js/popup.js
Follow-up of #618.
* Throw an error if `this._options` is not ready. If this error occurs, it indicates developer error. This allows the null check to be removed.
* Remove incorrect id from copy-pasted HTML.
* Renamed `unsecurePopupFrameUrl` to `useSecurePopupFrameUrl`, as this naming convention better matches the convention of variables named "enabled" instead of variables named "disabled".
=> Secure popup frame url changes

ext/bg/data/options-schema.json, ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/settings.html, ext/fg/js/frontend.js, ext/fg/js/popup.js, ext/mixed/js/api.js, ext/mixed/js/dynamic-loader.js
Originally mentioned in #292 and https://github.com/FooSoft/yomichan/issues/353#issuecomment-583880562.
This change adds support for wrapping the popup `<iframe>` element inside of a `<div>` with a closed shadow DOM. This should prevent external JavaScript code from being able to detect that Yomichan is present, since the internals are opaque. This should also prevent external code from mistakenly trying to use Yomichan's `<iframe>` for some other purpose (#608). The injected styles should also not be detectable on the root page, since they are individually injected into each shadow DOM.
An option titled "Use shadow DOM container for popup" has been added to the settings page, which is `true` by default.
=> Shadow DOM container for popup iframes

.eslintrc.json, ext/mixed/js/core.js
This function is intended to simplify the pattern of starting a promise and then using the `reject`/`resolve` callbacks later, outside of the promise executor.
=> Add deferPromise function

.eslintrc.json, ext/bg/js/backend.js, ext/bg/js/json-schema.js, ext/bg/js/util.js, ext/mixed/js/core.js, test/dictionary-validate.js, test/schema-validate.js, test/test-schema.js
Add a `clone` function to replace various `isolate` functions. This function skips the JSON stringification/parsing, so it should theoretically be more efficient. The name should also be more clear as to what it is actually doing. "isolation" makes sense when sending values across `window` boundaries, but this functionality is being removed in favor of message passing.
=> Clone function

.eslintrc.json, ext/bg/css/settings.css, ext/mixed/js/core.js, ext/mixed/js/environment.js, ext/mixed/js/yomichan.js
* Removes the `EXTENSION_IS_BROWSER_EDGE` value, which does not work on Chromium-based Edge.
* Moves WebExtension-related setup into yomichan.js.
=> Update browser compatibility and Edge detection

ext/bg/background.html, ext/bg/js/backend.js, ext/bg/js/dictionary-database.js, ext/bg/js/dictionary-importer.js, test/test-database.js
This change renames `Database` to `DictionaryDatabase` in order to give it better semantics. In the future, the `GenericDatabase` class may be used for more features besides storing dictionary information, such as storing logs.
Originally mentioned in https://github.com/FooSoft/yomichan/pull/600#issue-433907630.
=> Rename Database to DictionaryDatabase

ext/bg/background.html, ext/bg/js/database.js, ext/bg/js/dictionary-database.js, test/test-database.js
This change renames `GenericDatabase` to `Database`.
Originally mentioned in https://github.com/FooSoft/yomichan/pull/600#issue-433907630.
=> Rename GenericDatabase to Database

ext/mixed/js/yomichan.js
This caused `yomichan.log` to fail after extension reloading, which makes debugging harder.
=> Fix chrome.runtime.manifest failing when extension is reloaded

ext/fg/js/popup.js
=> Don't use/assign popup private fields without using "this"

ext/bg/js/json-schema.js
=> Make JsonSchemaProxyHandler.unconstrainedSchema public and non-configurable

ext/mixed/js/timer.js
=> Refactor timer privates

ext/fg/js/popup-proxy.js
=> Make PopupProxy._frameOffsetExpireTimeout non-static

ext/bg/js/profile-conditions.js
=> Move private function definitions inside of IIFE

ext/bg/js/search.js, ext/fg/js/float.js, ext/mixed/js/display.js
* Static functions removed so that they can become private.
* Fields made private.
* Functions made private.
* Added a few functions to expose some functionality which used to be accomplished by directly modifying base class fields (which are now private).
* Orphan error handling moved (but needs fixed, see #642).
=> Display refactor

ext/fg/float.html, ext/fg/js/frontend.js, ext/mixed/js/api.js, ext/mixed/js/comm.js, ext/mixed/js/display.js, ext/mixed/js/yomichan.js
First step towards fixing #642. There are additional places where extension unload can be detected/triggered, such as `chrome.runtime.connect`, which are causing unhandled errors. This change unifies the way that the extension unloaded state is stored and accessed.
=> Extension unload detection

ext/bg/js/text-source-map.js
=> Refactor text source map

ext/bg/js/search.js, ext/fg/js/float.js, ext/fg/js/frontend.js, ext/fg/js/popup-factory.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js
* Added "owner" frame ID to `Popup`/`PopupProxy`/`DisplayFloat`.
* Updated `DisplayFloat`'s host frame action invocation to use `CrossFrameAPI`.
This fixes an issue where a few messages sent by Yomichan (`'popupClose'`, `'selectionCopy'`) would be visible to the underlying page (originally mentioned in https://github.com/FooSoft/yomichan/issues/353#issuecomment-587065276). This also fixes an issue where pressing the ESC button will close all popups instead of only the most recent, and the same issue for CTRL+C.
=> Refactor DisplayFloat=>Frontend message passing

ext/fg/js/float.js, ext/mixed/js/display.js
This change converts the key handler map into two different maps.
* The first map is a mapping of `actionName: string => actionHandler: function`, which allows actions to be referenced using a string name.
* The second is a mapping of `key: string => {modifiers: Set, action: string}`, which maps the key/modifier combinations to the action it should perform when pressed.
This separation lays the groundwork for future support for customizable keyboard shortcuts, which will help to solve #653.
=> Refactor hotkey definitions to be more generic

ext/fg/js/frame-offset-forwarder.js, ext/fg/js/frontend.js
* Faster exit if used on the root window.
* Updated iframe selector since the default Yomichan iframe is now embedded in a shadow DOM.
* Function reuse for a `postMessage` call.
* Reply message is only sent to a single frame instead of broadcast to every frame in the tab.
=> Various updates to FrameOffsetForwarder

ext/fg/js/float.js, ext/fg/js/popup.js, ext/mixed/js/comm.js
This change updates the `Popup` => `DisplayFloat` communication use the `api.crossFrame` mechanism instead. This provides an easier callback/return value mechanism for API calls. This results in `DisplayFloat` not listening to window messages, so third-party content won't be able to send messages that interfere.
=> Popup crossFrame communication

ext/bg/js/backend.js
Remove use of `_optionsContext` on the background page, explicitly use the current options instead.
=> Remove backend options context

ext/bg/js/backend.js, ext/mixed/js/api.js, ext/mixed/js/comm.js
Use the port name as a JSON string to pass port usage details, rather than using a string that must be regex parsed. This is used to add support for cross-tab communication in content scripts by reusing the cross-frame communication system.
=> Port name details

ext/bg/js/backend.js, ext/fg/js/float-main.js, ext/mixed/js/display.js, ext/mixed/js/yomichan.js
* Moves `yomichan.ready()` check out of `Display` and into the entry point IIFE.
* Adds `_waitUntilTabFrameIsReady` to the backend.
=> Content script ready checks

ext/bg/js/backend.js, ext/bg/js/context-main.js, ext/bg/js/search-main.js, ext/bg/js/settings/main.js, ext/fg/js/content-script-main.js, ext/fg/js/float-main.js, ext/mixed/js/yomichan.js
* `yomichan.ready` is now `yomichan.backendReady`, which now only waits for the backend to be ready, but does not signal that the frontend is ready.
* `yomichan.ready` is now used to signal that the frontend is ready, which should include web extension event listeners.
=> Script ready state change

ext/mixed/js/comm.js
Prevents a developer issue where if `undefined` is passed, it will forward to the current tab.
=> Force targetTabId to be null if not a number

ext/fg/js/frontend.js, ext/fg/js/popup-factory.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js
`Popup*.showContent` API is refactored to only take two arguments: one which is only `Popup` uses (for external layout and styling), and one which only `Display` uses (for content assignment). This is part of a goal to simplify and standardize the data structure passed to `showContent` and `setContent` functions.
=> Simplify Popup.showContent API to use only two details arguments

ext/bg/js/backend.js, ext/bg/js/search.js
`mode` search parameter was removed in a previous commit, slightly changing behaviour.
=> Fix search popup mode

ext/bg/js/backend.js
Fixes extraneous `?mode=existingOrNewTab` in URL when opening search page.
=> Don't assign mode as a search parameter

ext/bg/js/search.js, ext/fg/float.html, ext/mixed/js/display.js
This change fixes the query parser being reset after scanning it, due to the previous changes to history-driven content updates. This change also makes the query parser part of the core `Display` class, so it can eventually be used on the display page. For now, it is only visible and used on the search page.
=> Query parser fix

ext/bg/js/search.js, ext/bg/search.html, ext/fg/float.html, ext/mixed/css/display.css, ext/mixed/js/display-generator.js, ext/mixed/js/display.js, ext/mixed/js/yomichan.js
* Query parser text assignment moved into core `Display` class.
* Title text assignment moved into `Display` class.
* Adds support for forcing the query parser to be visible or hidden using a URL search parameter.
* Removes the "#" link for kanji search results, as it conflicts with navigation.
* Popup closing moved into `Display`.
=> More display refactoring

ext/mixed/js/display.js
`this._setContentToken` was cleared, so comparison exited. There is not really a good reason to clear this object anymore.
=> Fix _setContentTermsOrKanjiUpdateAdderButtons not working

ext/bg/background.html, ext/bg/js/audio-uri-builder.js, ext/bg/js/backend.js, ext/bg/js/request-builder.js, ext/manifest.json, ext/mixed/js/audio-system.js
Fixes #706.
This change adds the `webRequest` and `webRequestBlocking` permissions, as they are needed to modify the headers. However, according to some docs, these additional permissions should not trigger an additional permissions warning, since I believe they fall under the same category as `<all_urls>`.
The new function `fetchAnonymous` is added in this change, which strips the `Cookie` header and modifies the `Origin` header to match the origin of the URL that is being requested. `AudioUriBuilder` and `AudioSystem` currently use this. The `XMLHttpRequest` changes made in #708 have been reverted to `fetch`.
(Note that there is an extremely unlikely chance for the header modification to affect an external request, but this would require an incredibly unlikely timing exploit that also …
=> Strip request origin

ext/fg/js/float.js
This works in Chrome, but not in Firefox, because the mousedown/mouseup/click/auxclick/pointerdown/pointerup events don't catch mouse buttons 3/4.
=> Add support for history navigation using mouse buttons in the popup window

.eslintrc.json, .gitattributes, .gitignore, build.bat, build.sh, build_zip.sh, dev/build.js, dev/data/manifest-variants.json, ext/manifest.json, package.json, test/test-manifest.js
The intent of this change is to set up build system which is simple yet flexible enough to accommodate future needs ([example](https://github.com/FooSoft/yomichan/pull/612#issue-435533656)). This can hopefully remove the need to have the testing and master branch history be divergent as it currently is; I think the reason behind that is so that the manifest.json metadata can be different on both branches.
I am requesting @FooSoft to review this, as you are in charge of creating and deploying builds. I want to make sure any changes I make will still work for your release workflow, and I can make changes as necessary.
* manifest.json style updated to use standard format as output by `JSON.stringify`, for simplicity. This mainly involved some newline and indentation changes, and the …
=> Build system changes

ext/bg/js/backend.js, ext/bg/js/search.js, ext/fg/js/float.js, ext/mixed/js/display.js
Search popup now has a persistent display mode, which persists across refreshes. Previously, refreshing would cause it to no longer be styled as the search popup.
This will also be used to address a longer-term issue of the backend not being able to store a reference to the window/tab ID of the search popup (due to manifest v3). Therefore, the backend will have to query the tab directly to see if it is the search popup.
=> Persistent display mode

ext/bg/js/query-parser.js, ext/fg/js/frontend.js, ext/mixed/js/display.js, ext/mixed/js/text-scanner.js
Decouples the internal options format used for `TextScanner` and `QueryParser` from the core options object. This makes these classes not store a reference to an options object, but instead only the values of the pertinent options.
=> Query parser text scanner options refactor

ext/bg/js/backend.js, ext/bg/js/dictionary.js, ext/bg/js/translator.js
* `Translator` now uses private functions and fields.
* Removed an unused function.
* Updated usage of exported functions in `dictionary.js` such that only `Translator` uses them. (Eventually these will be merged.)
=> Translator refactor

ext/bg/background.html, ext/bg/js/json-schema.js, test/dictionary-validate.js, test/schema-validate.js, test/test-database.js, test/test-schema.js
* Slightly restructures some of the JSON schema classes so that they can be instantiated, and thus have cached data.
* Adds support for pattern matching using regex. This implementation is technically more flexible than the standard JSON schema's specification, as it supports specifying flags (primarily useful for case-insensitive).
=> Json schema improvements

ext/bg/js/profile-conditions2.js, package.json, test/test-profile-conditions.js, test/yomichan-vm.js
This PR adds base support for profile condition validation using the JSON schema functionality, originally mentioned in https://github.com/FooSoft/yomichan/pull/506#issuecomment-624346263.
The new `ProfileConditions` class has two primary functions:
* `createSchema`, which takes the `profileConditions` structure that profiles use and converts it to a JSON schema.
* `normalizeContext`, which is used to normalize the `optionsContext` value used in the current schema validation. Currently, this just adds a `domain` field, which is extracted from the `url` field (if present).
All other validation is done using the standard JSON schema classes. This should hopefully make maintaining and extending the profile conditions system easier in the future, as the current system is blocking some updates …
=> JSON-schema-based profile conditions

ext/bg/js/backend.js, ext/bg/js/dictionary-importer.js, ext/bg/js/json-schema.js, test/dictionary-validate.js, test/schema-validate.js, test/test-schema.js
* Use `JsonSchemaValidator` instead of static `JsonSchema` class.
* Use private functions.
* Better reuse of `JsonSchemaValidator` for child proxies.
=> JSON schema refactor

ext/fg/js/frontend.js, ext/fg/js/popup-factory.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup.js, ext/mixed/js/display.js
This change updates how popup visibility overrides are handled. Visibility is now tracked using `DynamicProperty`, meaning overrides are handled more flexibly. Additionally, `PopupFactory` can now apply overrides to all popups with a single function call.
Popup visibility changes during screenshots are now applied directly to the owner frame using `api.crossFrame`, meaning that the resulting change can be awaited. In addition, there is an `await` for the next animation frame, which should ensure that the CSS changes are actually applied when creating the screenshot.
Since a broadcast message for the entire tab is no longer used to hide popups, this means that a card being created from a nested popup will capture the parent popup in the screenshot. This should be a better behaviour; …
=> Fix screenshot popup hide

ext/mixed/js/display.js
Fixes #754. [See docs](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage).
=> Fix sessionStorage not being supported when cookies are disabled

ext/bg/background.html, ext/bg/css/settings.css, ext/bg/js/backend.js, ext/bg/js/dictionary-database.js, ext/bg/js/dictionary-importer.js, ext/bg/js/settings/dictionaries.js, ext/bg/js/settings/dictionary-import-controller.js, ext/bg/js/settings/main.js, ext/bg/js/settings/settings-controller.js, ext/bg/settings.html, ext/mixed/js/api.js
This change refactors the dictionary import and purge functionality. The import is now performed directly on the settings page, rather than on the background page, which is necessary for manifest v3. This also removes some of the direct references to the background page, now using `api` functions instead.
This also resolves https://github.com/FooSoft/yomichan/pull/446#discussion_r410917734, since image validation is now performed directly on the settings page.
This change also fixes an issue where `.purge` throwing an exception would put the extension into an invalid state, since the database would be closed.
=> Settings dictionary import refactor

ext/mixed/js/yomichan.js
Fixes `url` being reported as `undefined` for all errors.
=> Fix log context not being in the correct format

ext/bg/js/anki-note-builder.js, ext/bg/js/backend.js, ext/bg/js/template-renderer.js, ext/mixed/js/api.js
Fixes an issue #612 is having, where the value of `marker` is seeing only the last assigned value. This is because pre-#612, the executor is synchronous, and sees the most recent `marker` value. Post-#612 is asynchronous, and will therefore see the last value.
=> Defer assignment of marker when rendering templates

ext/bg/js/request-builder.js
Makes fetchModifyHeaders private, since it's not used publicly.
=> Refactor RequestBuilder slightly

ext/bg/background.html, ext/bg/js/backend.js, ext/mixed/js/api.js
Required for #776. Unfortunately, for Firefox support, this requires the ugly workaround hack to use `document.execCommand('paste');` on the background page. https://bugzilla.mozilla.org/show_bug.cgi?id=1603985
=> Add api.clipboardGetImage

ext/bg/js/settings/keyboard-mouse-input-field.js, ext/bg/js/settings/main.js, ext/bg/js/settings/profile-conditions-ui.js, ext/bg/js/settings/profiles.js, ext/mixed/js/document-util.js, ext/mixed/js/environment.js
* Moves modifier key name detection into frontend rather than the backend, since this is used for user-visible presentation.
* Changes some names of the key modifiers on Mac to use text-representations, to avoid some edge cases in other code:
* `⌥` => `Opt`
* `^` => `Ctrl`
* `⇧` => `Shift`
* `⌘` => `Cmd`
=> Modifier key refactor

ext/bg/js/settings/profiles.js
Since this value should be constant, it only needs to be assigned once
=> Move assignment of the operating system property

ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/settings.html, ext/fg/js/frontend.js, ext/fg/js/popup.js, ext/mixed/js/text-scanner.js
Resolves #742.
~This feature is not yet complete; there is an issue where the popup will close after being hovered because the delay isn't cancelled when the popup is mouseover'd. This event may have to come from the popup itself, since the mouse move events don't fire for the root window when the cursor is in the frame.~
=> Delay hide option

ext/bg/js/anki-note-builder.js, ext/bg/js/backend.js, ext/fg/js/frontend.js, ext/mixed/js/api.js, ext/mixed/js/display.js
Screenshot is no longer generated directly from `Display` classes. Instead, it is generated from `AnkiNoteBuilder`, which is more consistent with audio/clipboard injection. This also removes some redundant marker checking code which was present in `Display`.
=> Anki screenshot refactor

ext/bg/js/anki-note-builder.js, ext/bg/js/backend.js
All media injection is now performed by `AnkiNoteBuilder`, which should help ensure a more consistent API and make it easier to transfer to the `Display` class.
=> Anki media injection move

ext/bg/css/settings.css, ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/js/settings/keyboard-mouse-input-field.js, ext/bg/js/settings/main.js, ext/bg/js/settings/profile-conditions-ui.js, ext/bg/js/settings/scan-inputs-controller.js, ext/bg/settings.html, ext/fg/js/frontend.js, ext/mixed/js/display.js, ext/mixed/js/document-util.js, ext/mixed/js/text-scanner.js
This change generalizes the way that scanning inputs are defined and used. This replaces the options `scanning.middleMouse` and `scanning.modifier` in favor of a generic set of inputs that are required to be included and inputs that are required to be excluded. This allows to require multiple inputs, including both keyboard modifiers and mouse buttons. This change will be expanded upon in the future when support for pointer events is added.
=> Scanning input generalization

ext/bg/js/backend.js, ext/bg/js/settings/anki-controller.js, ext/mixed/js/api.js
This removes the need for some API functions, and should make the Anki server usage more correct, as this uses the correct per-profile options for server/enabled.
=> Update the AnkiController class to use an instance of AnkiConnect directly

ext/bg/js/anki-note-builder.js, ext/bg/js/backend.js, ext/mixed/js/audio-system.js
This is necessary since the `AudioSystem` instance in `Display` doesn't support downloading binary. This must be done via the backend.
=> Generalize AnkiNoteBuilder to not use audioSystem directly

ext/bg/background.html, ext/bg/js/backend.js, ext/bg/js/settings/anki-templates-controller.js, ext/bg/search.html, ext/bg/settings.html, ext/fg/float.html, ext/mixed/js/api.js, ext/mixed/js/display.js
This change moves the usage of `AnkiNoteBuilder` and `TemplateRenderer` into `Display` and `AnkiTemplatesController`. This change is necessary to create the sandboxed iframe with manifest v3 support, since the background page (service worker) will no longer support DOM.
This change supersedes #797; this change does not move `AnkiConnect` usage out of the backend.
=> Use Anki classes directly in Display

ext/bg/css/settings.css, ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/js/settings/scan-inputs-controller.js, ext/bg/settings.html, ext/mixed/js/text-scanner.js
This change adds support for scanning input filters based on which type the input is. The types include `mouse`, `touch`, and `pen`; `pen` is not used currently, but will be once pointer events are supported.
=> Input type filters

ext/bg/js/backend.js, ext/bg/js/json-schema.js, ext/bg/js/options.js, ext/bg/js/settings/backup-controller.js, ext/mixed/js/api.js
This change refactors `OptionsUtil`, moves some functionality from `Backend` into it, and changes how default values are assigned.
Default options values are now assigned directly from the schema, bypassing the upgrade process. This change has the side effect of disabling `scanning.middleMouse` by default, which was mentioned in #479. (This is also partially due to the recent changes in how scanning inputs are defined.)
=> OptionsUtil refactor / options default values

ext/bg/settings.html
* Moves input for `scanning.touchInputEnabled`.
* Makes `scanning.touchInputEnabled` an advanced option.
* Renames `Deep DOM scan` to `Deep content scan`.
=> Settings scanning refactor

ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/settings.html, ext/fg/js/frontend.js, ext/mixed/js/display.js, ext/mixed/js/text-scanner.js
This change adds support for pointer events, which enables custom scanning modifiers for pen devices.
This change works well on Chrome, but has some issues on Firefox, which are presumably browser bugs:
* Pen pointer up/down events register as `touch` events instead of `pen` events. over/out events register correctly as `pen`.
* The above bug also causes the keyboard-mouse input fields on the settings page to not detect pen buttons correctly.
* Pen buttons also are not even detected correctly when buttons are held. On Chrome, they do work as expected.
The events incorrectly registering as `touch` instead of `pen` can probably be worked around, since the `pointerId` is the same for both. This will be done as a separate change later.
Originally mentioned in #267. This feature is disabled by …
=> Pointer events support

ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/js/settings/scan-inputs-controller.js, ext/bg/settings.html, ext/mixed/js/text-scanner.js
This change allows different scanning modifiers to selectively scan kanji, terms, both, or none. The default is both. This option is under the advanced options for the scanning inputs.
Resolves #79. Also mentioned in #267.
=> Add scan dictionary type filters

ext/mixed/js/document-util.js
* Prevents an issue on Firefox where `buttons` might be `-1` for certain pointer events (presumably another bug).
* Exits early when remaining flags are 0.
=> Mouse button modifier update

ext/bg/js/settings/profile-controller.js, ext/bg/js/settings/settings-controller.js
This change refactors the `ProfileController` class to no longer use `utilBackgroundIsolate` or `jQuery`. Functionality should be the same.
=> Profile controller refactor

ext/bg/css/settings.css, ext/bg/js/settings/dictionary-controller.js, ext/bg/js/settings/dictionary-import-controller.js, ext/bg/settings.html, ext/mixed/js/dom-data-binder.js
Refactors `DictionaryController`. The new class should be a bit more simple.
Removes use of `utilBackgroundIsolate` and mutable options; required for #455.
Fixes #302; this feature now requires a user input (new "Check integrity" button).
=> Dictionary controller refactor

ext/bg/background.html
Handlebars is now only used in display and settings pages.
=> Remove unused handlebars script

dev/data/manifest-variants.json, ext/bg/js/settings/anki-templates-controller.js, ext/bg/js/template-renderer-frame-api.js, ext/bg/js/template-renderer-frame-main.js, ext/bg/js/template-renderer-proxy.js, ext/bg/search.html, ext/bg/settings.html, ext/bg/template-renderer.html, ext/fg/float.html, ext/manifest.json, ext/mixed/js/display.js
Follow-up of #574. Implements a sandbox frame for rendering templates. The frame is currently created on the background page, but as with most things, this won't work with manifest v3. This is another intermediate step.
Another point is that apparently the sandboxing feature is not supported in Firefox WebExtensions. This means that in order to fully secure the default `content_security_policy`, there would need to be two versions of the extension: one for Firefox (which keeps the `unsafe-eval` permission on the default `content_security_policy`) and one for Chrome (which uses `sandbox.content_security_policy`).
https://developer.chrome.com/apps/sandboxingEval
=> Handlebars sandbox

ext/bg/js/backend.js, ext/bg/js/settings/dictionary-controller.js, ext/mixed/js/api.js
Moves dictionary deletion into the settings page rather than proxying it through the backend. Not tested, but the previous method could potentially cause issues on Manifest v3 since it's a long-running operation. Dictionary importing is now done on the settings page as well, so it adds parity with that.
=> Dictionary delete improvements

ext/mixed/js/timer.js
Allows it to be used for testing Manifest v3 things.
=> Remove window from performance object access

dev/lint/html-scripts.js, package.json
Validates that script tags are using the expected format and actually point to a valid file.
=> Add lint test to validate <script>s in HTML files

ext/bg/background.html, ext/bg/js/backend.js, ext/bg/js/clipboard-monitor.js, ext/bg/js/clipboard-reader.js, ext/bg/js/search.js
Moves clipboard reading functionality into a separate class. This makes backend.js a bit more organized, and should make it easier to use the functionality in other files, as well as changing the implementation if necessary (manifest v3).
=> ClipboardReader class

ext/bg/js/json-schema.js, ext/mixed/js/cache-map.js, test/test-cache-map.js
This change generalizes how the `CacheMap` class can be used, since there are a few other places where a cache object is used that has code similar to this class.
=> Cache map improvements

dev/data/manifest-variants.json, ext/manifest.json
This change splits builds into four different variants:
* `yomichan-chrome.zip`
* `yomichan-chrome-dev.zip`
* `yomichan-firefox.xpi`
* `yomichan-firefox-dev.xpi`
Differences:
* For the Chrome variants, the default `content_security_policy` has been changed to remove `script-src 'unsafe-eval'`; the sandbox is used instead for template rendering.
* For the Chrome variants, the `applications` entry in the manifest has been removed.
* For Firefox variants, the `applications` entry has been replaced with [`browser_specific_settings`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings). This should be the newer version of the old `applications` entry, supported in Firefox 48+ (our min version is 55). …
=> Browser manifest updates

package-lock.json, package.json
Primarily to be able to test using the `web-ext lint` command, to see to what extent the warnings can be addressed.
=> Add web-ext dev dependency

README.md, ext/bg/data/anki-field-templates-upgrade-v4.handlebars, ext/bg/data/default-anki-field-templates.handlebars, ext/bg/js/anki-note-builder.js, ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/js/settings/anki-controller.js, ext/mixed/js/api.js, ext/mixed/js/display.js
=> Add clipboard-text Anki field

ext/bg/js/backend.js
A bit of cleanup on the backend for better function reuse.
=> Send message updates

ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/mixed/js/document-util.js, ext/mixed/js/text-scanner.js, test/test-options-util.js
* Removes a check that is redundant with the new input settings.
* Updates a primary button check.
* Removes unused function.
=> Scanning mouse button fixes

ext/bg/js/search.js, ext/bg/js/settings/popup-preview-frame.js, ext/fg/js/content-script-main.js, ext/fg/js/float.js, ext/fg/js/frontend.js, ext/mixed/js/display.js
This also makes the page type more explicit, which can be `'web'`, `'popup'`, or `'search'`.
=> Fix page type never being detected as search page correctly

ext/bg/js/settings/scan-inputs-controller.js
Would cause issues when deleting an input group which was not the last, then trying to modify the last one.
=> Fix data-setting attributes not being updated on index change

ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/js/settings/scan-inputs-controller.js, ext/mixed/js/text-scanner.js, test/test-options-util.js
Should be a better organization, as searchTerms/searchKanji are less likely to have any related changes be made.
=> Move searchTerms/searchKanji to front of object definitions

ext/bg/js/deinflector.js, ext/bg/js/translator.js
This change is the first of a set of changes which are intending to make the implementation and behaviour of the `Translator` class more standardized and understandable. This is currently the messiest part of the codebase, which makes adding features and maintenance quite difficult, so it should be cleaned up prior to any significant new features are added to it, such as part of #560.
=> Dictionary data structure improvements

ext/bg/js/backend.js, ext/bg/js/translator.js
Follow-up of #878. This PR changes the options structure used by `Translator` such that it does not depend on the structure of the profile settings object. Instead, it uses a custom structure which is passed as an `options` object. This should improve integrity for options, as there should be no potential that the options can change during an `await` call. Additionally, since this options structure is created once, the default text parsing algorithm should have slightly better performance.
=> Translator options refactor

ext/bg/js/translator.js
This change adds `sourceTerm` to single-part dictionary entries and to the `expressions` array of definition entries. Additionally, `expressions` is now present on all definition entries, and the `source`/`rawSource` of related (sequenced) terms has been adjusted to match the `expression` of those terms.
The addition of `sourceTerm` should provided enough information to support #560 and #559.
=> Translator definition source term (and other info)

ext/bg/js/translator.js
Check would work when the `expression` value is an array, but would not yield the expected results. Instead, just skip the checks for this case.
=> Add check to verify expressions are strings

ext/bg/js/translator.js
Final organization of the `Translator` class. This change is intended to make it easier to find function implementations and have to scroll less between related functionality, as mentioned in #878.
=> Translator organization

ext/bg/js/translator.js, ext/mixed/js/display.js
When possible, in merged mode, select the expression/reading pair that matches the scanned text. Fixes #559.
=> Fix primary audio source

ext/bg/js/translator.js
Issue introduced in #878, 67ed7269472a8d36d9633e0353b39857afebe47e: "Use shared function for creating unused definition entries".
=> Fix incorrect definitions array being used for compatibility merged definitions

ext/bg/js/translator.js
~The 'term' type will be used for compatibility definitions in merged mode. For now, only the comment is updated.~
The definitions are now converted to a consistent `termMerged` type.
=> Update merged definitions to have consistent structure

ext/bg/js/translator.js
* All definitions now have a `dictionaryNames` array field, which contains all of the dictionaries used for the definitions.
* All definitions now have a `dictionary` field, which is the first element of the `dictionaryNames` array. This can be ambiguous, but is kept for backwards compatibility.
* Variables named `title` are changed to `dictionary` for consistency.
* Update pitch accent tag generation to use the `_expandTags`, which normalizes the data.
=> Fix data inconsistencies

ext/fg/js/frontend.js
Using the following steps on Chrome, the tab focus would be changed when changing a settings value:
* Open search page
* Enter query
* Scan a result from that query, opening a nested popup
* Go to options page
* Disable "Enable scanning on search page"
* Search page will be `.focus`'d
This change fixes the issue by making the event passive so that focus is not changed.
=> Fix search page being focused when changing settings

ext/bg/js/query-parser-generator.js, ext/bg/search.html, ext/fg/float.html, ext/mixed/js/display-generator.js, ext/mixed/js/html-template-collection.js
* Renames the class so the name is more clear (compared to `TemplateRenderer`).
* Adds support for loading templates from a HTML node, rather than only from a string.
=> Template handler update

ext/bg/js/settings/modal.js
Since `display` cannot be animated, there is a bit of a workaround using `getComputedStyle`, which is fairly consistent across both Chrome and Firefox.
=> Add support for allowing modals to be display:none when not open

ext/bg/data/options-schema.json
Fixes #917:
> And also old exported setting files don't seem to work on this new version.
=> Fix "modifier" field being required despite being deleted

ext/bg/css/settings.css, ext/bg/js/settings/main.js, ext/bg/js/settings/scan-inputs-controller.js, ext/bg/js/settings/scan-inputs-simple-controller.js, ext/bg/settings.html
This is effectively the old UI, which will show up when advanced mode is not enabled.
Resolves some confusion about the options, e.g. #919.
=> Add simple scan input UI

ext/bg/settings.html, ext/mixed/js/dom-data-binder.js, ext/mixed/js/selector-observer.js
This change creates a reusable `SelectorObserver` class, which is used to observe addition/removal/changes of elements matching a certain selector. Currently, this is used for `DOMDataBinder` (which is where a bulk of the source was copied from), but it will also be used for more functionality on the settings v2 page.
=> SelectorObserver

ext/bg/css/settings.css, ext/bg/js/settings/anki-controller.js, ext/bg/settings.html
Initial refactor of AnkiController, for better support of settings v2 and additional features. For example, it will now be easier to add support for additional card types if necessary (#875).
This also fixes some issues where Anki settings wouldn't all be updated properly when toggling the Anki enabled state; fixes #568.
Also fixes clipboard permissions not being requested when using the `{clipboard-*}` markers; fixes #925.
=> Anki controller refactor

ext/bg/js/json-schema.js, test/test-schema.js
Require properties to exist (via `hasOwnProperty`) before validating their value.
=> Json schema default value improvement

ext/bg/data/options-schema.json, ext/bg/js/anki-note-builder.js, ext/bg/js/anki.js, ext/bg/settings.html
Add support for card duplication check in the root deck and all children, instead of just one specific deck. Resolves #926. Depends on https://github.com/FooSoft/anki-connect/pull/203.
=> Duplicate scope options

ext/mixed/js/display.js
Should improve performance by disabling overlapping calls to card duplicate checks, particularly when Anki calls take a long time. May help for #993.
=> Optimize Anki duplicate checks

ext/fg/js/float.js, ext/fg/js/frontend.js, ext/fg/js/popup.js, ext/mixed/js/display.js, ext/mixed/js/text-scanner.js
This change updates how `optionsContext` is propagated to the popup during the scanning process. `TextScanner` is now in charge of applying the modifiers to the object, and `Frontend` no longer uses them. These options are passed to the `Display` classes, which use them for definitions lookup.
This change enables modifier keys to work for the query parser, which fixes #558.
=> Text scanning options propagation

ext/bg/data/default-anki-field-templates.handlebars, ext/bg/js/anki-note-builder.js, ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/js/settings/anki-templates-controller.js, ext/bg/js/translator.js, ext/mixed/css/display.css, ext/mixed/js/display-generator.js, ext/mixed/js/display.js, test/test-options-util.js
Enabling `compactTags` no longer affects the format of the definitions returned from the backend. Instead, tags are flagged as `redundant`, and these redundant tags are hidden when `compactTags=true`.
=> Compact tags refactor

ext/fg/float.html, ext/fg/js/float.js, ext/mixed/css/display.css, ext/mixed/js/display.js
This is the initial change to set up some new layout for the popup, initially described in #402. With this change, a sidebar will appear when navigation buttons are usable. This sidebar contains the forward/back navigation buttons, and a close button. In the future, the options on this sidebar may be increased to support additional functionality, such as profile selection.
The current style looks as follows:
=> Popup navigation style updates

ext/mixed/css/display.css, ext/mixed/display-templates.html
The current entry indicator style has been updated to use a new colored bar indicator on the left side of the definition entry, as originally described in https://github.com/FooSoft/yomichan/issues/402#issuecomment-596221370. The old indicator is also removed.
This fixes a minor issue where the visibility of the old `＊` indicator would cause a layout change, which could cause a visual jump of text, or affect scroll position when changing the selection.
=> Update selection indicator

ext/bg/js/search.js, ext/fg/js/float.js, ext/fg/js/frontend.js, ext/fg/js/popup.js, ext/mixed/js/display.js
Merges nested popup/frontend setup into the core `Display` class, improving amount of shared code. This also fixes an issue where the first nested popup wouldn't work on the search page when the option `Enable scanning on search page` was `true`, but `Maximum number of additional popups` was `0`.
=> Refactor nested popup/frontend setup

ext/bg/js/query-parser.js, ext/bg/js/search.js, ext/fg/js/frontend.js, ext/mixed/js/display.js, ext/mixed/js/document-util.js, ext/mixed/js/text-scanner.js
* Fixed an issue where scanning selector blacklist would affect webpages rather than Yomichan pages.
* Fixed a title issue (again).
* Fixed an error caused when options weren't assigned yet.
* Fixed some duplicate searches occurring on the search page when changing settings.
* Updated popup content searching using the mouse click to use TextScanner, for improved code re-use.
=> Text scanner improvements

ext/bg/data/options-schema.json, ext/bg/js/anki-note-builder.js, ext/bg/js/options.js, ext/bg/js/settings/anki-templates-controller.js, ext/bg/search.html, ext/bg/settings.html, ext/fg/css/client.css, ext/fg/float.html, ext/fg/js/popup.js, ext/mixed/css/display.css, ext/mixed/css/search.css, ext/mixed/js/display.js, test/test-options-util.js
* Replace `compactGlossaries` option with new `glossaryLayoutMode` option (for supporting more options in the future).
* Simplified some `data-*` attributes (removed `yomichan-` segment).
* Improved some color definitions
* Fixed scrollbar style on the default theme.
=> Popup style updates

README.md, docs/templates.md, ext/bg/data/anki-field-templates-upgrade-v6.handlebars, ext/bg/data/default-anki-field-templates.handlebars, ext/bg/js/anki-note-builder.js, ext/bg/js/settings/anki-controller.js, ext/bg/js/template-renderer.js, ext/mixed/js/japanese.js, test/test-japanese.js
This change adds a new `{frequencies}` marker. Some changes have also been made to the `furigana` and `furiganaPlain` helper functions, in order to support more generalized furigana generation.
Resolves #168, #1073.
=> Frequencies marker

ext/bg/js/settings/popup-preview-frame.js, ext/fg/js/popup.js
`<style>` node does not need to be moved if it is inside a shadow DOM.
=> Fix outer CSS being incorrectly injected

ext/mixed/css/display.css, ext/mixed/display-templates.html, ext/mixed/js/display-generator.js
Frequency tags were being displayed incorrectly for kanji, due to unnecessary disambiguation info.
=> Fix frequency tags

ext/fg/float.html, ext/fg/js/frontend.js, ext/fg/js/popup-factory.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup-window.js, ext/fg/js/popup.js, ext/mixed/css/display.css, ext/mixed/css/popup-outer.css, ext/mixed/js/display.js
The `iframe` no longer uses the `resize` CSS option to control resizing, which was not supported on Firefox. Instead, a new tag element is added to the frame which directly controls resizing.
=> Support frame resize on firefox

ext/bg/js/settings/dictionary-controller.js, ext/bg/js/settings/dictionary-import-controller.js, ext/bg/js/settings/main.js, ext/bg/js/settings2/settings-main.js
`DictionaryController` was missing the `storageController` constructor argument.
=> Fix storage stats update error during dictionary deletion

.eslintrc.json, dev/data/manifest-variants.json, ext/bg/js/backend.js, ext/bg/js/native-simple-dom-parser.js, ext/mixed/js/core.js, ext/sw.js, test/test-sw.js
This PR is not intended to be merged, it is for testing and evaluation purposes only.
The service work can be inspected in Chrome by opening `chrome://serviceworker-internals/` and inspecting the extension's service worker.
The manifest is not enabled by default, it is configured as a new build target: `chrome-mv3`. To update the manifest, run `build --manifest chrome-mv3`.
=> Set up initial manifest v3 support

dev/build.js, dev/data/manifest-variants.json
Allows sw.js to be excluded from non-MV3 builds, among other files in the future.
=> Build exclude files

.eslintrc.json, README.md, dev/build-libs.js, dev/data/manifest-variants.json, ext/bg/js/audio-downloader.js, ext/bg/js/native-simple-dom-parser.js, ext/bg/js/simple-dom-parser.js, ext/bg/legal.html, ext/mixed/lib/parse5.js, ext/sw.js, test/test-sw.js
`DOMParser` is not supported in service workers, so an alternative must be used. [parse5](https://github.com/inikulin/parse5) is used, which is apparently also used for [jsdom](https://github.com/jsdom/jsdom).
[browserify](https://github.com/browserify/browserify) is used to build parse5 to a standalone script that works in the browser. This script is not minified, but that could potentially be done as well.
An abstraction layer called `SimpleDOMParser` is added over the old `DOMParser` and the new `parse5`. This could potentially be used to switch implementations to anything we want without having to modify other code.
---
The new `SimpleDOMParser` is only included for MV3 builds; it and the built parse5 library are excluded from MV2 builds, where they are not used.
=> DOMParser replacement

dev/data/manifest-variants.json, ext/bg/js/backend.js, ext/bg/js/request-builder.js
Required for MV3, since `webRequest` and `webRequestBlocking` aren't supported there.
=> Add support for using declarativeNetRequest

ext/mixed/css/display.css
This selector appears to work in Chrome dev 89 and Firefox 84, but not in Chrome 87, hence why it was not initially detected.
Fixes #1130.
=> Fix invalid CSS :not selector causing frequency tags to display twice

ext/mixed/js/display.js
Fixes an issue mentioned in #1079:
> I think it catches the eye too much (whether it be the color or the "spread" animation when the popup displays).
> I also noticed that the blue bar indicating that the first entry is selected does some kind of "fade in" effect when first opening the popover, which is contributing to it being distracting.
=> Focus the current entry earlier in the generation process

ext/bg/js/translator.js, test/data/test-translator-data.json
Fixes part 2 of #1130:
> I don't know if this is a bug or not (or if it's even new), but it seems tags don't show up unless they are in the top dictionary entry.
=> Update termTags for termGrouped mode to include all definition tags

ext/mixed/css/display.css
Addressing an issue mentioned in #1131:
> Is there an option to change the color/colour of the "popular terms" (P)? The blue on dark is a little difficult to see.
=> Improve the accent color for the dark theme

ext/bg/settings2.html, ext/bg/welcome.html
This option should apply even when modifier keys are in use.
=> Fix description of scanning.autoHideResults setting

ext/mixed/js/display.js
Issue was causing this scanner to not ignore the query parser, which would result in the query parser being overwritten.
Fixes #1152.
=> Fix Display._definitionTextScanner not ignoring certain elements

ext/bg/js/search.js, ext/mixed/js/display.js
* Improves re-search behaviour when settings are updated while a search page is open.
* Fixes an issue mentioned in https://github.com/FooSoft/yomichan/issues/1152#issuecomment-748743633.
=> Improve query parser scanning

ext/bg/settings2.html
Fixes another issue mentioned in #1152.
=> Fix missing data-setting target for scanning.enablePopupSearch

ext/mixed/js/japanese.js, test/test-japanese.js
* Improves performance by about 2x.
* Adds more tests.
* Updates furigana to be visible if the reading is different. This should be a fairly rare case. Example: <br>
<h3><ruby>序<rt>じょ</rt></ruby><ruby>ノ<rt>の</rt></ruby><ruby>口<rt>くち</rt></ruby></h3>
=> Furigana distribution improvements

ext/bg/settings2.html
Since these options are more likely to be configured by the user than some of the other popup options, move scanning options before the popup options.
=> Move scanning options higher up

ext/bg/data/options-schema.json, ext/bg/js/options.js, test/test-options-util.js
Based on feedback in #1079, the default indicator is now smaller, has a more subtle animation, and still does not affect layout when visible.
=> Change popupCurrentIndicatorMode default to triangle

ext/bg/data/options-schema.json
The new default is used for new installations, but will not affect users who already have Yomichan installed.
=> Change global.useSettingsV2 default value to true

ext/bg/js/translator.js, test/data/test-translator-data.json
Exposes a `hasReading` property, which can be used to disambiguate whether a reading was explicitly listed in the source data. #1093
=> Translator frequency data improvements

ext/bg/js/settings/generic-setting-controller.js, ext/bg/settings2.html
Since the select currently only has two options, simplify the display to a toggle.
=> Simplify glossary layout setting

ext/mixed/display-templates.html, ext/mixed/js/display.js, ext/mixed/js/text-scanner.js
This also fixes the underlying issue of #1152/#1153, which was a missing condition checking `TextScanner._includeSelector`.
=> Improve tag scanning behaviour

ext/mixed/css/display.css
`height: 0` was causing the progress bar to be off screen sometimes. Using the new `position: absolute` for `content-scroll` should also be more simple than using a grid layout.
=> Fix some issues with the display layout

ext/bg/css/settings2.css, ext/bg/data/options-schema.json, ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/js/settings2/settings-main.js, ext/bg/js/settings2/translation-text-replacements-controller.js, ext/bg/js/translator.js, ext/bg/settings2.html, ext/mixed/css/material.css, test/data/test-translator-data.json, test/test-options-util.js, test/test-translator.js
Resolves #1195.
Example pattern: `[(]([^)]*)[)]`
=> Translator regex replacements

ext/mixed/css/display.css, ext/mixed/display-templates.html, ext/mixed/js/dictionary-data-util.js, ext/mixed/js/display-generator.js, ext/mixed/js/display-notification.js, ext/mixed/js/display.js
* Updates term tags display to always be shown, even in merged mode. Clicking on tags will show the disambiguation information.
* Improves usability on touch devices, since the term tags are now visible in merged mode. (#354)
* Fixes a layout issue causing an empty newline due to a `display: inline`.
=> Update term tags display and fix a layout issue

ext/bg/js/anki-note-builder.js, ext/bg/js/settings/anki-controller.js, ext/bg/js/settings/anki-templates-controller.js, ext/bg/js/template-renderer-frame-api.js, ext/bg/js/template-renderer-frame-main.js, ext/bg/js/template-renderer-proxy.js, ext/bg/js/template-renderer.js, ext/mixed/js/display.js
Some simplifications and generic-ifications.
=> Refactor anki note building

.eslintrc.json, ext/bg/js/anki-note-builder.js, ext/bg/js/anki-note-data.js, ext/bg/js/template-renderer-frame-main.js, ext/bg/template-renderer.html, ext/mixed/js/display.js
Note data is now generated and mutated in the sandbox frame, rather than in the display frame. This should help keep the definitions clean of unneeded data on the display page, and open the door to improved and easier backwards compatibility if the data format ever needs to be changed.
=> Anki note data abstraction

ext/bg/js/settings/profile-conditions-ui.js, ext/bg/settings2.html
Fixes an issue where it would not be easy to clear keyboard inputs on devices without an escape key/backspace (touchscreen). Also for consistency with other keyboard input fields.
=> Add reset input to profile condition

.eslintrc.json
`void 0` should be used instead.
=> Disable undefined usage

.github/workflows/ci.yml, dev/data/manifest-variants.json
CI build before other tasks was polluting the workarea, causing manifest mismatches to go undetected.
=> Build fixes

ext/fg/js/text-source-element.js
This fixes an issue where `TextScanner.excludeSelector` would not properly ignore images, buttons, etc.
=> Fix TextSourceElement.getNodesInRange not including the element

ext/bg/js/json-schema.js, ext/mixed/js/audio-system.js, ext/mixed/js/cache-map.js, test/test-cache-map.js
Use cases don't require the added complexity of supporting array keys.
=> Simplify CacheMap

ext/bg/data/custom-audio-list-schema.json, ext/bg/data/options-schema.json, ext/bg/js/audio-downloader.js, ext/bg/js/backend.js, ext/bg/js/options.js, ext/bg/settings2.html, ext/mixed/css/material.css, ext/mixed/js/display-audio.js, ext/mixed/js/display.js, test/test-options-util.js
The custom audio URL can now point towards a JSON file, which is parsed for multiple audio URLs. The format of the JSON file is specified in this schema: [custom-audio-list-schema.json](https://github.com/FooSoft/yomichan/blob/master/ext/bg/data/custom-audio-list-schema.json).
Resolves #544.
=> Multiple custom audio sources

dev/data/manifest-variants.json
@FooSoft Let me know if you think we should add this field to the standard `firefox` build target. I assume it won't affect the store deployment since the [Firefox information page](https://extensionworkshop.com/documentation/manage/updating-your-extension/) states:
> Firefox supports automated updates to add-ons using JSON update manifests. Add-ons hosted on addons.mozilla.org (AMO) automatically receive updates to new versions posted there. Other add-ons must specify the location of their update manifests.
Resolves #830.
=> Enable automatic updates for the firefox-dev release

ext/bg/js/settings2/settings-display-controller.js, ext/bg/settings2.html
Helps avoid (part of) an issue where, on Firefox, quickly refreshing the settings page will cause errors. These errors seem to be due to the Browser having stale execution after page refreshing. Disabling the iframe by default will cause less errors; the error can still occur for the other iframe, and potentially on content script pages (though more difficult).
=> Defer load of iframe on the settings page

ext/bg/data/options-schema.json, ext/bg/js/options.js, ext/bg/js/search.js, ext/bg/settings2.html, ext/mixed/js/display.js, test/test-options-util.js
Adds an option `autoSearchClipboardContent` which can be used to disable the immediate lookup of text copied from the clipboard. The query parser is still updated.
Resolves #1311.
=> Clipboard lookup skip option

ext/bg/js/options.js, ext/bg/js/search.js, ext/mixed/js/display.js
The _Clipboard monitor_ option on the search page did not persist properly. The value was written but never read.
=> Fix clipboard monitor not persisting

ext/bg/js/clipboard-monitor.js
Fixes an issue where the search window/query would immediately update after enabling the setting or loading the extension.
=> Don't trigger a change event for the initial content of the clipboard

ext/bg/css/settings2.css, ext/bg/js/settings2/extension-keyboard-shortcuts-controller.js, ext/bg/js/settings2/settings-main.js, ext/bg/settings2.html, ext/mixed/css/material.css
Add a modal to view and configure native keyboard shortcuts. Configuration is only supported on Firefox due to API support.
=> Native keyboard shortcuts settings

.eslintrc.json, ext/bg/background.html, ext/bg/data/anki-field-templates-upgrade-v8.handlebars, ext/bg/data/default-anki-field-templates.handlebars, ext/bg/js/options.js, ext/bg/js/template-patcher.js, ext/bg/settings.html, ext/bg/settings2.html, ext/sw.js, test/test-options-util.js
* Improves `glossary` and `glossary-single` definitions.
* Adds `TemplatePatcher`, which abstracts some of the template patching functionality out of `options.js`. It also supports diff-patch-like replacement tags, as these can be unwieldy to put directly into the source code.
=> Refactor anki field templates

README.md, ext/bg/data/anki-field-templates-upgrade-v8.handlebars, ext/bg/data/default-anki-field-templates.handlebars, ext/bg/js/settings/anki-controller.js, ext/bg/js/translator.js, ext/bg/settings2.html, ext/mixed/js/display-generator.js, test/data/test-translator-data.json, test/test-options-util.js
Having a tag in the data structure is largely redundant, so it is now removed. The display in the popup and functionality of the default templates remains the same. The `{glossary-no-dictionary}` marker has also been added, which outputs the `{glossary}` info without the definition tag.
Resolves #1229.
=> Remove the dictionary tag from the definitionTags

docs/browser-bugs.md
This is a bug that primarily affects the Anki card templates textarea on the settings v2 page, during its initial "fade-in" transition, but may affect other textareas to a lesser extent, such as the custom CSS textareas.
Demo: https://toasted-nutbread.github.io/chrome-textarea-transform-bug/
Report: https://bugs.chromium.org/p/chromium/issues/detail?id=1172666
=> Add info about a textarea display bug

ext/bg/js/permissions-main.js, ext/bg/js/settings/anki-controller.js, ext/bg/js/settings/clipboard-popups-controller.js, ext/bg/js/settings/settings-controller.js
`permissions.request` must be performed during a user interaction on Firefox, so no `await` calls can happen before it's invoked.
=> Permissions requesting fixes

ext/fg/js/frame-ancestry-handler.js
This class is used to return the ancestor frame IDs for the current frame. This is a workaround to using the [`webNavigation.getAllFrames`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webNavigation/getAllFrames) API, which would require an additional permission that is otherwise unnecessary.
Needed for addressing #876.
=> Add FrameAncestryHandler

dev/data/manifest-variants.json, docs/permissions.md, ext/bg/js/permissions-main.js, ext/bg/js/settings/permissions-toggle-controller.js, ext/bg/permissions.html, ext/bg/settings.html, ext/bg/settings2.html, ext/manifest.json
This change has two effects:
* The `nativeMessaging` permission is now optional on Chrome. On Firefox, it is still required because it cannot be optional.
* The permissions page will now automatically update toggles if permissions are changed from another source.
=> Native messaging optional permission

dev/data/manifest-variants.json, ext/bg/popup-preview.html, ext/fg/js/frame-ancestry-handler.js, ext/fg/js/frame-offset-forwarder.js, ext/fg/js/popup-proxy.js, ext/manifest.json, ext/mixed/js/display.js
Window message passing is still used, but a maximum of one message will be sent per frame.
Resolves #876.
=> Refactor FrameOffsetForwarder

ext/bg/js/context-main.js
Full size page will now be displayed when the page is opened in a browser tab vs in the popup.
This improves the display on Kiwi Browser for Android. Firefox for Android already supported this display mode, but it was hard-coded based on the browser name.
=> Improve context page display on mobile

ext/bg/js/backend.js, ext/bg/js/search-main.js, ext/bg/js/search.js, ext/bg/js/settings/popup-preview-frame-main.js, ext/bg/js/settings/popup-preview-frame.js, ext/fg/js/content-script-main.js, ext/fg/js/float-main.js, ext/fg/js/frontend.js, ext/fg/js/popup-factory.js, ext/fg/js/popup-proxy.js, ext/fg/js/popup-window.js, ext/fg/js/popup.js, ext/mixed/js/display.js
Ownership terminology is changed to "content origin", and this value is updated whenever the content is assigned, rather than on the `'configure'` initialization event. This should make the origin more accurately track where the content is coming from, particularly for popups which target the same frame.
=> Improve popup window ownership

ext/bg/js/search-display-controller.js, ext/bg/js/search-main.js, ext/bg/js/search.js, ext/bg/search.html, ext/fg/js/float-main.js, ext/mixed/js/display.js
`DisplaySearch` is now decoupled from `Display`. Dependency injection is used to pass `Display` to `SearchDisplayController` instead. This should make changes and other refactoring easier.
This also fixed an issue with the WanaKana toggle, where it wouldn't turn on/off properly when the options change.
=> Search decouple

ext/bg/js/backend.js, ext/mixed/js/display.js
This allows the search page popup to be detected without previously knowing what the tab ID is. This will be necessary when using MV3, since the service worker can be unloaded, losing state.
=> Improve search page popup detection

ext/bg/js/backend.js
This value is not (currently) used, it is primarily for debugging.
=> Fix cross frame communication not exposing sourceTabId properly

docs/browser-bugs.md
The following bugs have the potential to affect the extension, primarily in MV3 mode:
1. https://bugs.chromium.org/p/chromium/issues/detail?id=1178179
This bug can cause the browser to crash when using ports; discovered while looking into the port disconnection issues below.
2. https://bugs.chromium.org/p/chromium/issues/detail?id=1178188 (MV2)
https://bugs.chromium.org/p/chromium/issues/detail?id=1178189 (MV3)
These are bugs related to `Port.onDisconnect` not firing properly. Separate issues for both manifest versions 2 and 3 since they exhibit different behaviour.
These issues cause the cross-frame/cross-tab communication system to break if the background page or service worker is reloaded or stopped, since the `Port.onDisconnect` event is not fired.
=> Add information about communication port bugs

ext/js/app/content-script-main.js, ext/js/background/background-main.js, ext/js/comm/api.js, ext/js/display/popup-main.js, ext/js/display/search-main.js, ext/js/pages/action-popup-main.js, ext/js/pages/info-main.js, ext/js/pages/permissions-main.js, ext/js/pages/welcome-main.js, ext/js/settings/main.js, ext/js/settings/pitch-accents-preview-main.js, ext/js/settings/popup-preview-frame-main.js, ext/js/settings/settings-main.js, ext/js/yomichan.js
`api` and `yomichan` preparation is more consistent.
=> Api prepare refactor

.eslintrc.json, ext/js/app/frontend.js, ext/js/background/backend.js, ext/js/comm/cross-frame-api.js, ext/js/core.js, ext/js/display/display.js, ext/js/display/search-display-controller.js, ext/js/yomichan.js
Move function definitions and refactor single-use functions.
=> Cleanup yomichan api

ext/js/input/hotkey-handler.js
For now, disable forwarding. A better forwarding implementation can be implemented later.
=> Fix copy hotkey not working

ext/css/display.css, ext/css/material.css, ext/css/search.css, ext/css/settings.css, ext/settings.html
Button styles are now primarily configured using CSS variables, to account for the fact that [handling `:focus-visible` backwards compatibility is a disaster](https://github.com/FooSoft/yomichan/pull/1426).
=> Improve button styles

ext/js/dom/document-util.js
On Firefox, [`caretPositionFromPoint`](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/caretPositionFromPoint) will return the entire element instead of the text within the element.
Fixes #1435.
=> Fix user select all handling

ext/css/display.css, ext/data/schemas/options-schema.json, ext/display-templates.html, ext/js/data/options-util.js, ext/js/display/display-generator.js, ext/js/display/display.js, ext/settings.html, test/test-options-util.js
Adds options for configuring how frequency information is displayed.
1. [tags](https://user-images.githubusercontent.com/11037431/109079045-58ca7000-76cc-11eb-86f8-44335e13b05a.png) (old style)
2. [tags-grouped](https://user-images.githubusercontent.com/11037431/109079086-6849b900-76cc-11eb-99ad-ee6272c19b43.png) (new)
3. [split-tags](https://user-images.githubusercontent.com/11037431/109079106-71d32100-76cc-11eb-9659-fbecffb00112.png) (new)
4. [split-tags-grouped](https://user-images.githubusercontent.com/11037431/109079128-7b5c8900-76cc-11eb-9ced-165489468481.png) (new, default)
5. [inline-list](https://user-images.githubusercontent.com/11037431/109079153-84e5f100-76cc-11eb-9f9a-50e6651126b3.png) (current style, compact layout)
6. …
=> Improve frequency display

ext/js/language/translator.js
Dictionary priority should be more intuitively used now. Addresses point 2 from this comment: https://github.com/FooSoft/yomichan/issues/1340#issuecomment-780242587
=> Improve dictionary priority

ext/css/display.css, ext/data/schemas/options-schema.json, ext/display-templates.html, ext/js/data/options-util.js, ext/js/display/display-generator.js, ext/js/display/display.js, ext/settings.html, test/test-options-util.js
This is similar to how some other extensions display info, so adding an option for it. It can make it easier to scan the reading, without requiring reading tags to be enabled.
Related: https://github.com/FooSoft/yomichan/issues/1408#issuecomment-781700075
=> Add standalone reading

ext/js/background/backend.js
Definitions that return a single non-Japanese character are skipped.
Old:
New:
=> Fix a poorly handled edge case of the scanning parser

ext/js/language/translator.js
Fetching and grouping of definitions in merge mode should now be significantly more efficient. There are less separate database queries, less redundant searches, and more early exits. The code should also be more organized and a bit easier to follow.
=> Refactor translator merged mode

ext/js/dom/dom-text-scanner.js, ext/js/dom/text-source-element.js
Youtube separates certain characters in closed captions with `&ZeroWidthSpace;` (`'\u200b'`). This is similar to how Google Docs separates with `&zwnj;` (`'\u200c'`).
=> Remove zero-width space

docs/browser-bugs.md
The new issue is exhibited with the new layout for frequency tags on Firefox when using the `inline-list` format and the following custom CSS is enabled:
```css
.frequency-disambiguation::before,
.frequency-disambiguation::after {
content: none;
}
```
The result is tags wrapping incorrectly and a "jumping" behaviour when they are hovered using the dev tools inspector.
=> Update browser bug list

ext/js/background/backend.js, ext/js/language/translator.js, test/data/test-translator-data.json
Corrects a slight change in behaviour introduced in #1456. The issue is that dictionary index and priority can't be used as part of the same comparison; index comparison should come (nearly) last.
=> Split dictionary order and index sorting

ext/js/app/frontend.js, ext/js/display/display-resizer.js, ext/js/display/display.js, ext/js/display/popup-main.js, ext/popup.html
Move display resizer functionality into a separate class. This improves the modularity of the `Display` class and allows the resizer functionality to be omitted from the search page, where it isn't used.
=> Separate display resizer

ext/js/language/japanese-util.js, test/test-japanese.js
Fixes case where `reading.startsWith(expression) && reading.length > expression.length`. Spotted in some definitions from Kenkyuusha.
=> Fix furigana distribution when reading starts with expression, but has remainder characters

ext/js/display/display-generator.js, ext/js/language/dictionary-data-util.js, ext/js/language/japanese-util.js, ext/js/language/translator.js, ext/js/media/audio-downloader.js
Empty reading means that the reading is the same as the expression. Instead of handling this edge case in many different places, only handle it once: during the conversion from database definition to a translator definition.
Mentioned in https://github.com/FooSoft/yomichan/issues/1472#issuecomment-791877947.
=> Improve empty reading handling

ext/js/media/audio-downloader.js
Follows #1497. Additionally updated to use `URLSearchParams` instead of manual string generation.
=> Update audio downloader

ext/js/language/deinflector.js, ext/js/language/translator.js
`Deinflector` no longer adds fields that are only used by `Translator`. `Translator` is in charge of constructing these fields.
=> Deinflector refactor

ext/display-templates.html, ext/js/data/anki-note-data.js, ext/js/display/display-generator.js, ext/js/language/translator.js, ext/js/templates/template-renderer-frame-main.js, test/data/test-translator-data.json
Removes some fields that are derived from other fields. This should help reduce the amount of data that needs to sent via the messaging system when looking up definitions.
As an example of the difference, `test/data/test-translator-data.json` was reduced by ~3000 lines.
=> Refactor furigana segment data

ext/js/data/anki-note-data.js, ext/js/display/display-generator.js, ext/js/language/dictionary-data-util.js, ext/js/language/translator.js, test/data/test-translator-data.json
Removes some fields that are derived from other fields. This should help reduce the amount of data that needs to sent via the messaging system when looking up definitions.
As an example of the difference, `test/data/test-translator-data.json` was reduced by ~139 lines.
=> Refactor term frequency data

ext/js/language/japanese-util.js, test/test-japanese.js
Fixes #1509. `distributeFuriganaInflected` did not properly handle cases where the source matches the reading instead of the expression.
Prior to #1496, this only incidentally seemed to work. The bug that was fixed in that commit was causing an _apparently_ correct,  but still broken, behaviour of this function.
=> Fix incorrect furigana distribution

ext/js/language/translator.js
Fixes an issue mentioned in https://github.com/FooSoft/yomichan/issues/1472#issuecomment-794987642.
=> Fix sorting of non-top-level definitions

ext/js/language/dictionary-database.js
The index doesn't need to be added to the resulting values, since it's already known based on the array index.
=> Simplify _findFirstBulk

dev/data/manifest-variants.json, dev/database-vm.js, dev/vm.js, ext/js/language/dictionary-importer.js, ext/js/media/media-loader.js, ext/js/media/media-util.js, ext/manifest.json, ext/popup.html, ext/search.html
Content security policy was blocking `data:` images from being validated during initial import. `blob:` is now consistently used for all images and has been added to the CSP.
=> Fix dictionary image support

ext/data/deinflect.json, test/test-deinflector.js
Mentioned in #1545, but there was actually no rule for it yet.
=> Shimau inflection

ext/js/language/dictionary-data-util.js
This would occur for certain words with the same reading, such as あああ. Would show up as _(あああ, あああ only)_.
=> Remove repeated disambiguations

ext/js/data/anki-note-builder.js, ext/js/templates/template-renderer-frame-api.js, ext/js/templates/template-renderer-frame-main.js, ext/js/templates/template-renderer-proxy.js, ext/js/templates/template-renderer.js, test/test-anki-note-builder.js
This change optimizes the template rendering process by batching data together before sending to the rendering frame. This can result in an improvement of nearly 100x reduction of total data transmission. Metrics based on a test with many dictionaries installed and many Anki card fields:
* 21.2.28.2 - 53,317,095 (prior to Translator data refactoring)
* 21.3.31.0 - 23,957,117
* After this change - 240,763
The value is the sum of the lengths of all `JSON.stringify(data)` passed to the rendering frame, for a single lookup of 日本語. The values were calculated from this patch:
```patch
diff --git a/ext/js/templates/template-renderer-frame-api.js b/ext/js/templates/template-renderer-frame-api.js
index dd6be5173..b80c3a264 100644
--- a/ext/js/templates/template-renderer-frame-api.js
+++ …
```
=> Optimize template renderer

docs/interfaces/dictionary-entry.ts, ext/js/data/anki-note-data-creator.js, ext/js/language/translator.js, test/data/translator-test-results-note-data1.json, test/data/translator-test-results.json
`sequence` is now exposed on the new format for merged definitions, as well as a new `sequenceDictionary`. For the Anki note data, the `sequence` is exposed on the root `definition`, as well as the child `definitions` array.
Fixes an issue mentioned in https://github.com/FooSoft/yomichan/issues/1580#issuecomment-812904279.
=> Improve term dictionary entry sequence

ext/js/display/search-main.js, ext/js/dom/document-focus-controller.js
Appears to be a race condition, as manually `.focus()`ing an element prevents autofocus. Fixes #1595.
=> Fix autofocus sometimes not working on the search page

ext/css/settings.css, ext/js/background/backend.js, ext/js/background/environment.js, ext/js/media/audio-system.js, ext/js/pages/action-popup-main.js, ext/js/pages/settings/audio-controller.js, ext/js/pages/settings/settings-main.js, ext/settings.html
Some updates to fix some obvious errors that occur on Safari.
#986
=> Initial safari compatibility

ext/js/data/anki-note-data-creator.js, ext/js/language/translator.js, test/data/translator-test-results-note-data1.json, test/data/translator-test-results.json
This data is now redundant, as it can be derived from the `sequence` field of definitions.
Mentioned in https://github.com/FooSoft/yomichan/pull/1616#issuecomment-822053762
=> Remove redundant dictionary entry sequence

ext/js/pages/settings/permissions-origin-controller.js
`childNodes` includes all nodes, `children` only includes elements.
=> Use childNodes instead of children

ext/css/display.css, ext/data/schemas/options-schema.json, ext/display-templates.html, ext/js/background/backend.js, ext/js/comm/anki.js, ext/js/comm/api.js, ext/js/data/options-util.js, ext/js/display/display.js, ext/js/pages/settings/anki-controller.js, ext/settings.html, test/test-options-util.js
This PR adds a small button next to the "add card/view added card" button on the display template. This button will only appear if:
1. The word has an anki card.
2. That card has tags.
3. At least one of those tags is not in the "Card tags" anki setting.
This button does nothing when clicked, but instead when hovered over will show a tooltip with all of the custom tags that belong to this card:
This PR would solve issue #1626. This feature would help my workflow, as I tend to add cards that I want to later edit or fix if/when I find a better context for them. I go into more details of my workflow in the issue.
There are a few things that still need to be considered:
- I'm not sure about code style/conventions/the way I'm handling data in `backend.js`. Particularly how I'm accessing user …
=> Show any custom tags on words that have anki cards created

ext/js/dom/dom-text-scanner.js
The spelling with the "i" is the more common. Originally mentioned here: https://github.com/FooSoft/yomichan/pull/1628#discussion_r623548994
=> Replace collapsable with collapsible

ext/js/background/profile-conditions-util.js, ext/js/display/search-display-controller.js, ext/js/pages/settings/profile-conditions-ui.js, test/test-profile-conditions-util.js
Adds a new _Flags_ profile condition, which can be used to filter based on certain context flags. Currently, the only flag is the `clipboard` flag, which is present when text is copied from a clipboard monitor.
Originally mentioned here: https://github.com/FooSoft/yomichan/issues/1504#issuecomment-828881413
=> Flags profile conditions

docs/interfaces/dictionary-entry.ts, ext/js/data/anki-note-data-creator.js, ext/js/language/translator.js, test/data/translator-test-results.json
Definitions are now grouped without requiring a unique sequence.
Fixes an issue mentioned in https://github.com/FooSoft/yomichan/issues/1642#issuecomment-835347719.
=> Improve term grouping

ext/css/settings.css, ext/settings.html
Broke due to shared class names with the dictionary options.
=> Fix secondary search dictionary options layout

ext/js/pages/settings/dictionary-controller.js
Removes some node/selectors that were previously used to support the old settings page.
Fixes #1657.
=> Fix invalid node/selectors being used in the dictionary delete process

ext/settings.html
=> Restore the Anki on macOS warning from the old settings page

ext/js/language/translator.js, test/data/translator-test-results-note-data1.json, test/data/translator-test-results.json
Updates grouped `sourceTermExactMatchCount` to be based on the number of headwords instead of the number of definitions.
Resolves #1668.
=> Improve source term exact match count

ext/js/display/search-display-controller.js, ext/js/display/search-main.js, ext/js/display/search-persistent-state-controller.js, ext/search.html
This makes the logic run earlier and easier to reuse in other components.
=> Add SearchPersistentStateController

ext/js/display/display-generator.js
This has been supported by the schema, but wasn't properly handled for display.
=> Add support for custom text type generation

ext/js/display/display-generator.js
Turns out this is unnecessary because the internal format is different.
=> Revert "Add support for custom text type generation (#1683)"

ext/css/display.css, ext/data/schemas/dictionary-term-bank-v3-schema.json, ext/js/display/display-generator.js, ext/js/language/dictionary-importer.js, test/data/dictionaries/valid-dictionary1/term_bank_1.json, test/test-database.js
This PR adds a new type of definition: `"structured-content"`. This can be used to generate a limited subset of HTML tags, currently including `<img>`, `<ruby>`, `<rt>`, and `<rp>`.
See file `test/data/dictionaries/valid-dictionary1/term_bank_1.json` for an example.
Resolves #1652.
Resolves #1655.
=> Add support for definitions with structured content

ext/js/app/frontend.js, ext/js/display/display.js, ext/js/display/query-parser.js, ext/js/language/text-scanner.js
Some general improvements to the event flow for selection clearing. `TextScanner` now sends a `'clear'` event, which clients are responsible for responding to and actually calling `clearSelection`. This allows other logic to be added before the `clearSelection` invocation.
=> Selection clear improvements

docs/browser-bugs.md
* **Focus changes don't preserve caret position for caret browsing**
https://bugs.chromium.org/p/chromium/issues/detail?id=1211175
This is what is causing the issue in https://github.com/FooSoft/yomichan/issues/1627#issuecomment-835886794
* **CSS :active state on &lt;label&gt; element doesn't match state on inner element**
https://bugs.chromium.org/p/chromium/issues/detail?id=1211182
This is an issue detected a while ago when setting up some CSS rules which resulted in some duplicate rules being necessary.
=> Update browser bugs

ext/css/display.css, ext/data/schemas/dictionary-term-bank-v3-schema.json, ext/js/display/display-generator.js, ext/js/language/dictionary-importer.js, test/data/dictionaries/valid-dictionary1/term_bank_1.json
Adds support for specifying the preferred width/height in `em` units.
Resolves https://github.com/FooSoft/yomichan/issues/1652#issuecomment-844670154
=> Structured content image size units

ext/js/app/popup.js, ext/js/comm/frame-client.js, test/data/html/test-document2.html
Passively handles the error that occurs when trying to show a popup in a sandboxed iframe without `"allow-same-origin"`. Also adds a test.
Mentioned in #1702.
=> Improve support for sandboxed iframes

ext/js/display/display-audio.js
=> Fix incorrect selector causing invalid headword index to be used

ext/js/data/json-schema.js, test/test-json-schema.js
Basic `$ref` support added for validation of dictionary structured content (#1689).
=> Json schema ref support

ext/js/media/audio-system.js
Refactored while testing an issue on Chrome where `createAudio` sometimes stalls and never returns or errors when audio is auto-played. Interestingly, the audio will play if the `audio` object is kept alive by any means, such as logging it to console or assigning it to `window`. Note: this change does _not_ fix the issue, but makes it easier to debug certain parts.
=> Simplify createAudio function

dev/translator-vm.js, ext/js/background/backend.js, ext/js/language/translator.js
This allows a main dictionary to be selected for grouping, but excludes definitions and other content from that dictionary if it is not enabled. This allows one dictionary to be used for grouping related terms (e.g. JMDict) while only showing definitions from other dictionaries (e.g. a J2J dictionary without sequencing information).
Resolves https://github.com/FooSoft/yomichan/issues/1546#issuecomment-808729383
=> Add support for definitionless main dictionary

ext/js/language/translator.js
Secondary definitions are now searched using the source term as well, since there are cases where "inconsistent" results could show up. For example, see https://github.com/FooSoft/yomichan/issues/1580#issuecomment-813118330.
=> Improve secondary definitions

ext/js/language/translator.js, test/data/translator-test-results.json
Sorting now takes place after all data has been populated. This will allow for more sorting options in the future, such as using frequency information for sorting.
=> Translator sorting updates

.eslintrc.json
Treat it as a generalized file, same as `dictionary-data-util.js`.
=> Update eslint rules for structured-content-generator.js

ext/js/templates/template-renderer-frame-api.js, ext/js/templates/template-renderer-proxy.js
This should help ensure that the template renderer isn't used before the scripts on the page have fully loaded.
=> Template renderer init update

ext/template-renderer.html
The main script must run last, and the scripts must be in alphabetical order. The main script was only coincidentally the last alphabetically.
=> Add separation before template-renderer-frame-main.js

ext/css/display.css, ext/css/structured-content.css, ext/data/structured-content-style.json, ext/js/display/structured-content-generator.js
Resolves 4 and 5 of #1767.
To assign a max height for images, use the CSS:
```css
.gloss-image-container { max-height: /* height */; }
```
=> Update CSS rules for images

dev/patch-dependencies.js, package.json, test/test-jsdom.js
This script patches a bug in [jsdom](https://github.com/jsdom/jsdom), which uses [nwsapi](https://github.com/dperini/nwsapi), and adds a test to verify the patched version doesn't throw an error.
=> Add a script to patch bugs in dependencies

ext/js/data/anki-note-builder.js, ext/js/display/display.js, ext/js/pages/settings/anki-templates-controller.js, test/test-anki-note-builder.js
`{note, errors}` is now the return value rather than just `note`. This provides a more consistent API for returning the errors.
=> Refactor createNote

ext/js/display/display-anki.js
This change updates `DisplayAnki` to store note details for each dictionary entry, rather than them being stored in a temporary variable before being discarded. This will allow this information to be reused for certain functionality in the future.
=> Store anki note details

README.md, ext/data/templates/anki-field-templates-upgrade-v13.handlebars, ext/data/templates/default-anki-field-templates.handlebars, ext/js/data/anki-note-builder.js, ext/js/data/options-util.js, ext/js/display/display-anki.js, ext/js/display/display.js, ext/js/pages/settings/anki-controller.js, ext/js/pages/settings/anki-templates-controller.js, ext/js/templates/template-renderer-media-provider.js, ext/settings.html, test/data/anki-note-builder-test-results.json, test/test-anki-note-builder.js
Adds support for generating furigana for arbitrary text. This is an async process, so the furigana content will only be available when the card is being created, not when it's being tested for whether or not it can be added.
Adds marker `{sentence-furigana}`.
Resolves #153.
=> Anki text furigana parsing and {sentence-furigana} marker

ext/js/display/display-anki.js
Error used to appear if audio was requested but was not available for the term, which is a valid use case. Similar for clipboard images.
=> Improve error when card has missing content

ext/display-templates.html, ext/js/display/display-anki.js
This change enables a popup which shows all available note IDs when right clicking / shift clicking the _View Note_ button. Additionally, a small "+" badge will be shown if multiple notes are available. This is very similar to the functionality of the audio button.
=> Multi view note

docs/interfaces/dictionary-entry.ts, ext/css/display.css, ext/data/schemas/dictionary-term-meta-bank-v3-schema.json, ext/js/display/display-generator.js, ext/js/language/dictionary-data-util.js, ext/js/language/translator.js, test/data/dictionaries/valid-dictionary1/term_meta_bank_1.json, test/data/translator-test-results.json, test/test-database.js
This change adds support for devoiced and nasal characters in dictionary pronunciation info. [term_meta_bank_1.json](https://github.com/toasted-nutbread/yomichan/blob/99a593bcf865297dec2f2fdeb9841e0dd9f14067/test/data/dictionaries/valid-dictionary1/term_meta_bank_1.json#L45-L74) contains examples of the data format.
Addresses part of #1824.
=> Devoice and nasal pronunciation info

ext/css/display-pronunciation.css, ext/js/display/pronunciation-generator.js, ext/js/language/japanese-util.js
This change removes the diacritic from the mora so that there isn't a conflicting dakuten+handakuten. Additionally, a hidden handakuten has been added, which will be present when copy-pasting the text.
Resolves part of https://github.com/FooSoft/yomichan/pull/1832#issuecomment-881873410.
Related: #1824
=> Pronunciation nasal improvement

dev/translator-vm.js, ext/js/templates/sandbox/anki-template-renderer.js, ext/js/templates/sandbox/template-renderer-frame-main.js, ext/js/templates/sandbox/template-renderer.js, ext/template-renderer.html, test/test-anki-note-builder.js
This should make it easier and more organized to extend Anki template rendering functionality. It also creates a distinction between the `TemplateRenderer` (generic) and the `AnkiTemplateRenderer` (Anki-specific functionality). This would allow for other types of template rendering sandboxes if ever necessary.
=> Anki template renderer abstraction

docs/templates.md, ext/js/display/display-generator.js, ext/js/display/sandbox/pronunciation-generator.js, ext/js/dom/sandbox/css-style-applier.js, ext/js/templates/sandbox/anki-template-renderer.js, ext/template-renderer.html, test/test-anki-note-builder.js
This change adds a new `pronunciation` helper for generating HTML to display pronunciation info in Anki templates. This change does not replace the existing template or add support for nasal/devoice positions, which will be done in a future commit.
Related: #1824.
=> Pronunciation template helper

.eslintrc.json, ext/js/language/dictionary-importer-threaded.js, ext/js/language/dictionary-importer-worker-main.js, ext/js/language/dictionary-importer-worker-media-loader.js, ext/js/language/dictionary-importer-worker.js, ext/js/pages/settings/dictionary-import-controller.js, ext/settings.html, ext/welcome.html, test/test-workers.js
This change updates the dictionary importer to be run on a separate worker thread. This should improve the responsiveness of the browser during long-running steps, such as validation.
See: https://github.com/FooSoft/yomichan/issues/1853#issuecomment-888656712
=> DictionaryImporterThreaded

dev/translator-vm.js, ext/js/language/dictionary-importer-threaded.js, ext/js/language/dictionary-importer-worker.js, ext/js/language/dictionary-importer.js, ext/js/pages/settings/dictionary-import-controller.js, test/test-database.js
Updates to progress callback. `DictionaryImporter` should generally only be used for importing a single dictionary, and not reused.
=> Dictionary importer refactoring

.eslintrc.json, dev/data/manifest-variants.json, ext/data/schemas/options-schema.json, ext/js/accessibility/google-docs.js, ext/js/background/backend.js, ext/js/data/options-util.js, ext/js/document-start.js, ext/manifest.json, ext/settings.html, test/test-options-util.js
This change adds an option to force Google Docs to render using HTML rather than `<canvas>`. See #1670 for details.
https://workspaceupdates.googleblog.com/2021/05/Google-Docs-Canvas-Based-Rendering-Update.html
Resolves #1670.
=> Google Docs accessibility

docs/browser-bugs.md
Data added to the database from a Worker thread does not persist if the Worker is terminated.
https://bugs.chromium.org/p/chromium/issues/detail?id=1237686
https://bugzilla.mozilla.org/show_bug.cgi?id=1724602
Originally pointed out in https://github.com/FooSoft/yomichan/issues/1869#issuecomment-892243316
=> Update browser bugs with info about IndexedDB usage in a Worker

ext/js/data/database.js, ext/js/language/dictionary-database.js, ext/js/language/dictionary-importer.js
The `transaction.oncomplete` event should be used to determine when data has been fully added to the database rather than `request.onsuccess`.
This is the actual fix to https://github.com/FooSoft/yomichan/issues/1869#issuecomment-892243316 / #1877.
=> Database improvements to data persistency

ext/js/language/dictionary-database-modifier.js, ext/js/language/dictionary-worker.js, ext/js/pages/settings/dictionary-controller.js, ext/settings.html, ext/welcome.html
Dictionary deletion is now performed on a worker thread. This should improve browser responsiveness during deletion.
Resolves #1864.
=> Threaded dictionary delete

ext/js/pages/settings/dictionary-controller.js
Order wasn't the same as settings order.
Fixes #1905.
=> Fix incorrect dictionary name ordering being used for counts

ext/js/background/backend.js, ext/js/comm/api.js, ext/js/language/dictionary-worker-handler.js, ext/js/language/dictionary-worker.js, ext/js/pages/settings/dictionary-controller.js
Dictionary database counting is now performed on a worker thread rather than on the backend, since it is a long-running operation.
=> Dictionary worker updates

ext/action-popup.html, ext/display-templates.html, ext/info.html, ext/permissions.html, ext/settings.html, ext/welcome.html
Add `tabindex="0"` to all `<a>` tags without a `href` attribute, enabling keyboard navigation that is consistent with `<a>` tags with the `href` attribute.
Search regex: `<a\b(?! href)(?! tabindex)`.
=> Improve accessibility of links without href

ext/js/app/frontend.js, ext/js/display/display-history.js, ext/js/display/display.js, ext/js/display/search-display-controller.js
Fixes an issue where the _Back_ button would disappear after scanning the query parser twice in the popup. This only affected cases where the query parser would be visible, e.g. button text.
=> Fix history replacement issue

ext/js/display/display-anki.js
Sentence context is empty when opening a fresh page, e.g. via a bookmark.
=> Fix empty sentence on some search page URLs

dev/database-vm.js, ext/js/background/backend.js, ext/js/data/sandbox/string-util.js, ext/js/language/dictionary-importer-media-loader.js, ext/js/language/dictionary-importer.js, ext/js/language/dictionary-worker-handler.js, ext/js/language/dictionary-worker-media-loader.js, ext/js/language/dictionary-worker.js, ext/js/media/media-loader.js, ext/js/media/media-util.js, ext/popup.html, ext/search.html, ext/settings.html, ext/welcome.html
* Dictionary images are now processed in serial rather than in parallel. This should fix this memory issues mentioned in #1918.
* Dictionary image data is now passed from the worker thread to the main thread as a transfered `ArrayBuffer`, which should result in less JSON-serialized message data.
* Dictionary image data is now added to the database as an `ArrayBuffer`, which should hopefully result in less storage memory usage. It is still converted to base64 after being fetched from the database.
=> Dictionary media import improvements

ext/data/schemas/dictionary-term-bank-v3-schema.json, ext/js/display/sandbox/structured-content-generator.js, ext/js/templates/sandbox/anki-template-renderer.js, test/data/dictionaries/valid-dictionary1/term_bank_1.json
This change adds support for adding generic data attributes to structured-content elements. Attributes are prefixed with `data-sc`.
Example: 
```json
{
"tag": "span",
"data": {"testAttribute": "value"},
"content": ["text"]
}
```
Yomichan output:
```html
<span class="gloss-sc-span" data-sc-test-attribute="value">text</span>
```
Anki output:
```html
<span data-sc-test-attribute="value">text</span>
```
Resolves #1925.
=> Structured content data

ext/js/data/database.js, ext/js/language/dictionary-database.js, ext/js/language/dictionary-worker-handler.js, test/test-database.js
* Fixes a rare issue where dictionary settings would be repeatedly re-created if deleting a dictionary in one tab and viewing the settings from another tab. This was due to the dictionary metadata being deleted first; it is now deleted last.
This may fix https://github.com/FooSoft/yomichan/issues/1922#issuecomment-913034108.
=> Database readwrite transaction updates

docs/templates.md, ext/js/templates/sandbox/anki-template-renderer.js
Updated the `regexReplace` and `regexMatch` to support multiple content arguments.
Resolves #1928.
=> Anki template regex helper updates

ext/js/language/dictionary-importer.js
This change normalizes terms and readings before adding to the database. Additionally, empty readings are replaced with the expression.
Resolves #461.
Resolves #1768.
=> Normalize terms and readings during import

ext/css/settings.css, ext/data/schemas/options-schema.json, ext/js/background/backend.js, ext/js/comm/api.js, ext/js/data/options-util.js, ext/js/language/translator.js, ext/js/pages/settings/settings-main.js, ext/js/pages/settings/sort-frequency-dictionary-controller.js, ext/settings.html, test/data/translator-test-inputs.json, test/data/translator-test-results.json, test/test-options-util.js
This change adds support for using a frequency dictionary to sort search results.
Resolves #1742.
=> Frequency dictionary sort

ext/data/schemas/dictionary-kanji-meta-bank-v3-schema.json, ext/data/schemas/dictionary-term-meta-bank-v3-schema.json, ext/js/language/translator.js
Very few dictionaries have actually represented frequency values as a string, and those that do should not be considered valid. If there is a need for generalized string tags, that need can be addressed separately.
=> Ensure frequency values are always numbers

ext/js/language/dictionary-importer.js
[`String.normalize`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize) should not be performed on terms/readings since it has unintended effects, such as modifying kanji.
```js
'\u9038'.normalize('NFC') === '\u9038' // 逸
'\ufa67'.normalize('NFC') === '\u9038' // 逸 => 逸
```
Change originally introduced in #1941.
Originally discussed in #461.
Detected while investigating #1956.
=> Revert term/reading string normalization due to undesirable changes

ext/js/dom/document-util.js, ext/js/input/hotkey-handler.js, ext/js/pages/settings/settings-display-controller.js, ext/permissions.html
Hotkeys using no modifier or only the shift key should be blocked if they correspond to a character input while a text field is focused.
Fixes #1948.
=> Fix hotkey input field conflict

dev/data/manifest-variants.json, ext/manifest.json
Partial workaround for issue mentioned in #1962.
=> Update document-start.js to only run for docs.google.com

docs/templates.md, ext/js/language/sandbox/japanese-util.js, ext/js/templates/sandbox/anki-template-renderer.js, test/test-japanese-util.js
Adds an option `keepProlongedSoundMarks` to the katakana=>hiragana conversion functions.
Handlebars examples:
```handlebars
{{#hiragana}}ローマ字{{/hiragana}}
{{#hiragana keepProlongedSoundMarks=true}}ローマ字{{/hiragana}}
```
Output:
```html
ろうま字
ろーま字
```
Resolves #1947.
=> Katakana to hiragana conversion options

ext/js/display/display.js, ext/js/dom/scroll-element.js
This change does two things:
* Fixes the _nextEntryDifferentDictionary_ and _previousEntryDifferentDictionary_ hotkey actions, which were broken due to previous changes to the dictionary entry data format.
* Improves their behaviour to work when _Result grouping mode_ is _Group term-reading pairs_ or _Group related terms_.
This may potentially require some additional changes to the behaviour of _previousEntryDifferentDictionary_ in the future, as it is not very useful in certain situations, but that can be postponed for now.
Resolves #1830.
=> Hotkey dictionary navigation fix

ext/settings.html
Google Docs canvas rendering has (or is nearing) public deployment, so expose the settings when in non-advanced mode.
=> Make accessibility settings non-advanced

ext/js/pages/settings/popup-preview-controller.js, ext/settings.html
This change adds an option to the settings page which can be used to disable the popup preview. `popup-preview=false` can be added to the URL search query to disable the preview.
Related: #1955
=> Add disable-popup-preview option to the settings page

ext/js/display/display.js
The popup was being opened to an empty `'terms'` page, which was triggering an options update before it was fully configured.
Fixes https://github.com/FooSoft/yomichan/issues/1997#issuecomment-964000124.
=> Fix search page not being cleared properly

ext/js/app/frontend.js
Depending on the settings configuration (`showIframePopupsInRootFrame=true`), a new `<iframe>` being added to the page will cause an open popup to be closed unexpectedly. This change fixes this issue.
=> Don't clear the selection before the text scanner has been enabled

ext/js/yomichan.js
Function now works even if the extension context is invalidated due to unload.
=> Refactor isExtensionUrl

ext/js/app/popup-proxy.js, ext/js/comm/frame-offset-forwarder.js
Improves the results of `FrameOffsetForwarder.getOffset()` to return `null` rather than throw an error.
=> FrameOffsetForwarder fixes

dev/data/manifest-variants.json, ext/js/background/backend.js, ext/js/background/script-manager.js, ext/manifest.json, ext/permissions.html
`ScriptManager` now supports declarative content script updates. On up-to-date browsers, it uses native APIs to accomplish this, falling back to manual execution if those APIs aren't supported.
This will eventually be used to resolve #1962 in a more effective manner.
=> ScriptManager updates

.eslintrc.json, dev/data/manifest-variants.json, ext/background.html, ext/js/accessibility/accessibility-controller.js, ext/js/background/backend.js, ext/manifest.json, ext/sw.js
This change adds the `AccessibilityController` class, which dynamically registers and unregisters the google-docs.js content script. This content script will only be enabled when the `forceGoogleDocsHtmlRendering` setting is enabled.
This resolves #1962.
=> Dynamic Google Docs accessibility

ext/js/dom/document-util.js
This fixes a minor bug where `<input type=checkbox>` would be scanned, and its `.value` property would return `'on'`, which could result in the text "おん" being scanned if romaji => kana conversion was enabled.
=> Fix non-text <input> elements being included in scanning content

ext/js/background/backend.js, ext/js/display/display.js, ext/js/language/dictionary-database.js, ext/js/language/translator.js, test/test-database.js
`matchType` is more generic and a better representation of how the source text matches the text from the database.
=> Replace 'wildcard' parameter with 'matchType'

docs/interfaces/dictionary-entry.ts, ext/js/display/display-generator.js, ext/js/language/dictionary-database.js, ext/js/language/translator.js, test/data/translator-test-results.json
This change exposes information about how the source text was matched to a database entry. This includes two new fields:
* `matchType`, which indicates whether the text was an exact match, a prefix, or a suffix.
* `matchSource`, which indicates which field was matched to the database entry.
The values of these properties are added to the HTML as data attributes.
=> Dictionary database term source info

ext/data/schemas/options-schema.json, ext/js/app/frontend.js, ext/js/data/options-util.js, ext/js/display/display.js, ext/js/language/text-scanner.js, ext/settings.html, test/test-options-util.js
This change adds support for using a suffix wildcard during webpage scanning. Note that the lookup process will take longer with this enabled, since more results are returned from the database.
Note: there is a possible inconsistency when navigating backward in the popup history and the search needs to be re-performed. The search won't do a wildcard search the same way the original scanner did it. This is sufficiently rare and mostly inconsequential, so this issue isn't addressed at this time.
Resolves #2013.
=> Scanning wildcards

ext/js/comm/anki.js
Fixes https://github.com/FooSoft/yomichan/issues/2046
=> Set `Content-Type` header of AnkiConnect requests to `application/json`

docs/browser-bugs.md
* **Browser**: Chrome
* **Date**: 2022-01-31
* **Links**: [Report](https://bugs.chromium.org/p/chromium/issues/detail?id=1292815)
This is the bug reported in #2049.
=> Add info about touch events not working properly for certain webpages

ext/js/pages/settings/anki-controller.js
Adds some more generic aliases for selecting/highlighting default card values.
=> Add additional Anki card marker aliases

ext/js/background/backend.js, ext/js/comm/anki.js
* The return value is now used, in case file storage fails or the name is modified.
* Documentation updated.
=> Improve Anki storeMediaFile

ext/js/display/display-content-manager.js, ext/js/display/display-generator.js, ext/js/display/display.js, ext/js/display/sandbox/structured-content-generator.js, ext/popup.html, ext/search.html
Moving towards generalizing the functionality of the current `MediaLoader`. Also disambiguates with other classes named `*MediaLoader`.
=> Rename MediaLoader to DisplayContentManager

ext/js/display/display-content-manager.js, ext/js/templates/sandbox/anki-template-renderer-content-manager.js, ext/js/templates/sandbox/anki-template-renderer.js, ext/template-renderer.html, test/test-anki-note-builder.js
Generalizes the content manager that is passed into the `StructuredContentGenerator` inside of `AnkiTemplateRenderer`. This class has API parity with the existing `DisplayContentManager` class. Documentation was also added to both classes.
=> AnkiTemplateRendererContentManager

dev/css-to-json-util.js, dev/data/structured-content-overrides.css, ext/css/material.css, ext/css/structured-content.css, ext/data/schemas/dictionary-term-bank-v3-schema.json, ext/data/structured-content-style.json, ext/images/external-link.svg, ext/js/display/display-content-manager.js, ext/js/display/display.js, ext/js/display/sandbox/structured-content-generator.js, ext/js/templates/sandbox/anki-template-renderer-content-manager.js, resources/icons.svg, test/data/dictionaries/valid-dictionary1/term_bank_1.json
This change adds support for structured content links. The following types of links are supported:
* **Internal links**
Internal links begin with `?` and represent a search query string, using the same format that is used on the search.html page. For example, `?query=よみ` will search for the term `よみ`. Internal links are _not_ functional when exported to Anki.
* **External links**
External links begin with `http:` or `https:` and are opened in a new tab. In Yomichan, an external link will include an icon to indicate that it is external. External links _are_ functional when exported to Anki.
Resolves #2031 and probably also some of #1165.
=> Structured content links

ext/js/language/text-scanner.js
This change sets the `capture` parameter to `true` in [`addEventListener`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener). This does not appear to have negative side effects, but it is easy to revert if necessary.
Resolves #111.
Resolves #2086.
=> Text scanner event capture

ext/css/settings.css, ext/settings.html
This change shows a small purple bar on the right side of settings that only appear when advanced mode is enabled. The _Advanced_ toggle is also purple now to better correlate what the bar means.
=> Settings advanced indicators

ext/css/settings.css, ext/settings.html
Fixes some CSS styles that caused an incorrect appearance and adds a longer description about what these settings do.
Originally added in #868.
=> Update input action prevention settings

dev/data/manifest-variants.json, ext/css/display.css, ext/css/popup-outer.css, ext/data/schemas/options-schema.json, ext/js/app/popup-proxy.js, ext/js/app/popup-window.js, ext/js/app/popup.js, ext/js/app/theme-controller.js, ext/js/data/options-util.js, ext/js/display/display.js, ext/manifest.json, ext/popup-preview.html, ext/popup.html, ext/search.html, ext/settings.html, test/test-options-util.js
This change adds support for using the browser/OS's preferred color theme for the theme of the Yomichan popups. It also includes some internal cleanup to how the styles are handled, for simplification purposes.
Resolves #2066.
=> Theme updates

ext/settings.html
Adds warning text "_This is a workaround and it is likely that Google will unfortunately remove support for this workaround in the future._"
=> Add a warning about the future of the Google docs workaround

ext/data/schemas/options-schema.json, ext/js/app/frontend.js, ext/js/data/options-util.js, ext/settings.html, ext/welcome.html, test/test-options-util.js
This change adds a new option: _Hide popup on cursor exit_. When this option is enabled, the cursor exits the popup, the popup will automatically hide. There is also an additional delay parameter. This functions similarly to how the _Auto-hide search popup_ option works when the _Scan modifier key_ is _No key_, but works for any _Scan modifier key_ value.
Resolves #1990.
=> Hide popup on cursor exit

dev/data/structured-content-overrides.css, ext/css/structured-content.css, ext/data/schemas/dictionary-term-bank-v3-schema.json, ext/js/display/sandbox/structured-content-generator.js, test/data/dictionaries/valid-dictionary1/term_bank_1.json
Authors of dictionaries for Yomichan may want to include content from various languages, so I think this is a valuable feature. JMDict, for example, includes Japanese loanword source-words from over 60 different languages.
<details>
<summary>Characters 直次茶冷 displayed in structured content glosses</summary>
⚠The current version of Yomichan seems to apply `lang="ja"` attributes to standard glosses which contain Japanese characters, but not to structured content glosses. By default, most browsers will render the characters "直次茶冷" in simplified Chinese. 
</details>
The current way in which I have inserted supplemental information into JMdict glossaries (see: https://github.com/FooSoft/yomichan/issues/1165) is a little awkward. When the "compact glossaries" option is enabled, all of the …
=> Add new structured content features: lists and the HTML `lang` attribute

ext/js/display/display-generator.js, ext/js/display/sandbox/structured-content-generator.js, ext/js/templates/sandbox/anki-template-renderer.js, test/data/dictionaries/valid-dictionary1/term_bank_1.json
This change will apply the `lang="ja"` attribute if no explicit language is assigned to content which contains Japanese characters.
Resolves #2130, https://github.com/FooSoft/yomichan/pull/2129#issuecomment-1126548732.
=> Structured content auto language

dev/dictionary-validate.js, dev/schema-validate.js, package-lock.json, package.json, test/test-dictionary.js
This change makes `dictionary-validate.js` and `schema-validate.js` able to use https://ajv.js.org as a validator for testing.
This was originally mentioned in https://github.com/FooSoft/yomichan/pull/2129#issuecomment-1126785466:
> I don't know anything about JSON schema validation, and I haven't looked into how Yomichan does it or what engine it uses. My naive hope was that maybe Yomichan could be updated to use a faster validator ([ajv claims to be the fastest](https://github.com/ajv-validator/ajv)) and perhaps that would be enough to solve the problem.
=> Dictionary validate updates

ext/js/app/frontend.js, ext/js/app/popup-factory.js, ext/js/app/popup-proxy.js, ext/js/app/popup-window.js, ext/js/app/popup.js, ext/js/display/display.js, ext/js/dom/popup-menu.js, ext/js/dom/text-source-element.js, ext/js/dom/text-source-range.js
This change does some refactoring to popup positioning and updates how the popup is positioned for source content which spans multiple `DOMRect`s.
The updated algorithm is now:
* Iterate over each `sourceRect`, calculating the popup rect for each rect rather than the full bounding rect.
* If the popup rect doesn't overlap with any other `sourceRect` and if it has the best size, use it as the optimal position.
* If no optimal position is found, calculate the bounding rect of all `sourceRect`s and return that position. (This is the same as the old behaviour.)
Resolves #2124.
=> Popup positioning improvements

ext/css/display.css
By default, links are blue on dark gray, which has poor contrast. This change updates links to be the same color as the text, keeping the underline.
Related: #2143 (shows a link in an error message)
=> Fix the color of links in display footer notifications

ext/js/background/backend.js, ext/js/comm/anki.js, ext/js/comm/api.js
Adds `AnkiConnect.findNotes`. Currently unused, but may be used for part of #2143.
=> Anki findNotes

ext/js/display/display.js
`type` is not subsequently used, so omit it's assignment.
=> Simplify assignment of _contentType = 'clear'

dev/data/manifest-variants.json
This is largely untested, other than that it is able to be loaded. Currently generates the following warning:
```
Reading manifest: Error processing content_security_policy.extension_pages: ‘script-src’ directive contains a forbidden 'unsafe-eval' keyword
```
https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/
=> Add firefox-mv3 build target

ext/info.html, ext/issues.html, ext/js/background/backend.js, ext/js/display/display-generator.js
Follow-up of #2161: this change adds an issues page which will be used to show more detailed information about errors Yomichan may encounter.
Also related to #2157.
=> Add an issues page with information about some errors

ext/js/language/translator.js
Improves sorting in situations where a dictionary entry has differing numbers of definitions with the same score. Entries with a larger number of definitions will take priority.
Resolves #2118.
=> Sort using number of definitions

ext/css/material.css, ext/css/settings.css, ext/data/schemas/options-schema.json, ext/js/display/element-overflow-controller.js, ext/settings.html
This change adds two new modes for dictionary collapsing and adds some documentation for how to configure the appearance.
* **Not collapsible** - Definitions will not be collapsed.
* **Collapsed** - Definitions will show a collapse button if their size exceeds the max height, and they will be collapsed by default.
* **Expanded** - Definitions will show a collapse button if their size exceeds the max height, and they will be expanded by default.
* **Force collapsed** _(new)_ - Definitions will always show a collapse button, and they will be collapsed by default.
* **Force expanded** _(new)_ - Definitions will always show a collapse button, and they will be expanded by default.
Resolves #2168.
=> Collapsible dictionary updates

ext/js/pages/settings/scan-inputs-controller.js, ext/settings.html
* Generally makes the _Add_ button more consistent on several modal popups. The button now appears on the footer.
* Removes the redundant _(?)_ link for the description of the _Audio Sources_ modal.
=> Settings modal updates

ext/js/language/text-scanner.js
Simplifies the internal structure of the input data; the `options` sub-object is redundant and not really useful, so it is now removed.
=> TextScanner refactor

ext/js/language/text-scanner.js
While this works for me, please note that I have no idea what I am doing.
Particularly, I am not sure about the `setTimeout()` bit, and about all the possible edge cases. This also could be slightly optimized by only hooking `selectionchange` when select text is on, but the extra complexity is probably not worth it.
Closes #2071.
=> Do not change selection if user selected text manually

ext/data/schemas/dictionary-term-bank-v3-schema.json, ext/js/display/sandbox/structured-content-generator.js, test/data/dictionaries/valid-dictionary1/term_bank_1.json
Currently, only absolute font-size properties are allowed in styles specified by dictionaries. These font sizes do not scale when the popup scaling factor setting is adjusted in the "Popup Position & Size" section of the Yomichan settings. It would be useful if we could allow relative sizes (smaller, larger, 80%, etc.). I don't think there's any harm in allowing arbitrary strings in this field.
<details>
<summary>Test dictionary in popup at 100% scale</summary>
</details>
<details>
<summary>Test dictionary in popup at 200% scale. The texts with absolute sizes remain the same.</summary>
</details>
<details>
<summary>Cross-reference summaries in my JMdict dictionary which use this property</summary>
</details>
The text-align property is needed to center content in table cells. I'd like to …
=> Add new structured content styling options

ext/js/dom/document-util.js
This change handles the non-standard CSS `zoom` property on Chromium-based browsers, which causes scanning to break.
Will resolve #2176.
=> CSS zoom handling

ext/data/schemas/options-schema.json, ext/js/data/options-util.js
Bug introduced in [#2105](https://github.com/FooSoft/yomichan/pull/2105/files#diff-6d795e7332666b6973a3e802a98ed78cb8f7c0d248e8b47b46918a35a38797f7L215-R224).
=> Fix invalid default values for popupTheme and popupOuterTheme

ext/js/comm/anki-connect.js
This change updates `AnkiConnect.findNoteIds` to not run multiple of the same query. Instead, it will run the query only once and internally distribute the results into resulting array.
Addresses part of the issue mentioned in #2184.
=> Optimize AnkiConnect.findNoteIds

dev/data/manifest-variants.json, ext/js/data/sandbox/string-util.js, ext/js/dom/dom-text-scanner.js, ext/manifest.json, ext/popup-preview.html, ext/popup.html, ext/search.html, test/test-document-util.js, test/test-dom-text-scanner.js
Moves functions `readCodePointsForward` and `readCodePointsBackward` out of `DOMTextScanner` (#2213) and into a new `StringUtil` class so they can be reused.
=> New StringUtil

ext/data/schemas/options-schema.json, ext/js/app/frontend.js, ext/js/app/popup.js, ext/js/data/options-util.js, ext/js/display/display.js, ext/js/dom/document-util.js, ext/js/dom/text-source-element.js, ext/js/dom/text-source-range.js, ext/js/language/text-scanner.js, ext/settings.html, test/test-document-util.js, test/test-options-util.js
The `documentElement`'s computed `zoom` property is inconsistently reported depending on whether it's assigned in CSS and the browser's zoom level.
Related: https://github.com/FooSoft/yomichan/issues/2226#issuecomment-1242971135
=> Exclude documentElement from zoom calculation

ext/js/app/frontend.js, ext/js/display/display.js, ext/js/display/query-parser.js, ext/js/dom/document-util.js, ext/js/language/text-scanner.js, test/test-document-util.js
This change updates `DocumentUtil` to be entirely a static utility class. The reason that this was originally non-static was due to the use of its `_transparentColorPattern` field, which was stored to cache the regex. However, this can just as easily be assigned to the class itself for the same functionality. This simplifies the class API quite a bit and will no longer require instantiating and sharing instances across various classes.
=> DocumentUtil static

ext/js/background/backend.js, ext/js/background/script-manager.js, ext/js/comm/api.js
This change adds a new `loadExtensionScripts` API function, which can be used to dynamically load more extension scripts, such as content scripts, which shouldn't be loaded using `<script>` tags.
=> API loadExtensionScripts

ext/js/dom/document-util.js
This class updates `DocumentUtil` to support extensibility for its `getRangeFromPoint` function. This means that custom handlers can be provided for context-specific situations.
=> DocumentUtil extensibility

ext/js/accessibility/google-docs-util.js, ext/js/accessibility/google-docs.js, ext/js/app/frontend.js, ext/settings.html
This change updates the implementation of the Google Docs accessibility scripts and restores some support for scanning on Google Docs pages. It currently lacks the ability to select text, since there is no real text, but it otherwise functions similar to how scanning input elements works: by creating a temporary "<span title="ඞ">imposter</span>" element and then scanning it.
Google exposes some structural text information in a hidden `<svg>` element if `window._docs_annotate_canvas_by_ext` is assigned to a whitelisted extension ID. This change registers an extension to `DocumentUtil` which will handle the scanning on Google Docs webpages.
The extension ID whitelist can be found by viewing the source of the main Google Docs script and searching for an ID which is known to be on the list, …
=> Google Docs accessibility update

ext/js/accessibility/google-docs-util.js, ext/js/app/frontend.js, ext/js/dom/document-util.js, ext/js/dom/text-source-element.js, ext/js/dom/text-source-range.js, ext/js/language/text-scanner.js, ext/js/pages/settings/popup-preview-frame.js, test/test-document-util.js
This change updates the `TextSourceRange` and `TextSourceElement` APIs to remove anything that is unused, simplify the constructors, and fix an issue related to returning stale rects.
The fixed issue would occur when scanning an element which creates an imposter (such as a textarea) and then the window is resized, which triggers a repositioning of the popup. When this repositioning occurred, it would cause the `getRect/getRects` function to be called, which is selecting a range which is no longer connected to the document, so the popup position would be incorrect.
=> TextSource* API updates

ext/js/accessibility/google-docs-util.js
This improves a few ways that the styling changes are handled when scanning for elements, so it should be slightly more efficient.
Follow-up of #2235.
=> Google Docs accessibility simplifications

ext/issues.html, ext/js/background/backend.js
This change updates the audio download error handling in order to show an error notification in cases of expired server certificates.
Resolves #2242.
=> Audio certificate error notification

ext/js/language/text-scanner.js
The timer was too short, which resulted in the timeout completing before the `selectionchange` event fired.
Fixes #2244.
=> Fix text selection not always working properly

ext/css/search.css
Firefox default textbox style seems to have this, so it needs to be forced to 0.
=> Fix unnecessary margin on search box in Firefox
